- src/components/Channel.js
Cancelling debounced fucntions during unmount.
> Fixing potential memory leak

- src/components/Channel.js
> dont mark own messages as read

- src/components/AutoCompleteTextarea/List.js
> fix autocomplete on mouseclick

- src/components/ChannelList.js
@vishalnarkhede moved the RN listener to the React library can you double check if it's alright?
> added user presence change listener to channellist

- src/components/ChannelList.js
> Updating channel list when channel is updated

- CHANGELOG.md
- src/components/Message.js
- src/components/MessageActionsBox.js
- src/components/MessageList.js
- src/components/MessageSimple.js
- src/utils.js
> Restricting message actions

- src/components/Channel.js
- src/components/Thread.js
> Fixing connection recovery issue with threads

- src/components/Channel.js
- src/components/ChannelList.js
- src/components/ChannelPreviewCompact.js
- src/components/ChannelPreviewLastMessage.js
- src/components/ChannelPreviewMessenger.js
- src/components/Chat.js
- src/components/ChatAutoComplete.js
- src/components/EditMessageForm.js
- src/components/Message.js
- src/components/MessageActionsBox.js
- src/components/MessageCommerce.js
- src/components/MessageInputFlat.js
- src/components/MessageInputLarge.js
- src/components/MessageInputSmall.js
- src/components/MessageList.js
- src/components/MessageLivestream.js
- src/components/MessageSimple.js
- src/components/MessageTeam.js
- src/components/ReactionSelector.js
- src/components/docs/Message.md
- src/components/docs/MessageActionsBox.md
- src/components/docs/MessageInput.md
> Styleguide cleanup

- src/components/ChannelList.js
- src/components/ChannelPreviewCompact.js
- src/components/ChannelPreviewLastMessage.js
- src/components/ChannelPreviewMessenger.js
- src/components/Chat.js
- src/components/docs/Channel.md
- src/components/docs/ChannelContext.md
- src/components/docs/ChannelPreviewCompact.md
- src/components/docs/ChannelPreviewMessenger.md
- src/components/docs/Chat.md
- src/components/docs/ChatContext.md
- src/components/docs/withChannelContext.md
- src/components/docs/withChatContext.md
- styleguide.config.js
> Styleguide cleanup: Docs for chat and channel context

- src/components/Attachment.js
- src/components/Gallery.js
> Attachment issues

- src/components/Channel.js
- src/components/LoadingErrorIndicator.js
- src/components/docs/ChannelContext.md
This is regarding - https://github.com/GetStream/stream-chat-react/issues/42
> Adding support for custom loading error indicator

- src/components/Card.js
* `trimUrl` logical operator is corrected. Otherwise, rest of the case won't work.
* fixed some typos in comments since they are extracted to doc, they are visible to user directly.
> Fix logic operator of trimUrl in Card

- src/components/Avatar.js
Due operator precedence, intention (apply loaded class if avatar is loaded) was reflected mistakenly (was always being applied).
> fix(avatar): Correct loaded classname

- src/components/MessageInputFlat.js
Expression result is already boolean, there is no need to check again, instead use it directly.
> refactor(message-input-flat): Simplify disabled condition

- src/components/Channel.js
> CHAT-541: Limiting API calls for mark read functionality

- src/components/Channel.js
> CHAT-704: Making empty typing object immutable

- src/components/MessageList.js
- types/index.d.ts
Adds a InitialMessageComponent to MessageList props.
> Add HeaderComponent to MessageList

- src/components/MessageInputFlat.js
- src/components/MessageInputLarge.js
- src/components/MessageInputSmall.js
- src/styles/MessageInput.scss
- src/styles/MessageInputFlat.scss
- src/styles/SmallMessageInput.scss
> Fix message input styles

- src/components/Channel.js
> CHAT-721: Fixing unbinding of visibility listener

- src/components/Message.js
- src/components/MessageSimple.js
- src/components/ReactionSelector.js
- src/components/ReactionsList.js
- src/components/index.js
- types/index.d.ts
> CHAT-669: Fixing types of message component

- src/components/MessageActionsBox.js
Fixes typos in actions and default props.
> fix(message-actions-box): correct typos

- src/components/MessageList.js
For the issue: https://github.com/GetStream/stream-chat-react/issues/67
> CHAT-807: Fixing scroll issue on message list

- src/components/Message.js
- src/components/MessageCommerce.js
- src/components/MessageLivestream.js
- src/components/MessageSimple.js
- src/components/MessageTeam.js
- types/index.d.ts
> CHAT-669: Changing openThread func name in Message component to fix conflict with channel context

- examples/messaging/src/App.js
- src/components/ChannelList.js
> set customActiveChannel

- .travis.yml
> Ensure latest yarn is used

- .eslintrc.json
- package.json
- src/components/Attachment.js
- src/components/Audio.js
- src/components/AutoCompleteTextarea/Textarea.js
- src/components/Message.js
- src/components/MessageInput.js
- src/components/MessageList.js
- src/components/MessageSimple.js
- src/components/MessageTeam.js
- src/components/ReactionSelector.js
- src/components/SimpleReactionsList.js
- src/components/Thread.js
- src/components/docs/Gallery.md
- src/components/docs/data.js
- src/utils.js
- yarn.lock
Add sonarjs to lint similar to stream-chat-js.
> Add sonarjs for linting

- package.json
- src/components/Chat.js
- src/components/Message.js
- src/components/MessageList.js
- yarn.lock
Update sonarjs with the latest rules(released today)
Fix a typo from previous PR #84 in a separate commit
> Bump sonarjs

- CHANGELOG.md
- src/components/AutoCompleteTextarea/Textarea.js
- src/components/InfiniteScroll.js
- src/components/MessageList.js
- src/components/MessageLivestream.js
- src/components/MessageTeam.js
- src/components/ReverseInfiniteScroll.js
- types/index.d.ts
> Prop for custom system message

- src/components/ChannelList.js
- types/index.d.ts
> CRNS-29, CRNS-32: Handling channel.truncated and channel.deleted events

- types/index.d.ts
> add sendbutton to types.d.ts

- package.json
- yarn.lock
> Remove parcel

- src/components/Attachment.js
- src/components/Gallery.js
- src/components/InfiniteScrollPaginator.js
- src/components/MessageInputFlat.js
- src/components/MessageInputLarge.js
- src/components/MessageInputSmall.js
- src/components/MessageList.js
- src/index.js
- src/styles/Attachment.scss
- src/styles/Gallery.scss
- src/styles/InfiniteScrollPaginator.scss
- src/styles/MessageInput.scss
- src/styles/MessageInputFlat.scss
- src/styles/MessageList.scss
- src/styles/SmallMessageInput.scss
> remove inline styles

- README.md
- src/components/Message.js
- src/components/Window.js
Refactored code of some components using some of the best practices in React
> chore: code refactoring

- src/components/ChannelPreviewLastMessage.js
- yarn.lock
> Fixing lodash trucate in ChannelPreviewLastMessage

- src/components/ChannelList.js
- src/components/ChannelListMessenger.js
- src/components/ChannelListTeam.js
- types/index.d.ts
> CRS-18: Fixing LoadingIndicator prop and adding LoadingErrorIndicator prop for ChannelList

- src/components/InfiniteScrollPaginator.js
- src/styles/InfiniteScrollPaginator.scss
> Fixing loading indicator in InfiniteScrollPaginator

- src/components/MessageInput.js
Fixes: editing a message with a file attached duplicated the message. Now it checks for duplicates and skips if they exist.
> fix for duplicate file uploads

- src/components/Message.js
> Fixing the check for moderator role

- src/components/MessageInputLarge.js
- src/utils.js
> Fix in typing indicator to exclude current user

- src/components/Channel.js
Fix on js client - https://github.com/GetStream/stream-chat-js/pull/276/files
> Fixing remove message functionality for threads

- src/components/Message.js
> Fixing the mute notification message

- src/components/EditMessageForm.js
- src/components/MessageInputFlat.js
- src/components/MessageInputLarge.js
- src/components/MessageInputSmall.js
> fix proptype for maxNumberOfFiles

- src/components/ChannelList.js
Fixes - https://github.com/GetStream/stream-chat-react/issues/185
> Fixing channel.updated and channel.deleted handlers

- src/components/MessageList.js
> show date separator before deleted message

- src/components/Message.js
> add check for mutes on channel config

- src/components/ChannelHeader.js
- src/components/ChannelList.js
- src/components/ChannelPreviewMessenger.js
- src/components/Chat.js
- src/styles/ChannelHeader.scss
- src/styles/ChannelList.scss
- types/index.d.ts
> rework responsive menu

- package.json
- src/components/Message.js
- yarn.lock
Dependent on https://github.com/GetStream/stream-chat-js/pull/288
> Adding fix for checking if current user is moderator

- types/index.d.ts
> add types for setActiveChannelOnMount

- src/components/Channel.js
- src/components/ChannelPreview.js
- src/components/ChannelPreviewCompact.js
- src/components/ChannelPreviewCountOnly.js
- src/components/ChannelPreviewLastMessage.js
- src/components/ChannelPreviewMessenger.js
- types/index.d.ts
> fix for no currently activeChannel

- src/components/Gallery.js
- src/i18n/en.json
- src/i18n/fr.json
- src/i18n/hi.json
- src/i18n/it.json
- src/i18n/nl.json
- src/i18n/ru.json
- src/i18n/tr.json
> Adding missing translation key in Gallery component

- src/components/ChannelPreview.js
> add check for optioinal activeChannel

- package.json
> Removing babel output log

- src/components/ChannelPreview.js
- src/components/ChannelPreviewCompact.js
- src/components/ChannelPreviewCountOnly.js
- src/components/ChannelPreviewLastMessage.js
- src/components/ChannelPreviewMessenger.js
- types/index.d.ts
> Adding direct messaging support for channel preview

- src/i18n/fr.json
Hi !
This PR fixes a few typos in the french translation file.
> Fix typos in french i18n file

- src/components/MessageInput.js
When uploading images and other files, the other files did not upload because the checking for duplicates was wrong.
> fix missing attachments

- src/components/MessageList.js
- src/components/MessageSimple.js
- src/components/MessageTeam.js
> add check for readBy undefined

- .eslintrc.json
- yarn.lock
> add eslint-jest plugin

- .eslintrc.json
- package.json
- src/components/ChatDown/ChatDown.js
- src/components/ChatDown/__tests__/ChatDown.test.js
- src/components/ChatDown/__tests__/__snapshots__/ChatDown.test.js.snap
- yarn.lock
> React test renderer

- src/components/Thread/Thread.js
- src/styles/MessageList.scss
- src/styles/Thread.scss
This commit makes the whole thread scrollable, instead of having the first message stick to the top of the thread.
It also fixes some spacing issues around the not-first messages in the thread (there was too much padding) and the "Start of a new thread" separator (too much / too little padding)
> CRS-242 Thread layout rework

- src/components/ChannelHeader/ChannelHeader.js
- src/components/DateSeparator/DateSeparator.js
- src/components/Loading/LoadingErrorIndicator.js
- src/components/Window/Window.js
> remove invalid @extends in component docs

- src/components/MessageInput/MessageInputLarge.js
- src/components/MessageInput/MessageInputSmall.js
- src/styles/MessageInput.scss
- src/styles/SmallMessageInput.scss
This fixes an alignment issue with the message input icons on the <MessageInputLarge /> component and some minor alignment issues on the <MessageInputSmall /> component:
_Mobile before_:
_Mobile after_:
> Fix message input icons alignment

- src/styles/MessageInput.scss
- src/styles/MessageInputFlat.scss
- src/styles/SmallMessageInput.scss
- src/styles/_base.scss
> fix layout on fileupload

- src/components/Attachment/Attachment.js
- src/styles/Attachment.scss
> fix video attachment rendering

- src/components/SafeAnchor/__tests__/SafeAnchor.test.js
This just tests if the sanitize url function was called with the right prop. No snapshot tests for now because that's literally all the component does
> SafeAnchor test

- README.md
- rollup.config.js
This exposes .scss sources. Resolves https://github.com/GetStream/stream-chat-react/issues/190.
> Expose .scss sources on dist

- examples/commerce/package.json
- examples/livestream/package.json
- examples/livestream/yarn.lock
- examples/messaging/package.json
- examples/team/package.json
- examples/team/yarn.lock
> upgrade react example apps

- README.md
- src/styles/ReactionList.scss
- src/styles/_variables.scss
This improves the extensibility of our SCSS styles by making providing a way to override the path for the required assets.
> Improve scss extensibility

- types/index.d.ts
Fixes for https://github.com/GetStream/stream-chat-react/issues/261
> Fix types for setActiveChannel and LoadMoreButton

- src/components/ChatDown/ChatDown.js
- src/components/ChatDown/__tests__/ChatDown.test.js
> ChatDown uses hooks

- src/components/DateSeparator/__tests__/DateSeparator.test.js
- src/components/DateSeparator/__tests__/__snapshots__/DateSeparator.test.js.snap
Add tests for DateSeparator component
> CRS-120 date separator tests

- package.json
> upgrade react

- src/styles/_variables.scss
Fix [default](https://github.com/GetStream/stream-chat-react/pull/264/files#diff-5fe3d0a4e432178fef40b09df0627c4fL12) asset path.
Resolves https://github.com/GetStream/stream-chat-react/issues/274
> Fix default asset path

- src/components/Attachment/Attachment.js
- src/components/Gallery/Gallery.js
- src/components/Message/MessageRepliesCountButton.js
- src/components/Message/MessageSimple.js
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/MessageDeleted.js
- src/components/Reactions/ReactionSelector.js
- src/components/Reactions/ReactionsList.js
Add MessageSimple component tests.
> Add MessageSimple component tests

- package.json
- src/components/Message/MessageSimple.js
- types/index.d.ts
This PR is a follow-up of https://github.com/GetStream/stream-chat-react/pull/271.
1. It refactors the render function to reduce its complexity so it will no longer throw a [sonar/cognitive-complexity](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/cognitive-complexity.md) Eslint error there.
2. It enables typescript `@ts-check` and fixes types accordingly.
> Improve message simple component

- src/components/Tooltip/__tests__/Tooltip.test.js
- src/components/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
Just a very simple snapshot test, so this component i covered.
> CRS-157 Add tooltip snapshot test (for completeness)

- src/components/Message/MessageLivestream.js
- src/components/Message/__tests__/MessageLivestream.test.js
- src/components/MessageActions/MessageActionsBox.js
- src/components/MessageList/__tests__/MessageList.test.js
- src/components/Reactions/SimpleReactionsList.js
- types/index.d.ts
Improve <MessageLivestream /> component:
- Add tests.
- Enable ESLint.
- Enable type check.
> Add message livestream tests

- src/components/Audio/Audio.js
- src/components/Audio/__tests__/Audio.test.js
> CRS-102 Audio component tests

- src/components/Message/MessageTeam.js
- src/components/Message/__tests__/MessageTeam.test.js
- types/index.d.ts
- Add <MessageTeam /> tests
- Enable ESLint
- Enable types
> Add <MessageTeam /> tests

- src/components/Audio/Audio.js
- src/components/Audio/__tests__/Audio.test.js
> CRS-174 convert Audio component to hooks, fix tests

- src/components/Message/MessageTeam.js
Fix type checking in handleRetry callback for MessageTeam
> Add type ignore for retry handler

- src/docs/MessageInput.md
While checking a SO question, saw some typos.
> Fix some typos

- src/components/Chat/Chat.js
- src/components/Chat/__tests__/Chat.test.js
- types/index.d.ts
> feature/#212/add Chat initialNavOpen prop

- src/components/MessageInput/MessageInputState.js
- src/components/MessageInput/MessageInputTypes.ts
- src/components/MessageInput/__tests__/MessageInput.test.js
- types/index.d.ts
This allows users to remove mentions by just getting rid of (part of) the text in the input.
> CRS-256 mentioned users

- src/components/InfiniteScrollPaginator/__tests__/InfiniteScroll.test.js
I added some basic tests for the InfiniteScroll component. It tests quite little of the actual scroll event handling code, because jsdom does not implement any layout features, which makes it quite difficult to test these things.
> CRS-127 Add tests for InfiniteScroll

- src/components/Window/Window.js
- src/components/Window/__tests__/Window.test.js
> CRS-93 Tests/hooks for Window

- src/components/SafeAnchor/SafeAnchor.js
- src/components/SafeAnchor/__tests__/SafeAnchor.test.js
> CRS-86 SafeAnchor: functional component, slightly more extensive test

- package.json
- src/components/Message/Message.js
- src/components/Message/__tests__/Message.test.js
- src/components/Message/__tests__/MessageCommerce.test.js
- src/components/Message/__tests__/MessageLivestream.test.js
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/__tests__/MessageTeam.test.js
- src/mock-builders/generator/index.js
- src/mock-builders/generator/reaction.js
- types/index.d.ts
- yarn.lock
- Add tests to the <Message /> component.
Depends on: https://github.com/GetStream/stream-chat-js/pull/344
> Add tests and improve <Message /> component

- src/utils.js
* fixes an issue when typing markdown manually it also tries to convert the link to markdown
* allows app:// deeplinks
> Fix: markdown issue and allow app:// deeplinks

- src/components/Attachment/Attachment.js
more fixes to attachment component
> add media type

- jest.config.js
- src/components/Reactions/ReactionSelector.js
- src/components/Reactions/ReactionsList.js
- src/components/Reactions/SimpleReactionsList.js
- src/components/Reactions/__tests__/ReactionSelector.test.js
- src/components/Reactions/__tests__/ReactionsList.test.js
- src/components/Reactions/__tests__/SimpleReactionsList.test.js
- src/mock-builders/generator/reaction.js
- types/index.d.ts
> Tests for ReactionSelector, ReactionsList and SimpleReactionsList

- src/components/Message/Message.js
- src/components/Message/__tests__/Message.test.js
- src/components/Message/__tests__/utils.test.js
- src/components/Message/utils.js
- src/components/MessageActions/MessageActionsBox.js
- src/components/MessageList/MessageList.js
- src/utils.js
- types/index.d.ts
This is the first step in a bigger refactoring of the message components. The key goal of this PR is to extract functionality that is shared between MessageUI components and that now lives in the HO one, so we can more easily reuse it later on other functional components or custom hooks.
> Message components refactoring part I

- src/components/Message/MessageDeleted.js
- src/components/Message/MessageSimple.js
- src/components/Message/__tests__/MessageDeleted.test.js
> Message deleted component refactoring

- src/components/MessageInput/SendButton.js
- src/components/MessageInput/__tests__/SendButton.test.js
Add SendButton test, convert to hooks, fix type
> CRS-154 Add SendButton test, convert to hooks, fix type

- src/components/AutoCompleteTextarea/Textarea.js
- src/components/ChatAutoComplete/ChatAutoComplete.js
> Implement queryMembers endpoint for mentions feature

- src/components/Avatar/Avatar.js
> CRS-176: add types to avatar component

- src/components/MessageInput/MessageInputLarge.js
- types/index.d.ts
#165 Submit a pull request
This should fix type issues with TranslationContext (i.e. components like Channel now no longer require t / tDateTimeParser to be passed as props).
> Fix translation context type issues

- src/components/Message/MessageDeleted.js
- src/components/Message/__tests__/MessageDeleted.test.js
- src/components/Message/utils.js
- types/index.d.ts
~To be merged after https://github.com/GetStream/stream-chat-react/pull/336.~
Making MessageDeleted a functional component.
> <MessageDeleted /> hooks

- src/@types/image-files.d.ts
- src/components/Card/Card.js
- src/components/ChatDown/ChatDown.js
- types/index.d.ts
> CRS-191: add types to ChatDown component

- src/components/Tooltip/Tooltip.js
> CRS-229: add types for tooltip

- src/components/ChannelSearch/ChannelSearch.js
> CRS-188: add types to channelsearch component

- src/components/Message/MessageRepliesCountButton.js
- src/components/Message/__tests__/MessageRepliesCountButton.test.js
- src/context/TranslationContext.js
- types/index.d.ts
Test and refactor MessageRepliesCountButton
> CRS-79 MessageRepliesCountButton

- src/context/ChatContext.js
- types/index.d.ts
> CRS-189: add chat types

- src/components/LoadMore/LoadMoreButton.js
- src/components/LoadMore/__tests__/LoadMoreButton.test.js
> CRS-207: loadmorebutton type/tests

- src/components/EmptyStateIndicator/EmptyStateIndicator.js
- src/components/EmptyStateIndicator/__tests__/EmptyStateIndicator.test.js
> CRS-56: emptystateindicator refactor

- src/components/EventComponent/EventComponent.js
> CRS-197: add types to event component types

- src/components/DateSeparator/DateSeparator.js
- src/components/DateSeparator/__tests__/DateSeparator.test.js
> CRS-193: add types to DateSeparator

- src/components/ChannelPreview/ChannelPreview.js
> FIX: channel unread_count

- package.json
- src/components/ChannelPreview/ChannelPreview.js
- src/components/ChannelPreview/ChannelPreviewCompact.js
- src/components/ChannelPreview/ChannelPreviewLastMessage.js
- src/components/ChannelPreview/ChannelPreviewMessenger.js
- src/components/ChannelPreview/__tests__/ChannelPreview.test.js
- src/components/ChannelPreview/__tests__/ChannelPreviewCompact.test.js
- src/components/ChannelPreview/__tests__/ChannelPreviewLastMessage.test.js
- src/components/ChannelPreview/__tests__/ChannelPreviewMessenger.test.js
- src/components/ChannelPreview/__tests__/__snapshots__/ChannelPreviewCompact.test.js.snap
- src/components/ChannelPreview/__tests__/__snapshots__/ChannelPreviewLastMessage.test.js.snap
- src/components/ChannelPreview/__tests__/__snapshots__/ChannelPreviewMessenger.test.js.snap
- src/components/ChannelPreview/__tests__/utils.test.js
- src/components/ChannelPreview/utils.js
- src/components/Reactions/__tests__/SimpleReactionsList.test.js
- src/mock-builders/event/index.js
- src/mock-builders/generator/attachment.js
- src/mock-builders/generator/index.js
- src/mock-builders/generator/user.js
- src/mock-builders/index.js
- yarn.lock
> Tests and refactoring of ChannelPreview component

- jest.config.js
- package.json
- src/components/ChannelPreview/ChannelPreview.js
- src/components/ChannelPreview/ChannelPreviewCompact.js
- src/components/ChannelPreview/ChannelPreviewLastMessage.js
- src/components/ChannelPreview/ChannelPreviewMessenger.js
- src/components/ChannelPreview/__tests__/ChannelPreview.test.js
- src/components/ChannelPreview/__tests__/utils.test.js
- src/components/ChannelPreview/utils.js
- src/components/DateSeparator/DateSeparator.js
- src/components/DateSeparator/__tests__/DateSeparator.test.js
- src/components/Reactions/ReactionsList.js
- src/components/Reactions/SimpleReactionsList.js
- src/components/Reactions/__tests__/SimpleReactionsList.test.js
- src/context/ChatContext.js
- src/mock-builders/event/index.js
- src/mock-builders/generator/attachment.js
- src/mock-builders/generator/index.js
- src/mock-builders/generator/user.js
- src/mock-builders/index.js
- src/utils.js
- types/index.d.ts
- yarn.lock
Dependent on https://github.com/GetStream/stream-chat-react/pull/362
> Hooks and typescript for ChannelPreview & UI component

- src/components/ChatAutoComplete/__tests__/ChatAutocomplete.test.js
> CRS-117 Add tests for ChatAutoComplete

- src/components/Window/Window.js
- src/components/Window/__tests__/Window.test.js
- src/context/ChannelContext.js
> CRS-232: window types

- src/components/MessageList/MessageNotification.js
- src/components/MessageList/__tests__/MessageNotification.test.js
> CRS-145: add tests/ts for MessageNotification

- src/components/InfiniteScrollPaginator/InfiniteScrollPaginator.js
- src/components/Loading/LoadingIndicator.js
- src/components/Message/MessageTeam.js
> CRS-201: InfinteScrollPaginator types

- src/components/Attachment/Attachment.js
- src/components/Attachment/AttachmentActions.js
- src/components/Attachment/__tests__/Attachment.test.js
- src/components/Attachment/__tests__/AttachmentActions.test.js
- src/components/Attachment/__tests__/Audio.test.js
- src/components/Attachment/__tests__/File.test.js
- src/components/Attachment/__tests__/__snapshots__/AttachmentActions.test.js.snap
- src/components/Attachment/__tests__/__snapshots__/File.test.js.snap
- src/mock-builders/generator/attachment.js
> Tests for Attachment and its child components

- .github/workflows/size.yml
> Add size comparison action

- src/components/TypingIndicator/TypingIndicator.js
- src/components/TypingIndicator/__tests__/TypingIndicator.test.js
> CRS-158: TypingIndicator refactor

- src/components/CommandItem/CommandItem.js
- types/index.d.ts
> CRS-192: add types to command item

- src/components/Thread/Thread.js
- src/components/Thread/__tests__/Thread.test.js
> CRS-156 Add Thread tests

- src/components/UserItem/UserItem.js
- src/components/UserItem/__tests__/UserItem.test.js
- types/index.d.ts
> CRS-159 UserItem refactor

- src/components/Message/MessageOptions.js
- src/components/Message/MessageSimple.js
- src/components/Message/MessageText.js
- src/components/Message/__tests__/MessageOptions.test.js
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/__tests__/MessageText.test.js
- src/components/MessageActions/MessageActions.js
- src/components/MessageActions/__tests__/MessageActions.test.js
- src/components/MessageActions/index.js
- types/index.d.ts
A follow-up on the improvements that should enable more code reusability and maintainability for message UI components.
Depends on: https://github.com/GetStream/stream-chat-react/pull/373
- To-do:
> Message ui components improvements part II

- src/components/Modal/Modal.js
- src/components/Modal/__tests__/Modal.test.js
- src/i18n/en.json
- src/i18n/fr.json
- src/i18n/hi.json
- src/i18n/it.json
- src/i18n/nl.json
- src/i18n/ru.json
- src/i18n/tr.json
- types/index.d.ts
> Refactor Modal, improve tests (add required props where needed)

- src/components/MessageList/MessageList.js
- types/index.d.ts
> make loadingindicator overridable messagelist

- src/components/Attachment/Attachment.js
> Attachment component to FC

- src/components/MessageList/CustomNotification.js
- src/components/MessageList/__tests__/CustomNotification.test.js
- src/components/MessageList/__tests__/MessageNotification.test.js
> test CustomNotification component

- src/components/Message/MessageCommerce.js
- src/components/Message/MessageOptions.js
- src/components/Message/MessageText.js
- src/components/Message/__tests__/MessageCommerce.test.js
- src/components/Message/__tests__/MessageOptions.test.js
- src/components/Message/__tests__/MessageText.test.js
- types/index.d.ts
This makes <MessageCommerce /> a functional component while keeping backward compatibility.
Depends on: https://github.com/GetStream/stream-chat-react/pull/374
> Message commerce hooks

- src/components/Message/MessageLivestream.js
- src/components/Message/__tests__/MessageLivestream.test.js
- src/components/Message/__tests__/utils.test.js
- src/components/Message/hooks/__tests__/useReactionHandler.test.js
- src/components/Message/hooks/useReactionHandler.js
- src/components/Message/utils.js
- src/components/MessageActions/MessageActions.js
- src/components/MessageActions/__tests__/MessageActions.test.js
- types/index.d.ts
Convert <MessageLivestream /> to hooks.
> Message livestream hooks

- src/components/Message/MessageTeam.js
- src/components/Message/__tests__/MessageTeam.test.js
- src/components/MessageActions/MessageActions.js
- types/index.d.ts
Makes <MessageTeam /> a functional component.
> Message team hooks

- src/components/LoadMore/LoadMorePaginator.js
- src/components/LoadMore/__tests__/LoadMorePaginator.test.js
> Tests/crs 130/load more paginator

- src/components/MessageList/MessageList.js
> clean up the message list a bit

- src/components/Channel/Channel.js
- src/components/Chat/Chat.js
- src/docs/data.js
> fix docs error

- src/components/ChannelList/hooks/usePaginatedChannels.js
> Fixing pagination issue with ChannelList upon filters change

- src/components/ChannelList/hooks/usePaginatedChannels.js
> Fixing pagination for channel list

- src/components/Message/hooks/__tests__/useOpenThreadHandler.test.js
- src/components/Message/hooks/__tests__/useRetryHandler.test.js
- src/components/Message/hooks/useOpenThreadHandler.js
- src/components/Message/hooks/useRetryHandler.js
Improve some hooks to make sure we have a clear API for overwriting custom handlers, allowing for a cleaner way of customizing message components.
> Improve message hooks

- src/components/MessageList/MessageList.js
> remove TypingIndicator from MessageList

- src/components/Channel/Channel.js
> enable eslint for channel

- src/components/MessageInput/MessageInputFlat.js
- src/components/MessageInput/MessageInputLarge.js
- src/components/MessageInput/MessageInputSmall.js
- src/styles/MessageInput.scss
- src/styles/MessageInputFlat.scss
- src/styles/SmallMessageInput.scss
> fix mentions hiding behind image previewer

- src/components/Message/MessageLivestream.js
- src/components/Message/__tests__/MessageLivestream.test.js
- types/index.d.ts
Following https://github.com/GetStream/stream-chat-react/pull/429.
> Refactor message livestream tests

- src/components/Message/Message.js
- src/components/Message/__tests__/Message.test.js
> Make message hoc functional

- src/components/MessageList/MessageList.js
- src/components/MessageList/MessageListInner.js
- types/index.d.ts
> remove rest of event history related logic

- src/components/Message/Message.js
- src/components/Message/MessageCommerce.js
- src/components/Message/MessageLivestream.js
- src/components/Message/MessageSimple.js
- src/components/Message/MessageTeam.js
- src/components/Message/MessageText.js
- src/components/Message/hooks/__tests__/useReactionHandler.test.js
- src/components/Message/hooks/__tests__/useUserHandler.test.js
- src/components/Message/hooks/useReactionHandler.js
- src/components/Message/hooks/useUserHandler.js
- src/docs/MessageHooks.md
Some minor fixes to Message HOC component and custom hooks.
> Message component improvements

- src/components/Chat/Chat.js
- src/components/Message/Message.js
- src/components/Message/MessageLivestream.js
- src/components/Message/MessageTeam.js
- src/components/Message/hooks/useEditHandler.js
Fixes some issues regarding the message actions.
> Fixmessage actions

- src/components/Chat/__tests__/Chat.test.js
A test to better cover the issue fixed in #b44c7b9c.
> Update test to cover mutes first load update

- src/components/Message/MessageLivestream.js
- src/components/Message/MessageTeam.js
- src/components/Message/MessageText.js
- src/utils.js
- types/index.d.ts
Memoize renderText function in Message components.
> Memoize renderText function in Message components

- examples/messaging/src/App.js
- examples/team/src/App.js
- src/components/ChannelList/ChannelList.js
fixes: #451 
updating examples so issue above doesn't happen
> FIX: rerendering examples

- src/components/ChannelHeader/ChannelHeader.js
> get openMobileNav from ChatContext

- src/utils.js
should fix the  runtime issue with https://codepen.io/team/stream/pen/pYrMJe?editors=0010
> react-markdown uriTransformer imported instead of require

- package.json
- src/components/ChannelList/ChannelList.js
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/ChannelList/hooks/useChannelVisibleListener.js
- src/mock-builders/event/channelVisible.js
- src/mock-builders/event/index.js
- types/index.d.ts
- yarn.lock
depends on: https://github.com/GetStream/stream-chat-js/pull/398
fixes: #484
> add useChannelVisibleListener

- src/components/ChannelList/ChannelList.js
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/ChannelList/hooks/useChannelHiddenListener.js
- src/mock-builders/event/channelHidden.js
- src/mock-builders/event/index.js
- types/index.d.ts
also includes fixes for useChannelDeleted listener
fixes: #484
> add useChannelHiddenListener

- src/components/Attachment/FileAttachment.js
> Fix: use Number.isFinite

- package.json
- yarn.lock
> bump react-file-utils

- package.json
- src/components/Attachment/__tests__/Audio.test.js
- yarn.lock
> Upgrading stream-chat version to 2.2.0

- src/components/ChannelList/ChannelList.js
- src/components/ChannelList/hooks/usePaginatedChannels.js
- types/index.d.ts
> Fixing types for ChannelList component

- rollup.config.js
> Fix linkify module resolution

- package.json
- types/index.d.ts
- yarn.lock
Adjust generic usage for ABC of stream chat js generics
> change generics for stream chat js

- rollup.config.js
Fix issue with the CSS bundle when running in watch mode.
> Fix rollup css bundle

- package.json
- yarn.lock
> bump stream-chat to v2.4.0

- package.json
- yarn.lock
related https://github.com/GetStream/react-file-utils/pull/21
> CRS-17: update react-file-utils

- src/components/ChannelPreview/ChannelPreviewCompact.js
- src/components/ChannelPreview/ChannelPreviewLastMessage.js
- src/components/ChannelPreview/ChannelPreviewMessenger.js
- src/components/ChannelPreview/__tests__/__snapshots__/ChannelPreviewCompact.test.js.snap
- src/components/ChannelPreview/__tests__/__snapshots__/ChannelPreviewLastMessage.test.js.snap
- src/components/ChannelPreview/__tests__/__snapshots__/ChannelPreviewMessenger.test.js.snap
> CRS-288: add first letter of display name to avatar

- src/components/Attachment/Attachment.js
- src/components/ChannelList/hooks/usePaginatedChannels.js
- src/components/ChannelList/utils.js
- types/index.d.ts
> TS fixes 550, 541, 542

- src/components/Attachment/Attachment.js
- src/components/Gallery/Image.js
- src/components/Gallery/__tests__/Image.test.js
- src/components/Gallery/index.js
> Rename Image component to ImageComponent

- examples/typescript-app/package.json
- examples/typescript-app/yarn.lock
- types/index.d.ts
Add any to defaults and update TS example
> add any and update example

- src/components/Channel/channelState.js
> keep channel.members in sync on events

- src/components/MessageList/__tests__/VirtualizedMessageList.test.js
- src/components/MessageList/__tests__/__snapshots__/VirtualizedMessageList.test.js.snap
> test: fix virtual list snapshotting

- src/styles/VirtualMessage.scss
> fix word-wrap issue on FixedHeightMessage

- src/components/TypingIndicator/TypingIndicator.js
- src/components/TypingIndicator/__tests__/TypingIndicator.test.js
- src/mock-builders/generator/channel.js
- src/mock-builders/index.js
> feat: TypingIndicator renders null if typing_events is disabled

- src/components/ChannelList/hooks/usePaginatedChannels.js
> fix channellist pagination bug

- types/index.d.ts
> types: change sendMessage text to optional

- CHANGELOG.md
> change log for 3.3.0

- CHANGELOG.md
- src/components/Message/__tests__/Message.test.js
- src/components/Message/hooks/useUserRole.js
> add-isModerator-role-check

- CHANGELOG.md
- src/components/Channel/Channel.js
> thread-load-more-bug

- src/components/Message/Message.js
- src/components/Message/MessageCommerce.js
- src/components/Message/MessageLivestream.js
- src/components/Message/MessageSimple.js
- src/components/Message/MessageTeam.js
- src/components/MessageList/MessageList.js
- src/components/MessageList/MessageListInner.js
https://github.com/GetStream/stream-chat-react/issues/653
https://github.com/GetStream/stream-chat-react/issues/649
> GitHub issues

- .eslintignore
- src/components/Message/MessageLivestream.js
- src/components/Message/MessageSimple.js
- src/components/Message/MessageTeam.js
- src/components/Message/__tests__/MessageLivestream.test.js
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/__tests__/MessageTeam.test.js
- types/index.d.ts
https://github.com/GetStream/stream-chat-react/issues/384
> Customize edit input

- package.json
- src/i18n/__tests__/Streami18n.test.js
- yarn.lock
> bump mml-react

- types/index.d.ts
> fix-mentions-type

- examples/messaging/src/App.js
- examples/messaging/yarn.lock
> update messaging app

- src/components/ChannelList/ChannelList.js
- src/components/ChannelList/hooks/useMessageNewListener.js
- types/index.d.ts
> Adding a prop allowNewMessagesFromUnfilteredChannels on ChannelList

- src/components/MessageInput/hooks/messageInput.js
> adds parent id to keystroke

- CHANGELOG.md
> 3.5.0-changelog

- src/components/MessageInput/hooks/messageInput.js
> upload-psd-bug

- package.json
- yarn.lock
> chore: bump mml-react

- CHANGELOG.md
- src/components/MessageInput/hooks/messageInput.js
> delay closeEmojiPicker event listener

- src/components/ChannelList/ChannelList.js
- src/components/ChannelList/__tests__/ChannelList.test.js
- types/index.d.ts
> Custom channellist filter

- examples/commerce/package.json
- examples/commerce/src/App.js
- examples/commerce/yarn.lock
- examples/livestream/package.json
- examples/livestream/src/App.js
- examples/livestream/yarn.lock
- examples/messaging/package.json
- examples/messaging/src/App.js
- examples/messaging/yarn.lock
- examples/team/package.json
- examples/team/src/App.js
- examples/team/yarn.lock
- examples/typescript-app/package.json
- examples/typescript-app/src/App.tsx
- examples/typescript-app/yarn.lock
> refactor-example-apps

- types/index.d.ts
> fix: missing export for VirtualizedMessageList type

- src/components/Message/hooks/usePinHandler.js
> channel-type-permissions-update

- src/components/ChannelHeader/ChannelHeader.js
- types/index.d.ts
> Add image prop to customize header

- CHANGELOG.md
> 4.0.0-changelog

- examples/tutorial/step1.js
- examples/tutorial/step2.js
- examples/tutorial/step3.js
- examples/tutorial/step4.js
- examples/tutorial/step5.js
- scripts/send-messages.js
- src/components/Chat/hooks/useChat.js
- src/components/ChatAutoComplete/ChatAutoComplete.js
- src/components/MessageInput/EmojiPicker.js
- src/components/Reactions/ReactionSelector.js
- src/components/Reactions/ReactionsList.js
- src/components/Reactions/SimpleReactionsList.js
- src/docs/Chat.md
- src/docs/EditMessageForm.md
- src/docs/data.js
- src/mock-builders/index.js
> Fix broken docs

- CHANGELOG.md
- src/docs/useFlagHandler.md
- src/docs/useMuteHandler.md
- src/docs/useOpenThreadHandler.md
- src/docs/usePinHandler.md
- src/docs/useReactionHandler.md
- src/docs/useRetryHandler.md
- styleguide.config.js
> adds docs for usePinHandler

- rollup.config.js
> generate minified css output

- src/components/MessageInput/MessageInputFlat.js
- src/components/MessageInput/MessageInputLarge.js
- src/components/MessageInput/MessageInputSimple.js
- src/components/MessageInput/MessageInputSmall.js
> Add tabIndex to emoji picker

- src/components/Channel/Channel.js
- types/index.d.ts
> Add dispatch to channel context

- src/components/Reactions/ReactionsList.js
> Removing unnecessary $ in ReactionList

- src/components/MessageInput/MessageInputFlat.js
- src/components/MessageInput/MessageInputLarge.js
- src/components/MessageInput/MessageInputSimple.js
- src/components/MessageInput/MessageInputSmall.js
- src/components/MessageInput/hooks/messageInput.js
- types/index.d.ts
> a11y support for emoji picker

- .github/workflows/ci.yml
> ignore node version error in CI

- package.json
- yarn.lock
**should be merged after #694 is merged**
> chore: upgrade mml-react

- package.json
- yarn.lock
> bump emojimart

- src/utils.js
> Fixes markdown in backticks 

- src/components/MessageList/MessageList.js
- types/index.d.ts
> Add scrolledUpThreshold MessageList prop

- CHANGELOG.md
> 4.1.0-changelog

- CHANGELOG.md
- examples/commerce/package.json
- examples/commerce/yarn.lock
- examples/livestream/package.json
- examples/livestream/yarn.lock
- examples/messaging/package.json
- examples/messaging/yarn.lock
- examples/team/package.json
- examples/team/yarn.lock
- examples/typescript-app/package.json
- examples/typescript-app/yarn.lock
- package.json
- src/utils.js
- yarn.lock
> Upgrade stream chat and markdown issue

- src/components/ChannelPreview/index.js
> export ChannelPreview helpers

- src/components/ChannelList/hooks/usePaginatedChannels.js
> stringify ChannelList filters

- src/components/MessageInput/MessageInputFlat.js
- src/components/MessageInput/MessageInputLarge.js
- src/components/MessageInput/MessageInputSimple.js
- src/components/MessageInput/MessageInputSmall.js
- src/components/MessageInput/hooks/messageInput.js
- src/i18n/en.json
- src/i18n/fr.json
- src/i18n/hi.json
- src/i18n/it.json
- src/i18n/nl.json
- src/i18n/ru.json
- src/i18n/tr.json
- types/index.d.ts
> allows user to close emoji picker using smiley button

- src/components/Reactions/ReactionSelector.js
> hide tooltip bug

- src/components/Message/MessageLivestream.md
- src/components/Message/MessageLivestream.tsx
- src/components/Message/__tests__/MessageLivestream.test.js
- src/components/Message/index.ts
- src/components/Reactions/ReactionsList.tsx
- src/components/Reactions/SimpleReactionsList.tsx
- src/components/Reactions/__tests__/SimpleReactionsList.test.js
> MessageLivestream TS conversion

- README.md
Updating the readme for customizing styles
> update preferred method for customizing styles

- CHANGELOG.md
- types/index.d.ts
> Add missing exports

- src/components/Message/MessageLivestream.tsx
- src/components/Message/__tests__/MessageLivestream.test.js
- src/components/Message/utils.tsx
> Message livestream memo refactor

- src/components/AutoCompleteTextarea/List.js
- src/components/AutoCompleteTextarea/Textarea.js
Cherry picked two commits off of master to merge into the typscript branch. These changes happened to be to JS files, so no further changes are needed.
> CRS-442 typescript emoji keyboard navigation

- src/components/ChatAutoComplete/ChatAutoComplete.tsx
- src/components/ChatAutoComplete/__tests__/ChatAutocomplete.test.js
- src/components/MessageInput/EditMessageForm.tsx
- src/components/MessageInput/MessageInput.tsx
- src/components/MessageInput/MessageInputFlat.tsx
- src/components/MessageInput/MessageInputLarge.tsx
- src/components/MessageInput/MessageInputSimple.tsx
- src/components/MessageInput/MessageInputSmall.tsx
- src/components/MessageInput/__tests__/MessageInput.test.js
> Add option to mention all app users

- CHANGELOG.md
> v5 changelog

- CHANGELOG.md
- examples/typescript-app/yarn.lock
- package.json
> add built to package json

- examples/typescript-app/src/App.tsx
> remove expect error

- examples/typescript-app/src/App.tsx
- src/components/Message/types.ts
- src/styles/Message.scss
- src/utils.tsx
> Add renderText options

- examples/messaging/yarn.lock
- src/components/ChannelPreview/ChannelPreview.tsx
- src/components/ChannelPreview/ChannelPreviewCompact.tsx
- src/components/ChannelPreview/ChannelPreviewCountOnly.tsx
- src/components/ChannelPreview/ChannelPreviewLastMessage.tsx
- src/components/ChannelPreview/ChannelPreviewMessenger.tsx
- src/components/ChannelPreview/utils.ts
> Enable ChannelPreview i18n Translation

- src/components/Channel/Channel.tsx
- src/components/MessageList/MessageList.tsx
- src/context/ChannelContext.tsx
> Move notification logic to channel context

- CHANGELOG.md
- src/components/Channel/Channel.tsx
- src/components/Channel/__tests__/Channel.test.js
- src/components/ChatAutoComplete/ChatAutoComplete.tsx
> Hopin fixes

- src/components/DateSeparator/DateSeparator.tsx
- src/components/DateSeparator/__tests__/DateSeparator.test.js
> Show date separator for new messages

- src/components/AutoCompleteTextarea/List.js
- src/utils.tsx
Escapes the regex that is created when typing a command (e.g. by typing `:` or `/`) so it doesn't create an invalid regex.
> CRS-474 Fix trigger autocomplete error

- src/components/Chat/Chat.tsx
- src/components/Chat/index.ts
- src/context/ChatContext.tsx
> Update Chat types

- CHANGELOG.md
> 5.1.1 changelog

- src/components/Channel/hooks/useMentionsHandlers.ts
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
> Fix channel mentions hook bug

- CHANGELOG.md
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/MessageListInner.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/utils.ts
- types/types.ts
> Hide new message separator option

- src/components/Channel/Channel.tsx
- src/components/Channel/__tests__/Channel.test.js
> Remove extra loadMore calls

- CHANGELOG.md
> 5.1.3 changelog

- src/components/Message/MessageCommerce.tsx
- src/components/Message/MessageSimple.tsx
- src/components/Message/__tests__/MessageCommerce.test.js
- src/components/Message/utils.tsx
- src/styles/Message.scss
- src/styles/MessageCommerce.scss
> Message memoization adjust

- src/components/Message/Message.tsx
- src/components/Message/__tests__/Message.test.js
> Remove ability for channel owner to edit/delete messages

- src/components/MessageActions/MessageActions.tsx
- src/components/MessageActions/__tests__/MessageActions.test.js
- src/components/Modal/Modal.tsx
- src/components/Modal/__tests__/Modal.test.js
Event listener were being registered with invalid names so the callback was never triggered.
I updated those names to get it to work. The tests were passing because the callbacks were being triggered manually with the invalid event names.
> Fix event listeners

- src/components/Message/Message.tsx
- src/components/Message/types.ts
- src/components/Message/utils.tsx
- src/components/MessageActions/MessageActions.tsx
- src/components/MessageActions/MessageActionsBox.tsx
- src/components/MessageActions/__tests__/MessageActions.test.js
- src/components/MessageList/MessageList.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/__tests__/Modal.test.js
- src/context/MessageContext.tsx
> Custom actions support

- src/components/AutoCompleteTextarea/List.js
Fixed a bug in the List component where selection of items in the component use ids, but command items don't have ids. Updated this to use name instead when id isn't present.
> Suggestion list command fix

- CHANGELOG.md
- src/components/Message/__tests__/Message.test.js
- src/components/Message/hooks/usePinHandler.ts
- src/components/Message/utils.tsx
> Adjust pin permissions

- src/components/ChatAutoComplete/ChatAutoComplete.tsx
- src/components/MessageInput/MessageInput.tsx
- src/components/MessageInput/MessageInputFlat.tsx
- src/components/MessageInput/MessageInputLarge.tsx
- src/components/MessageInput/MessageInputSimple.tsx
- src/components/MessageInput/MessageInputSmall.tsx
- src/components/MessageInput/__tests__/MessageInputLarge.test.js
- src/components/MessageInput/hooks/index.ts
- src/components/MessageInput/hooks/useCooldownTimer.tsx
- src/context/ComponentContext.tsx
- src/context/MessageInputContext.tsx
- src/i18n/en.json
- src/i18n/fr.json
- src/i18n/hi.json
- src/i18n/it.json
- src/i18n/nl.json
- src/i18n/ru.json
- src/i18n/tr.json
- src/styles/MessageInput.scss
- src/styles/MessageInputFlat.scss
after message send...
after cooldown period...
> Slow Mode UX

- src/components/Message/MessageSimple.tsx
- src/components/Message/MessageStatus.tsx
- src/components/Message/MessageTeam.tsx
- src/components/Message/__tests__/MessageTeam.test.js
> MessageStatus component

- src/components/MessageList/MessageListInner.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/hooks/useNewMessageNotification.ts
- src/components/MessageList/hooks/usePrependMessagesCount.ts
- src/components/MessageList/hooks/useShouldForceScrollToBottom.ts
- src/components/MessageList/utils.ts
> Update process messages logic

- examples/typescript-app/src/components/CustomMessage.scss
- examples/typescript-app/src/components/CustomMessage.tsx
> adds MessageStatus to CustomMessage

- src/components/Message/utils.tsx
> Adjust readBy memoization

- CHANGELOG.md
- src/components/Message/utils.tsx
> Memoize message on mutes array

- src/components/MessageList/VirtualizedMessageList.tsx
Chrome throttles timers when the window is deactivated (say, tab away from it). This prop allows the message list to "catchup" on new messages when the focus is restored.
> feat(): scrollToLatestMessageOnFocus vlist prop

- src/components/MessageList/MessageList.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
> Custom message notification

- CHANGELOG.md
> 5.3.2 changelog

- src/components/Message/FixedHeightMessage.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/styles/VirtualMessage.scss
> Adjust virtualized grouping

- src/components/Message/MessageTeam.tsx
- src/styles/MessageTeam.scss
> Add quoted messages to MessageTeam

- src/components/MessageList/MessageList.tsx
> Adjust scroll to bottom logic for reaction/reply on last message

- examples/next-based/next.config.js
- examples/next-based/package.json
- examples/next-based/yarn.lock
> Add next config for images

- src/components/TypingIndicator/TypingIndicator.tsx
> check for user typing in thread

- CHANGELOG.md
> v6 changelog

- CHANGELOG.md
- src/components/MessageList/hooks/useMessageListScrollManager.ts
> Fix empty channel crash

- examples/messaging/yarn.lock
- examples/next-based/yarn.lock
- examples/typescript-app/yarn.lock
- package.json
- src/components/Attachment/__tests__/__snapshots__/File.test.js.snap
- src/components/MessageInput/__tests__/MessageInput.test.js
- src/version.ts
- yarn.lock
> Upgrade file utils dep

- package.json
> Keep css in sideEffects

- CHANGELOG.md
> add v6.0.2 changelog

- rollup.config.js
- src/version.ts
> Export library as namespace

- CHANGELOG.md
- src/components/Channel/Channel.tsx
- src/version.ts
> Add missing Input prop

- CHANGELOG.md
- examples/typescript-app/src/App.tsx
- src/components/ChatAutoComplete/ChatAutoComplete.tsx
- src/components/MessageInput/DefaultTriggerProvider.md
- src/components/MessageInput/DefaultTriggerProvider.tsx
- src/components/MessageInput/hooks/useCommandTrigger.ts
- src/components/MessageInput/hooks/useEmojiTrigger.ts
- src/components/MessageInput/hooks/useMessageInputState.ts
- src/components/MessageInput/hooks/useUserTrigger.ts
- src/context/MessageInputContext.tsx
- src/version.ts
> Prevent members query when mentions disabled

- CHANGELOG.md
- src/components/MessageList/VirtualizedMessageList.tsx
> Add loadMore VML prop

- src/components/ChatAutoComplete/ChatAutoComplete.tsx
- src/version.ts
> Fix chatautocomplete props

- src/components/Message/hooks/useReactionHandler.ts
> Reaction throttle

- CHANGELOG.md
> 6.0.6 changelog

- CHANGELOG.md
- src/components/Message/hooks/useReactionHandler.ts
> Adjust reaction error catch

- docusaurus/docs/React/Customization/theming-and-css.mdx
> css and theming page updated

- docusaurus/docs/React/utility-components/channel-search.mdx
- src/components/ChannelSearch/ChannelSearch.tsx
> add needed params to channel search search function

- CHANGELOG.md
- package.json
- src/components/Message/QuotedMessage.tsx
- yarn.lock
> upgrade stream chat

- docusaurus/docs/React/core-components/message-list.mdx
- docusaurus/docs/React/message-components/message.mdx
- examples/typescript-app/package.json
- examples/typescript-app/yarn.lock
- src/components/Message/FixedHeightMessage.tsx
- src/components/Message/Message.tsx
- src/components/Message/hooks/__tests__/useUserRole.test.js
- src/components/Message/hooks/useUserRole.ts
- src/components/Message/types.ts
- src/components/MessageList/MessageList.tsx
- src/version.ts
> Adjust edit privileges

- src/components/MessageInput/hooks/useSubmitHandler.ts
> changes type from media to video

- src/components/MessageList/MessageList.tsx
> don't show empty state indicator if thread list

- src/components/InfiniteScrollPaginator/InfiniteScroll.tsx
- src/components/InfiniteScrollPaginator/__tests__/InfiniteScroll.test.js
> updates wheel event listener

- CHANGELOG.md
- package.json
- yarn.lock
> Remove docgen

- .github/workflows/docusaurus.yml
- docusaurus/docs/React/core-components/channel.mdx
- src/version.ts
> Adjust docs build flow

- src/components/MessageInput/hooks/useUserTrigger.ts
> Add limit option to user mention

- docusaurus/docs/React/Hooks/message-hooks.mdx
- docusaurus/docs/React/contexts/channel-state-context.mdx
- docusaurus/docs/React/contexts/message-context.mdx
- docusaurus/docs/React/message-components/message-ui.mdx
- src/components/Channel/Channel.tsx
- src/components/Message/Message.tsx
- src/components/Message/MessageLivestream.tsx
- src/components/Message/MessageOptions.tsx
- src/components/Message/MessageTeam.tsx
- src/components/Message/__tests__/FixedHeightMessage.test.js
- src/components/Message/__tests__/Message.test.js
- src/components/Message/__tests__/MessageCommerce.test.js
- src/components/Message/__tests__/MessageDeleted.test.js
- src/components/Message/__tests__/MessageLivestream.test.js
- src/components/Message/__tests__/MessageOptions.test.js
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/__tests__/MessageTeam.test.js
- src/components/Message/__tests__/MessageText.test.js
- src/components/Message/hooks/__tests__/useUserRole.test.js
- src/components/Message/hooks/useUserRole.ts
- src/context/ChannelStateContext.tsx
- src/context/MessageContext.tsx
> Channel permissions updates

- src/components/Attachment/Attachment.tsx
- src/components/Attachment/AttachmentActions.tsx
- src/components/Attachment/utils.tsx
- src/components/Message/MessageSimple.tsx
- src/components/Message/hooks/useActionHandler.ts
- src/components/MessageInput/hooks/useAttachments.ts
- src/types/types.ts
> Clean up attachment and refactor types

- src/components/MessageList/hooks/useMessageListElements.tsx
> Add formatDate prop to DateSeparator

- docusaurus/docs/React/custom-code-examples/system-message.mdx
> fix system message mdx header

- docusaurus/docs/React/custom-code-examples/adding-notification.mdx
- docusaurus/docs/React/custom-code-examples/channel-header.mdx
- docusaurus/docs/React/custom-code-examples/channel-list-preview.mdx
- docusaurus/docs/React/custom-code-examples/channel-search.mdx
- src/version.ts
> minor docs changes

- docusaurus/docs/React/contexts/component-context.mdx
- docusaurus/docs/React/core-components/channel.mdx
- docusaurus/docs/React/core-components/message-list.mdx
- docusaurus/docs/React/customization/translations.mdx
- src/components/Channel/Channel.tsx
- src/components/Message/MessageSimple.tsx
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/hooks/useLastReadData.ts
- src/components/MessageList/hooks/useMessageListElements.tsx
- src/components/MessageList/utils.ts
- src/context/ComponentContext.tsx
> Add option to view read states on all messages

- package.json
- yarn.lock
> Upgrade react-file-utils

- docusaurus/docs/React/hooks/channel-list-hooks.mdx
- docusaurus/docs/React/hooks/message-input-hooks.mdx
> Docs fixes

- docusaurus/docs/React/core-components/channel-list.mdx
- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/ChannelListMessenger.tsx
> Add loadedChannels prop

- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/hooks/useNotificationMessageNewListener.ts
- src/components/ChannelList/hooks/usePaginatedChannels.ts
- src/version.ts
> account for new messages in offset

- examples/next-based/yarn.lock
- package.json
- yarn.lock
> Upgrade file utils for Next

- package.json
> Add repo to npm info

- src/components/index.ts
- src/version.ts
> add missing MML export

- src/components/ChannelList/hooks/usePaginatedChannels.ts
Reference the implement in react-native package
https://github.com/GetStream/stream-chat-react-native/blob/04dbc9bf3e0f334215b6bac3221a8963951e97e2/package/src/components/ChannelList/hooks/usePaginatedChannels.ts#L126-L146
> fix: reload channel list when sort changed

- examples/typescript-app/yarn.lock
- package.json
- yarn.lock
> upgrade virtuoso dep

- src/components/MessageList/MessageList.tsx
> Revert thread empty

- .eslintignore
- .stylelintignore
- CHANGELOG.md
- jest.config.js
- src/components/MML/MML.tsx
- src/styles/index.scss
- src/styles/vendor/emoji-mart.scss
- src/styles/vendor/react-file-utils.scss
> refactor mml css

- examples/next-based/yarn.lock
- src/components/MML/MML.tsx
- src/styles/index.scss
> update css import for next apps

- docusaurus/docs/React/message-components/ui-components.mdx
- src/components/Message/MessageSimple.tsx
- src/components/Message/MessageText.tsx
- src/version.ts
> pass message to MessageText

- docusaurus/docs/React/core-components/virtualized-list.mdx
- docusaurus/docs/React/message-components/message-ui.mdx
- examples/typescript-app/src/App.tsx
- src/components/Message/FixedHeightMessage.tsx
- src/components/Message/types.ts
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/hooks/useEnrichedMessages.ts
- src/components/MessageList/utils.ts
- src/components/Thread/Thread.tsx
> Add option to use VirtualizedMessageList in Thread

- CHANGELOG.md
- src/components/ChannelPreview/ChannelPreviewMessenger.tsx
- src/components/Message/QuotedMessage.tsx
- src/components/MessageInput/QuotedMessagePreview.tsx
> Add fallback name avatar

- CHANGELOG.md
- examples/typescript-app/yarn.lock
- package.json
- yarn.lock
> upgrade react-images dep

- docusaurus/docs/React/contexts/message-input-context.mdx
- src/components/AutoCompleteTextarea/Textarea.js
- src/components/ChatAutoComplete/ChatAutoComplete.tsx
- src/components/MessageInput/MessageInputFlat.tsx
- src/components/MessageInput/hooks/useMessageInputState.ts
- src/context/MessageInputContext.tsx
> Add ability to open/close commands list

- CHANGELOG.md
- src/utils.tsx
- src/version.ts
Update the replaceAll method to replace in the renderText utility function.
> update replace all method with replace

- src/styles/_base.scss
> add min width to main panel

- src/components/AutoCompleteTextarea/Textarea.js
> clean up new textarea props

- CHANGELOG.md
- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/ChannelList/hooks/useMessageNewListener.ts
- src/components/ChannelList/utils.ts
> Custom active channel fix

- docusaurus/docs/React/utility-components/channel-search.mdx
- src/components/ChannelSearch/ChannelSearch.tsx
- src/components/ChannelSearch/SearchInput.tsx
- src/components/ChannelSearch/__tests__/ChannelSearch.test.js
- src/styles/ChannelPreview.scss
- src/version.ts
> add SearchInput prop for ChannelSearch

- src/components/ChannelSearch/ChannelSearch.tsx
> add missing generic

- src/components/ChannelSearch/index.ts
> adding missing exports

- docusaurus/docs/React/customization/translations.mdx
- src/components/Chat/hooks/useChat.ts
- src/components/MessageInput/hooks/useSubmitHandler.ts
- src/context/TranslationContext.tsx
- src/i18n/Streami18n.ts
> Detect user's default language for translation

- CHANGELOG.md
- docusaurus/docs/React/contexts/message-context.mdx
- docusaurus/docs/React/message-components/message.mdx
- src/components/Message/FixedHeightMessage.tsx
- src/components/Message/Message.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/context/MessageContext.tsx
> Update VML message grouping logic

- docusaurus/docs/React/customization/translations.mdx
- src/version.ts
> update translations docs

- src/components/MessageInput/hooks/useSubmitHandler.ts
- src/i18n/ja.json
> clear input text prior to message send

- CHANGELOG.md
- src/components/Avatar/Avatar.tsx
- src/components/ChannelPreview/ChannelPreview.tsx
- src/components/ChannelPreview/ChannelPreviewMessenger.tsx
- src/i18n/ko.json
> prevent Avatar from trying to render a number for name

- examples/next-based/pages/App.css
> fix next app css issues

- docusaurus/docs/React/custom-code-examples/emoji-picker.mdx
- docusaurus/docs/React/customization/css-and-theming.mdx
- src/context/EmojiContext.tsx
- src/version.ts
> Css docs update

- CHANGELOG.md
- src/components/Message/MessageCommerce.tsx
- src/components/Message/MessageLivestream.tsx
- src/components/Message/MessageSimple.tsx
- src/components/Message/MessageTeam.tsx
> ternary render Attachment component in Message UI components

- examples/typescript-app/yarn.lock
- src/components/MessageInput/hooks/useCooldownTimer.tsx
- src/components/Thread/__tests__/Thread.test.js
- src/version.ts
> skip cooldown for admin and moderators

- docusaurus/docs/React/customization/translations.mdx
Adding link to docs covering automatic translation of user messages.
- [ x ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ x ] The code changes follow best practices  (NA - Docs Change) 
- [ x ] Code changes are tested (add some information if not applicable) (NA - Docs Change) 
Merging docs updates.
> Add link to docs for automatic translation

- src/components/Message/MessageSimple.tsx
- src/components/Message/MessageText.tsx
- src/components/Message/QuotedMessage.tsx
> add support for replys to be attachments on quoted messages

- examples/website-demos/virtual-event/src/components/Chat/MessageUI.tsx
- examples/website-demos/virtual-event/src/components/Chat/ThreadInner.tsx
- examples/website-demos/virtual-event/src/styles/MessageInputUI.scss
- examples/website-demos/virtual-event/src/styles/ThreadUI.scss
> Thread css

- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelSearch/ChannelSearch.tsx
- src/components/MessageInput/DefaultTriggerProvider.tsx
- src/components/MessageInput/MessageInput.tsx
- src/components/MessageInput/hooks/useUserTrigger.ts
- src/version.ts
> separate channel and user filters in channel search

- src/components/MessageInput/MessageInput.tsx
> Remove unnecessary message input state hook props

- docusaurus/docs/React/core-components/message-list.mdx
- docusaurus/docs/React/core-components/virtualized-list.mdx
- docusaurus/docs/React/message-components/message.mdx
- src/components/Message/Message.tsx
- src/components/Message/hooks/useReactionHandler.ts
- src/components/Message/types.ts
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
> add option to close the ReactionSelector component on reaction pick

- examples/typescript-app/yarn.lock
- package.json
- src/components/Message/MessageOptions.tsx
- src/components/Message/MessageStatus.tsx
- src/components/MessageActions/MessageActions.tsx
- src/version.ts
- yarn.lock
> fix empty message actions bug

- CHANGELOG.md
- docusaurus/docs/React/contexts/message-context.mdx
- docusaurus/docs/React/message-components/message.mdx
- src/components/Message/Message.tsx
- src/components/Message/MessageSimple.tsx
- src/components/Message/types.ts
- src/components/Message/utils.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/context/MessageContext.tsx
- src/styles/Message.scss
- src/styles/VirtualMessage.scss
> Vml message additions

- CHANGELOG.md
- src/components/MessageInput/hooks/useSubmitHandler.ts
- src/version.ts
> fix edit bug with custom message data

- examples/typescript/yarn.lock
- src/components/MessageInput/hooks/useMessageInputText.ts
> re-add deleted typing default value

- src/components/Avatar/Avatar.tsx
- src/utils.tsx
Allow the Avatar fallback logic to display an emoji if one is the first character in a user's name
Add a regex check that tests to see if the first two characters comprise a unicode emoji
None
> support emoji as first character in avatar name

- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/hooks/useNotificationMessageNewListener.ts
- src/components/ChannelList/hooks/usePaginatedChannels.ts
Maintain correct pagination offset when channels added/removed from list
Always paginate the offset based on the current number of loaded channels
None
> update channel list pagination offset logic

- docusaurus/docs/React/basics/_category_.json
- docusaurus/docs/React/core-components/_category_.json
- docusaurus/docs/React/core-components/channel.mdx
- examples/capacitor/android/app/src/main/assets/capacitor.config.json
- examples/capacitor/capacitor.config.ts
- examples/capacitor/ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
- examples/capacitor/ios/App/App/Assets.xcassets/Contents.json
- examples/capacitor/ios/App/App/Assets.xcassets/Splash.imageset/Contents.json
- examples/capacitor/ios/App/App/capacitor.config.json
- examples/capacitor/src/components/ChannelInner.tsx
- examples/typescript/src/App.tsx
- examples/typescript/src/components/ChannelInner.tsx
- examples/website-demos/social-messaging/src/index.tsx
- examples/website-demos/social-messaging/tsconfig.json
- examples/website-demos/virtual-event/src/index.tsx
- examples/website-demos/virtual-event/tsconfig.json
- src/components/Channel/Channel.tsx
- src/components/Channel/hooks/useCreateChannelStateContext.ts
> memoization cleanup

- CHANGELOG.md
> 6.9.0 changelog

- examples/nextjs/yarn.lock
- examples/typescript/yarn.lock
- package.json
- yarn.lock
> upgrade virtuoso, mml, css

- docusaurus/docs/React/core-components/channel-list.mdx
- docusaurus/docs/React/custom-code-examples/channel-list-preview.mdx
> Channellist doc update

- src/components/AutoCompleteTextarea/List.js
- src/components/ChatAutoComplete/ChatAutoComplete.tsx
> Add Value Prop To Suggestion Item

- docusaurus/docs/React/customization/css-and-theming.mdx
- examples/nextjs/yarn.lock
- examples/typescript/yarn.lock
- package.json
- src/components/Channel/Channel.tsx
- src/context/ChatContext.tsx
- yarn.lock
Ability to override className wrapping Channel children
Add new custom css class override
None
> add chatContainer custom class override

- CHANGELOG.md
- package.json
- yarn.lock
> reduce css bundle

- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/ChannelListMessenger.tsx
Allow clients to manually set the local channel list state
Pass `setChannels` state hook as a prop to the ChannelList's List UI component
> pass setChannels state hook to List UI component

- src/components/Message/QuotedMessage.tsx
- src/components/TypingIndicator/TypingIndicator.tsx
- src/context/ComponentContext.tsx
Keep avatars consistent across all components
If available, use the avatar in the ComponentContext in the QuotedMessage and TypingIndicator components
> use context avatar in quoted message and typing indicator

- src/components/ChannelList/hooks/usePaginatedChannels.ts
reset error to false to prevent erroneous error messages 
setState back to false at top of usePaginatedChannels hook
> fix: reset state to false

- .github/workflows/release.yml
- package.json
- src/version.ts
- yarn.lock
> feat: automated release

- docusaurus/docs/React/core-components/message-list.mdx
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/__tests__/MessageList.test.js
- src/components/MessageList/hooks/useEnrichedMessages.ts
- src/components/MessageList/hooks/useMessageListElements.tsx
- src/components/MessageList/index.ts
Adding a way to change the group styles makes it easier to customize its experience (like grouping only messages within a timeframe, etc).
> Adding custom group styles function

- src/i18n/Streami18n.ts
I agreed with [CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform).
close #1290 
Some Japanese translations sounds unnatural. So update them.
Update translation only.
No change.
> Update Japanese translation

- README.md
- docusaurus/docs/React/basics/getting-started.mdx
- docusaurus/docs/React/custom-code-examples/channel-list-preview.mdx
- docusaurus/docs/React/customization/css-and-theming.mdx
- examples/capacitor/package.json
- examples/capacitor/src/App.tsx
- examples/capacitor/yarn.lock
- examples/nextjs/pages/_app.js
- examples/nextjs/yarn.lock
- examples/typescript/package.json
- examples/typescript/src/App.tsx
- examples/typescript/yarn.lock
- examples/vite/src/App.tsx
- examples/vite/yarn.lock
- examples/website-demos/social-messaging/yarn.lock
- examples/website-demos/virtual-event/src/components/Chat/ChatContainer.tsx
- examples/website-demos/virtual-event/yarn.lock
- package.json
- rollup.config.js
- yarn.lock
update stream-chat-css link to scoped package
> fix(): link scoped package

- package.json
- yarn.lock
> fix(): improve virtualized message list stability

- docusaurus/docs/React/hooks/message-input-hooks.mdx
Help keep our documentation error-free.
Fix a quick typo in the hooks section of documentation.
> chore: hook docs typo fix

- docusaurus/docs/React/basics/getting-started.mdx
- docusaurus/docs/React/core-components/channel.mdx
- docusaurus/docs/React/hooks/message-input-hooks.mdx
- examples/nextjs/next.config.js
- examples/nextjs/package.json
- examples/nextjs/yarn.lock
- examples/typescript/yarn.lock
- package.json
- rollup.config.js
- src/components/Attachment/Card.tsx
- src/components/MessageInput/MessageInput.tsx
- src/components/MessageInput/hooks/utils.ts
- yarn.lock
The PR updates to our scoped packages that work with NextJS node compilation. I can no longer reproduce an emoji-related error I had, which is suspicious. 
@ambaldwin can you test on your side?
> Next import updates

- src/components/MessageInput/QuotedMessagePreview.tsx
To keep avatars consistent across all components.
Use the avatar in the ComponentContext in the QuotedMessagePreview component if available.
> chore: add component context avatar to quoted message preview

- src/components/AutoCompleteTextarea/List.js
- src/components/AutoCompleteTextarea/Textarea.js
The regexp calculated value was not used anywhere. 
Please test if mentions, emojis, and slash commands work as expected.
> Remove UNSAFE warning from textarea

- docusaurus/docs/React/custom-code-examples/channel-users-list.mdx
Guide on how to build a custom list with channel members and have real time updates of their online status.
> docs: Guide on users list and online presence

- examples/typescript/package.json
- examples/typescript/yarn.lock
- package.json
- src/components/Channel/Channel.tsx
- src/components/MessageActions/MessageActionsBox.tsx
- src/components/MessageInput/MessageInputFlat.tsx
- src/components/MessageInput/MessageInputSmall.tsx
- yarn.lock
Stream-chat-css changes: https://github.com/GetStream/stream-chat-css/pull/37
> feat: Quote reply to thread messages

- examples/typescript/yarn.lock
- examples/vite/package.json
- examples/vite/vite.config.ts
- examples/vite/yarn.lock
- package.json
- src/components/AutoCompleteTextarea/Textarea.js
- yarn.lock
Removing the custom event polyfill means one less dependency. It also simplifies Vite setup. 
Fixes #1375
> [CRS-804] Remove custom-event polyfill

- docusaurus/docs/React/custom-code-examples/channel-search.mdx
- docusaurus/docs/React/customization/message-ui.mdx
- examples/typescript/package.json
- examples/typescript/yarn.lock
Add the missing CSS that is referenced in the Custom Message UI example. Add information for the `searchFunction` prop for the `ChannelSearch` customization example as this comes up in support often.
Also, bumped the typescript example app's stream-chat-css version to latest.
> chore: update to channel search and message ui component docs

- examples/capacitor/package.json
- examples/capacitor/yarn.lock
- examples/nextjs/package.json
- examples/nextjs/yarn.lock
- examples/typescript/package.json
- examples/typescript/yarn.lock
- examples/vite/package.json
- examples/vite/yarn.lock
- examples/website-demos/social-messaging/package.json
- examples/website-demos/social-messaging/src/components/ChannelPreview/SocialPreviewActions.tsx
- examples/website-demos/social-messaging/src/components/ChannelPreview/utils.tsx
- examples/website-demos/social-messaging/src/components/ChatContainer/ChatContainer.tsx
- examples/website-demos/social-messaging/src/components/NewChat/NewChatUser.tsx
- examples/website-demos/social-messaging/yarn.lock
- examples/website-demos/virtual-event/package.json
- examples/website-demos/virtual-event/yarn.lock
- package.json
- yarn.lock
This PR solves the TS issue with version 6.0.0 of `stream-chat`. The issue was caused due to the unavailability of types of (_queryFlags function) of this PR here - https://github.com/GetStream/stream-chat-js/issues/913.
- The TS issue due to circular Typescript Generics is solved.
- Issue with 6.0.0 is solved by upgrading the version of `stream-chat` to 6.10.
> fix: typescript issues due to stream-chat@6.0.0

- examples/capacitor/package.json
- examples/capacitor/src/App.tsx
- examples/capacitor/yarn.lock
- examples/nextjs/package.json
- examples/nextjs/pages/index.js
- examples/nextjs/yarn.lock
- examples/typescript/package.json
- examples/typescript/src/App.tsx
- examples/typescript/yarn.lock
- examples/vite/package.json
- examples/vite/src/App.tsx
- examples/vite/yarn.lock
- fix: Add missing required filter key `members` into channel filters for each example app
- chore: Update example apps dependencies (mainly upgrade `stream-chat` package version)
> chore/fix: Example apps - update dependencies and fix missing members in channel filters

- examples/website-demos/social-messaging/package.json
- examples/website-demos/social-messaging/yarn.lock
- examples/website-demos/virtual-event/package.json
- examples/website-demos/virtual-event/yarn.lock
Make consistent reuse of dependencies across example apps.
> chore: use stream-chat dependency used by the stream-chat-react SDK in website demos

- .releaserc.json
- CHANGELOG.md
Add `assets` keyword with CHANGELOG.md path to be updated when a new release is created and update change log (add `8.1.0` release notes).
> chore: update .releaserc.json and change log

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- commitlint.config.js
- developers/BRANCHES.md
- developers/COMMIT.md
- developers/DEVELOPMENT.md
- developers/E2E.md
- developers/PR.md
- developers/RELEASE.md
- dotgit/hooks/pre-commit-reject-binaries.py
- package.json
- yarn.lock
Provide an onboarding guide for developers that would like to start contributing to the `stream-chat-react` repository.
As the repository developers come and go, the domain knowledge tends to disappear. This documentation should provide single source of truth on how to maintain a certain level of the repository's quality standard. It should represent a shared contract removing any doubts about how the things should be done correctly.
The main file is `CONTRIBUTING.md`. It then refers to more narrow-scoped files in `developers` directory.
fixes #1416
> docs: add contributor documentation

- .github/workflows/release.yml
- .releaserc.json
- CHANGELOG.md
- package.json
- yarn.lock
Make sure that CHANGELOG.md gets properly updated after the release.
> ci: update `CHANGELOG.md` upon release  

- .github/workflows/ci.yml
- .github/workflows/docusaurus.yml
- .github/workflows/size.yml
Update used actions to the latest stable versions, improve run times.
- ignore post-install scripts when running `tsc` (`yarn types`), prevent file generation with `noEmit`
> ci: update action versions, improve run times

- playwright.config.ts
- src/stories/utils.tsx
Get rid of excessive `setState` action in `ConnectedUser` component and adjust Playwright configuration.
> test: fix randomly failing E2E tests

- .github/workflows/release.yml
- .releaserc.json
Extend release configuration with beta version stuff.
> ci: extend release configuration (add beta stuff)

- .github/workflows/release.yml
- .releaserc.json
- playwright.config.ts
- src/stories/utils.tsx
Reflect beta release workflow changes so that pushing into newly created `beta` branch will trigger release workflow.
> ci: introduce beta release workflow

- .github/workflows/docusaurus.yml
- docusaurus/docs/React/contexts/_category_.json
- docusaurus/docs/React/custom-code-examples/_category_.json
- docusaurus/docs/React/hooks/_category_.json
- docusaurus/docs/React/resources/_category_.json
- docusaurus/docs/React/troubleshooting/_category_.json
- docusaurus/docs/React/utility-components/_category_.json
- package.json
- scripts/merge-stream-chat-css-docs.sh
- yarn.lock
Merge contents of the `stream-chat-css/docs/` contents into `stream-chat-react/docusaurus/docs/React` folder 
1. while running CI (`.github/workflows/docusaurus.yml`)
2. for local development (`package.json` script `docs-merge`)
fixes #1577
> ci: merge stream-chat-css docs into React docs

- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelPreview/ChannelPreviewMessenger.tsx
- src/components/ChannelPreview/__tests__/__snapshots__/ChannelPreviewMessenger.test.js.snap
- src/components/ChatDown/__tests__/__snapshots__/ChatDown.test.js.snap
- src/components/EmptyStateIndicator/EmptyStateIndicator.tsx
- src/components/EmptyStateIndicator/__tests__/EmptyStateIndicator.test.js
- src/components/EmptyStateIndicator/icons.tsx
- src/components/LoadMore/LoadMoreButton.tsx
- src/components/LoadMore/__tests__/LoadMoreButton.test.js
- src/components/Loading/LoadingChannels.tsx
- src/components/Loading/__tests__/__snapshots__/LoadingChannels.test.js.snap
Apply v2 styling matching https://github.com/GetStream/stream-chat-angular/pull/292
fixes #1579 
depends on https://github.com/GetStream/stream-chat-css/pull/102
**Acceptance Criteria**
| Scenario | Light theme  | Dark theme |  Remark |
|------------- | ------------- |------------- |------------- |
|loading channel list|![image](https://user-images.githubusercontent.com/32706194/169893477-ad677315-bb80-4494-9300-828d689c27e9.png)|![image](https://user-images.githubusercontent.com/32706194/169893584-e4d59f3a-938c-4f23-8f46-eccf40110075.png)||
| empty channel list|![image](https://user-images.githubusercontent.com/32706194/169891562-a25a449f-04b3-42ba-9272-5d728690cb45.png)|![image](https://user-images.githubusercontent.com/32706194/169891434-2b7dcf8c-d71f-4a2f-b61e-ff65c8711513.png)|| …
> feat: Apply theme-v2 to channel list and preview 

- src/components/Channel/__tests__/Channel.test.js
- src/components/MessageInput/__tests__/MessageInput.test.js
- src/mock-builders/generator/channel.js
Fix randomly failing unit tests mainly focusing on `MessageInput.test.js` and `Channel.test.js`.
- add mock implementation of `React.Suspense` to mock lazy loading
- add `channel.getConfig` mock
> test: fix randomly failing unit tests

- src/components/MessageInput/EditMessageForm.tsx
Introduced changes implemented by PR https://github.com/GetStream/stream-chat-angular/pull/312 into stream-chat-angular.
The PR contains only small change, because the rest of the changes in the above mentioned PR are about:
1. Message input hight being adjusted dynamically (will be solved by PR for message input V2)
2. Emoji picker (part of the message input changes)
3. Image gallery carousel (implemented in #1665 & #1667)
This PR is created in order to maintain PR parity btw the angular and react repo.
Closes #1586
> Theming v2 modal react (missing parts)

- commitlint.config.js
- developers/COMMIT.md
- developers/DEPRECATIONS.md
We want to have a clear guideline about how SDK deprecations shall be handled.
> chore: add guideline how deprecations shall be handled

- package.json
- src/components/AutoCompleteTextarea/Item.jsx
- src/components/AutoCompleteTextarea/List.jsx
- src/components/AutoCompleteTextarea/Textarea.jsx
- src/components/ChatAutoComplete/ChatAutoComplete.tsx
- src/components/Message/MessageSimple.tsx
- src/components/MessageInput/EditMessageForm.tsx
- src/components/MessageInput/EmojiPicker.tsx
- src/components/MessageInput/MessageInputFlat.tsx
- src/components/MessageInput/MessageInputSmall.tsx
- src/components/MessageInput/QuotedMessagePreview.tsx
- src/components/MessageInput/UploadsPreview.tsx
- src/components/MessageInput/hooks/useCooldownTimer.tsx
- src/components/MessageInput/hooks/useImageUploads.ts
- src/components/MessageInput/hooks/useMessageInputState.ts
- src/components/MessageInput/icons.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/icons.tsx
- src/components/Thread/Thread.tsx
- src/components/TypingIndicator/TypingIndicator.tsx
- src/components/UserItem/UserItem.tsx
- yarn.lock
_To test locally first `cherry-pick` commits [70cbfcb](https://github.com/GetStream/stream-chat-react/pull/1665/commits/70cbfcbce643b230d8f7c66f615b4cc9bde9b816), [3421087](https://github.com/GetStream/stream-chat-react/pull/1665/commits/34210879aaede5ecf63dc4c85da47440372af058) and [695f30a](https://github.com/GetStream/stream-chat-react/pull/1665/commits/695f30a0f6137c4c84f07ef8528e97f6666a40db) to this branch to enable usage of `themeVersion`._
> ThemingV2: MessageInput component

- src/components/ChatAutoComplete/ChatAutoComplete.tsx
This PR partially fixes the mismatches reported in #1659. 
The proper way to go for it would be to convert the js/jsx files to typescript, but that's quite the effort. We can tackle that in a separate effort.
> fix: update types for suggestions

- package.json
- yarn.lock
Bump to a version that does not yet contain unsupported features.
> chore(deps): bump @stream-io/stream-chat-css to v3.1.1

- docusaurus/docs/React/contexts/channel-action-context.mdx
- docusaurus/docs/React/contexts/channel-state-context.mdx
- docusaurus/docs/React/contexts/message-context.mdx
- docusaurus/docs/React/contexts/message-input-context.mdx
- docusaurus/docs/React/custom-code-examples/override-submit-handler.mdx
- docusaurus/docs/React/utility-components/channel-preview-ui.mdx
- docusaurus/docs/React/utility-components/channel-preview.mdx
- docusaurus/docs/React/utility-components/indicators.mdx
- src/components/ChannelPreview/ChannelPreview.tsx
- src/components/LoadMore/LoadMorePaginator.tsx
- src/components/TypingIndicator/TypingIndicator.tsx
Bring the documentation into the up-to-date state.
> docs: fix outdated documentation

- e2e/attachment-sizing.test.ts
- examples/typescript/package.json
- examples/typescript/src/App.tsx
- examples/typescript/yarn.lock
- package.json
- src/components/Attachment/AttachmentContainer.tsx
- src/components/Attachment/__tests__/__snapshots__/Attachment.test.js.snap
- src/components/Attachment/attachment-sizing.tsx
- src/components/Gallery/Gallery.tsx
- src/components/Gallery/Image.tsx
- src/components/Message/__tests__/FixedHeightMessage.test.js
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/__tests__/MessageText.test.js
- src/components/Message/__tests__/utils.test.js
- src/components/MessageList/VirtualizedMessageList.tsx
- src/mock-builders/generator/attachment.js
- src/types/types.ts
- yarn.lock
> fix: add image attachment height from CSS

- src/components/Reactions/SimpleReactionsList.tsx
- src/components/Reactions/__tests__/SimpleReactionsList.test.js
Display the `SimpleReactionList` in `PopperTooltip` to avoid reaction and tooltip blinking on hover.
Fix text content overflow in `PopperTooltip` by applying css fix (https://github.com/GetStream/stream-chat-css/pull/205).
Fix styling of `SimpleReactionList` tooltip for theme v1.
fixes #1750 
`SimpleReactionList` tooltip for theme v1 was collapsed due to the addition of `str-chat__tooltip` class with the release v10.0.0 (theming v2). This fix reverts that and avoids applying styles associated with that class.
**PopperTooltip overflow**
***PopperTooltip overflow fix**
**Tooltip collapsed (theme v1)**
**Tooltip fixed (theme v1)**
> feat: add popper tooltip to SimpleReactionList items

- docusaurus/docs/React/contexts/_category_.json
- docusaurus/docs/React/core-components/_category_.json
- docusaurus/docs/React/custom-code-examples/_category_.json
- docusaurus/docs/React/customization/_category_.json
- docusaurus/docs/React/hooks/_category_.json
- docusaurus/docs/React/message-components/_category_.json
- docusaurus/docs/React/message-input-components/_category_.json
- docusaurus/docs/React/resources/_category_.json
- docusaurus/docs/React/theming/_category_.json
- docusaurus/docs/React/troubleshooting/_category_.json
- docusaurus/docs/React/utility-components/_category_.json
> docs: make room for theming guide at position 2.

- src/__tests__/__snapshots__/utils.test.js.snap
- src/__tests__/utils.test.js
- src/utils.tsx
Provide a fix which handles a special case where message contains at least one valid mention and @ symbol at the end of the message which causes unrecoverable crash.
Fixes: #1872
> fix(renderText): special case @ symbol at the end of the message

- src/components/MessageInput/hooks/useCooldownTimer.tsx
Refreshing a page would reset local cooldown timer after posting a message on a cooldown enabled channel.
~After discussing this issue with @MartinCupela I opted for fetching the latest message as in `livestream` type channels a large influx of messages would push our latest message beyond limit of locally loaded messages thus preventing us from deriving remaining cooldown.~
Latest message is derived from sorted `messages` (from `ChannelStateContext`) for the current user.
Fetching solution (for future purposes/reference):
```ts
// in livestream type of channels where there's a large influx
// of new messages - refreshing a page on a cooldown enabled
// channel after posting a message would load limited amount of
// new messages (not including ours, since it wouldn't fit within the limit) …
```
> fix(useCooldownTimer): fetch and derive cooldown from last message

- examples/nextjs/.nvmrc
- examples/nextjs/package.json
- examples/nextjs/yarn.lock
- src/components/Chat/Chat.tsx
Unchecked window.getComputedStyle access caused errors in NextJS (our own example included). 
Fixes #1884
> fix: check for window with getComputedStyle

- src/components/MessageList/ConnectionStatus.tsx
- src/components/MessageList/CustomNotification.tsx
- src/components/MessageList/__tests__/CustomNotification.test.js
> feat: add custom class to ConnectionStatus component

- src/components/MessageList/hooks/useMessageListElements.tsx
> fix(MessageSystem): duplicate element keys

- package.json
- yarn.lock
> chore: bump @stream-io/stream-chat-css from version 3.7.2 to version 3.9.1

- src/components/MessageInput/hooks/useCreateMessageInputContext.ts
> fix: add `handleSubmit` to the dependency array

- src/__tests__/__snapshots__/utils.test.js.snap
- src/__tests__/utils.test.js
- src/utils.tsx
> fix(renderText): handle forward slash in mentions

- docusaurus/docs/React/basics/getting-started.mdx
The code snippet of the "Getting started" section of our docs was badly formatted. This PR fixes that.
> chore: formatted code in getting-started.mdx

- src/components/MessageList/VirtualizedMessageList.tsx
Prevent Message component remount. This is the most visible with the video player, when the thumbnail is reloaded with every new message. The root cause of the issue was that the `Item` component for `Virtuoso` was recreated due to new `messages` object passed as the VML prop.
Group style classes are now passed via Virtuoso context prop to virtuoso Item component. This prevents recreation of Item component with each new message and remount of Message component.
> fix: prevent remounting Message components in VirtualizedMessageList

- src/components/Loading/LoadingIndicator.tsx
- src/components/Loading/__tests__/__snapshots__/LoadingIndicator.test.js.snap
> fix: remove color code from LoadingIndicator root class

- src/components/MML/__tests__/MML.test.js
Try to fix the pesky MML unit test.
> test: fix MML test

- README.md
- docusaurus/docs/React/basics/getting-started.mdx
- docusaurus/docs/React/guides/customization/channel-list-preview.mdx
- docusaurus/docs/React/guides/theming/css-and-theming.mdx
- package.json
Move `@stream-io/stream-chat-css` to `devDependencies` as there's no need for it to live in the `dependencies`.
> chore(deps): move `@stream-io/stream-chat-css` to `devDeps`

- .github/workflows/release.yml
- docusaurus/docs/React/release-guides/upgrade-to-v11.mdx
Add missing part about `useImageFlagEmojisOnWindows`.
> docs: adjust v11 release guide

- src/components/Gallery/ModalGallery.tsx
- src/components/Gallery/__tests__/ModalGallery.test.js
fix: #2210
depends on: https://github.com/GetStream/stream-chat-css/pull/255
> fix: show image fallbacks in image gallery modal

- package.json
- yarn.lock
Fixes #2218 
Provides better compatibility with yarn modern's pnp linker (maybe also pnpm?) by explicitly providing required dependencies.
N/A
N/A
> chore(deps): add @babel/runtime to dependencies

- docusaurus/docs/React/components/contexts/component-context.mdx
- src/components/Channel/Channel.tsx
- src/components/Channel/__tests__/Channel.test.js
- src/components/MessageActions/CustomMessageActionsList.tsx
- src/components/MessageActions/MessageActionsBox.tsx
- src/components/MessageActions/__tests__/CustomMessageActionsList.test.js
- src/components/MessageActions/__tests__/MessageActionsBox.test.js
- src/components/MessageActions/index.ts
- src/context/ComponentContext.tsx
Adds CustomMessageActionsList to ComponentContext for easier message actions adjustment.
> feat: add CustomMessageActionsList to ComponentContext

- docusaurus/docs/React/guides/theming/css-and-theming.mdx
Updates a few dead links in the legacy theming guide.
> chore(docs): update theming-v1 links

- package.json
- yarn.lock
🚂 #2263 
🚂 https://github.com/GetStream/stream-chat-css/pull/267
Bumping deps to adopt the fix for avatar alignment.
> fix: avatar alignment

- docusaurus/docs/React/components/message-components/ui-components.mdx
- docusaurus/docs/React/guides/theming/message-ui.mdx
> fix: link-breaking typos

- package.json
- yarn.lock
🚂 https://github.com/GetStream/stream-chat-css/pull/276
> chore: bump css

- docusaurus/docs/React/components/message-components/reactions.mdx
- docusaurus/docs/React/components/message-input-components/emoji-picker.mdx
- docusaurus/docs/React/guides/customization/emoji-picker.mdx
- docusaurus/sidebars-react.json
- src/components/Emojis/EmojiPicker.tsx
Adds missing EmojiPicker documentation and adjust existing Reactions documentation (fixes formatting).
> docs: add EmojiPicker component documentation

- docusaurus/docs/React/guides/sdk-state-management.mdx
- docusaurus/sidebars-react.json
Documentation which describes how is the state within the SDK managed and how to acess it.
> docs: SDK State Management

- .github/workflows/release.yml
- .releaserc.json
- developers/RELEASE.md
Make the master branch the pre-release branch and the branch-vX the latest branch.
> chore: make the latest release from release-vX branch

- src/components/MessageList/renderMessages.tsx
> fix: make it possible to jump to system messages in MessageList

- src/components/Message/__tests__/utils.test.js
- src/components/Message/utils.tsx
fix #2168
depends on https://github.com/GetStream/stream-chat-js/pull/1310
> fix: update quoting message on update of quoted message

- docusaurus/docs/React/release-guides/upgrade-to-v12.mdx
Follow-up to https://github.com/GetStream/stream-chat-react/pull/2443#discussion_r1664462282.
> docs: add browser compat table

- docusaurus/docs/React/guides/sdk-state-management.mdx
- docusaurus/react_versioned_docs/version-11.x.x/guides/sdk-state-management.mdx
Fixing an argument order typo reported by a customer.
> docs: fix a typo

- src/components/Channel/__tests__/Channel.test.js
Follow-up for [#1370](https://github.com/GetStream/stream-chat-js/pull/1370/files).
> chore(tests): adjust problematic tests with proper created_at

- docusaurus/docs/React/release-guides/upgrade-to-v12.mdx
Fixes a broken link in v12 upgrade guide.
> docs: fix ChatView link

- src/components/MessageList/hooks/VirtualizedMessageList/useScrollToBottomOnNewMessage.ts
Refactor `useScrollToBottomOnNewMessage` hook using `useRef`.
> refactor: useScrollToBottomOnNewMessage hook

- src/components/MessageList/MessageList.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
Due to the same dialog manager id, the dialogs in thread message list were not displayed.
> fix: show dialogs in thread message list

- examples/typescript/src/App.tsx
- examples/vite/src/App.tsx
- package.json
- src/types/types.ts
- yarn.lock
Support custom member properties in Typescript
Depends on: https://github.com/GetStream/stream-chat-js/pull/1389
> feat: support custom member data in StreamChatGenerics

- src/components/MessageList/VirtualizedMessageList.tsx
- src/context/VirtualizedMessageListContext.tsx
Achieve parity with normal MessageList + customer request.
Fixes React-250
https://github.com/GetStream/docs-content/pull/148
> feat: add VirtualizedMessageListContext

- src/components/Dialog/FormDialog.tsx
Fixes REACT-392
Depends on https://github.com/GetStream/stream-chat-css/pull/332
> fix: prevent page reload on FormDialog submission with Enter key

- src/components/TextareaComposer/TextareaComposer.tsx
> fix: prevent adding newline in message text composer upon submitting with Enter key

- src/components/ReactFileUtilities/UploadButton.tsx
> fix: focus textarea upon file input change event

- package.json
- src/components/MessageInput/MessageInput.tsx
- src/components/MessageInput/__tests__/EditMessageForm.test.js
- src/components/MessageInput/__tests__/ThreadMessageInput.test.js
- src/mock-builders/generator/channel.ts
- src/mock-builders/generator/reminder.ts
- yarn.lock
> fix: prevent querying thread draft when drafts are disabled

- src/components/Message/index.ts
> fix: export MessageIsThreadReplyInChannelButtonIndicator

- src/components/TextareaComposer/TextareaComposer.tsx
> fix(TextareaComposer): check sendable data before allowing message submission
