GetStream/stream-chat-react

- src/components/MessageSimple.js
Variable(`hasReactions`) is already a boolean
there is no need to coerce into number to compare.
> drop unnecessary coerce

- .eslintrc.json
`eslint-plugin-react` requires `react` version for some rules. Right now, it shows a warning since its version isn't set in the config. By setting `detect` in `eslint`, version info can be maintained in one place and there is no suspicious warning.
> detect react version to silence eslint warning for react

- src/components/MessageCommerce.js
Boolean (`hasReactions`) was compared to number unnecessarily where boolean could be used directly.
> refactor(message-commerce): Drop unnecessary coerce

- src/components/Channel.js
- src/components/MessageInput.js
- src/components/MessageList.js
- types/index.d.ts
Allow users to override the Edit messages network requests, similar to https://github.com/GetStream/stream-chat-react/pull/102
> override doEditMessageRequest

- src/components/Channel.js
- types/index.d.ts
This prop allow users to pass a custom function to catch network request for sending a new message. This can be used to reroute the new messages to custom API and send the message after some validation.
> override sendMessage request in Channel props

- src/components/Thread.js
- types/index.d.ts
Fix for issue: https://github.com/GetStream/stream-chat-react/issues/101
Currently there is no way to customise the underlying components of `Thread` component. Props added in this PR will give the client power to customise or add more props to them as he wishes.
> CRNS-48: Support props for thread customization

- src/components/ChannelList.js
- src/components/MessageInput.js
> I am pretty sure this is also happening on the React SDK (in that case I suggest to solve it there first and then copy/paste the same solution to RN to save dev time)
https://github.com/GetStream/stream-chat-react-native/issues/113
> allow changing filters to update the channellist

- src/components/ChannelPreview.js
fix ChannelPreview in ChannelList not getting updated on message delete or updates
> sync ChannelPreview latest message on edit/delete

- src/utils.js
Add the strikethrough option to the markdown renderer so the `~~text~~` doesn;t return an empty message
> add strikethrough to text renderer

- src/components/AutoCompleteTextarea/Textarea.js
- src/components/ChatAutoComplete.js
- src/components/EditMessageForm.js
- src/components/Message.js
- src/components/MessageInput.js
- src/components/MessageInputFlat.js
- src/components/MessageInputLarge.js
- src/components/MessageInputSmall.js
- types/index.d.ts
> Translation fix and additionalTextareaProps prop support

- src/components/Channel.js
- src/components/Message.js
- src/components/MessageList.js
- types/index.d.ts
- Update the reactions (add/remove) in UI without waiting for api calls.
- In case of failure, reset the added/removed reactions.
- Lifting `handleReaction` function up from `Message` (HOC) to `Channel` component.
- Lifting network status (state variable `online`) from `MessageList` to `Channel` component
- Updating channel state before calling sendReaction/removeReaction api.
- If promise gets rejected or api fails, then we reset the state update.
**NOTE** This PR is dependent on changes of following PR in js client - https://github.com/GetStream/stream-chat-js/pull/280
> CRS-22: Optimistic reaction updates to UI

- src/components/MessageList.js
Fixes the following issue: if two messages are for example two thursdays apart, the dateseparator is hidden
> Fix dateseparator on same day of week

- types/index.d.ts
This two properties are missing in typings.
Maybe it would be cleaner to remove comments for Preview & LoadingIndicator, or add comments for each one, but I'm not sure which code style you use here.
> add missing ChannelList's component overrides props types

- src/components/Message.js
- src/components/MessageCommerce.js
- src/components/MessageDeleted.js
- src/components/MessageLivestream.js
- src/components/MessageSimple.js
- src/components/MessageTeam.js
- types/index.d.ts
Adds `MessageDeleted` prop to all Message components. If left undefined, what happens if a message has been deleted is left up to the component itself. This means that for `MessageSimple` and `MessageCommerce` a default "message deleted" is rendered, whereas for the other Message components nothing is shown.
> Add MessageDeleted prop

- src/components/Gallery.js
- src/styles/Gallery.scss
- src/styles/Message.scss
This fixes alignment for galleries under long messages. It also turns a 3 image gallery into a flat list of thumbnails rather than a square gallery. Lastly, I fixed some issues with the rounded corners (i.e. no longer rounded on the wrong side, and fully rounded corners by tweaking width/margin)
> fix gallery alignment issues + better border rounding

- src/styles/Message.scss
- src/utils.js
Disabling truncation in case of emails. Also disabling hyphenation as hyphens could lead to confusion.
**Before**:
**After**:
Notice it will still break words in smaller screens:
> Disable truncation for email urls on messages

- src/components/MessageList.js
This adds an `onLoadCapture` handler to the parent of the `Message` component. This ensures that if some asset loads inside that message, the `MessageList` scrolls to the bottom (if applicable).
> CRS-235 ensure scrolling down when attachment loads

- src/components/ChannelList/ChannelList.js
Unset channel on delete if the deleted channel was the active one and there's no custom `onChannelDelete` handler.
> Unset channel on delete if it is active

- src/components/MessageInput/MessageInputFlat.js
- src/components/MessageInput/MessageInputLarge.js
- src/components/MessageInput/MessageInputSmall.js
- src/components/Reactions/ReactionSelector.js
- src/components/Tooltip/Tooltip.js
- src/i18n/en.json
- src/i18n/fr.json
- src/i18n/hi.json
- src/i18n/it.json
- src/i18n/nl.json
- src/i18n/ru.json
- src/i18n/tr.json
- src/styles/MessageInput.scss
- src/styles/MessageInputFlat.scss
This cleans up some remainder styling for the icons in the message input and adds a tooltip for those icons.
Examples:
> Show tooltips for emojis and attachments in message input

- types/index.d.ts
This commit 6ac325a6c68c4467b360b5917787bea7765a3c06 introduced typescript build errors:
```
Overload 1 of 2, '(props: Readonly<ChannelProps>): Channel', gave the following error.
Property 'mutes' is missing in type '{ children: Element[]; }' but required in type 'Readonly<ChannelProps>'.
Overload 2 of 2, '(props: ChannelProps, context?: any): Channel', gave the following error.
Property 'mutes' is missing in type '{ children: Element[]; }' but required in type 'Readonly<ChannelProps>'.
```
This is happen because top level components: `Channel`, `MessageList`, `Message` now require `mutes` prop.
In this PR I set mutes property back to optional for user extendable components, such as `Channel`, `MessageList`, `Message`, and leaved it as required for `MessageActions` component, which seems …
> make mutes prop optional

- types/index.d.ts
Currently the typescript definitions (i.e. interfaces) for Message components are set up as follows:
- MessageProps, which contains all the props for the high level Message component
- MessageUIComponentProps, which extends MessageProps, and adds some props specific to the UI components.
However, the high level Message component receives several props which the UI components ignore (and which aren’t defined in their PropTypes definitions). I refactored it so it accurately reflects the actual React components.
> CRS-244 Fix Message UI component type definitions

- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/MessageList/__tests__/MessageList.test.js
Something on our mocking strategy is not working as expected, resulting
in some tests failing. This skips those failing tests while we fix
this issue.
> Skip failing tests

- src/components/ChannelList/ChannelList.js
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/MessageList/__tests__/MessageList.test.js
- src/mock-builders/index.js
Some recent changes on stream-chat introduced a new way to handle users
and tokens. This led to some of our tests breaking, as our mocking
implementation no longer complied with the actual API of the library.
Here we fix this by mocking and abstracting away the bits that deal with
user and tokens.
> Fix client tests mock

- src/components/Message/MessageSimple.js
- types/index.d.ts
Rely on the MessageUIComponentProps directly. Fixes https://github.com/GetStream/stream-chat-react/issues/291.
Though on the implementation of the message UI components, we explicitly rely on some props to be there, the types are currently not accurately reflecting this. https://github.com/GetStream/stream-chat-react/commit/8d72c986439121ddefc0007e0ab9cb89f558f444 tried to work around this issue by making the specific UI component types more strict, following the actual implementation, but this causes problems as the higher-order components that wrap those UI components would need to comply to their more strict interface also. We could achieve this by [refining](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types) the UI component types …
> Fix MessageSimple types

- src/components/MessageInput/MessageInput.js
- src/components/MessageInput/MessageInputLarge.js
- src/components/MessageInput/SendButton.js
- src/components/MessageInput/__tests__/MessageInput.test.js
Note that these tests don't really try to mock out child components. This means that some of the functionality in these tests relies on the implementation of its children. With that said, I tried to stick to a declarative style as much as possible, so that the actual implementation of those children doesn't really matter, as long as they do what is expected for MessageInput to work properly. In that sense it follows what's in this article: https://kentcdodds.com/blog/why-i-never-use-shallow-rendering/
> CRS-139 MessageInput tests

- src/components/Message/MessageCommerce.js
- src/components/Message/__tests__/MessageCommerce.test.js
- types/index.d.ts
Moving on with adding tests for message components, This PR:
- Adds tests for MessageCommerce tests.
- Enable ESLint on MessageCommerce component.
- Enable Typescript check on MessageCommerce component.
~Should be merged after: https://github.com/GetStream/stream-chat-react/pull/295~ ✅
> Add <MessageCommerce /> tests and improve component

- src/components/Reactions/ReactionsList.js
- src/components/Reactions/SimpleReactionsList.js
- src/utils.js
- types/index.d.ts
This refactors ReactionsList and SimpleReactionsList to use hooks. There is some overlap in functionality between the two components, but I decided to not separate that into some separate module (or hook) because it's only used by these two components, and it's just two functions that take some prop and convert it into something that can be rendered (i.e. not stateful).
> Refactor ReactionsList and SimpleReactionsList

- src/components/Message/MessageDeleted.js
- src/components/Message/MessageSimple.js
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/__tests__/utils.test.js
- src/components/Message/hooks/__tests__/useActionHandler.test.js
- src/components/Message/hooks/__tests__/useDeleteHandler.test.js
- src/components/Message/hooks/__tests__/useEditHandler.test.js
- src/components/Message/hooks/__tests__/useFlagHandler.test.js
- src/components/Message/hooks/__tests__/useMentionsHandler.test.js
- src/components/Message/hooks/__tests__/useMuteHandler.test.js
- src/components/Message/hooks/__tests__/useOpenThreadHandler.test.js
- src/components/Message/hooks/__tests__/useReactionHandler.test.js
- src/components/Message/hooks/__tests__/useRetryHandler.test.js
- src/components/Message/hooks/__tests__/useUserHandler.test.js
- src/components/Message/hooks/useActionHandler.js
- src/components/Message/hooks/useDeleteHandler.js
- src/components/Message/hooks/useEditHandler.js
- src/components/Message/hooks/useFlagHandler.js
- src/components/Message/hooks/useMentionsHandler.js
- src/components/Message/hooks/useMuteHandler.js
- src/components/Message/hooks/useOpenThreadHandler.js
- src/components/Message/hooks/useReactionHandler.js
- src/components/Message/hooks/useRetryHandler.js
- src/components/Message/hooks/useUserHandler.js
- src/components/Message/hooks/useUserRole.js
- src/components/Message/utils.js
- src/mock-builders/generator/message.js
- types/index.d.ts
Refactors the <MessageSimple /> component. Creates some new custom hooks.
The general idea is to decouple all message UI components from the Message HOC, replacing the logic that now is handled by the later in the form of custom hooks. When migrating the other message UI components, we'll be able to abstract more of the logic that now lives inside the component itself, and that's shared between all of them.
> Make <MessageSimple /> a functional component

- src/components/ChannelHeader/ChannelHeader.js
- src/components/ChannelHeader/__tests__/ChannelHeader.test.js
Get all contextual data from ChannelContext rather than the ChatContext,
as `channel` might not be available on the latter.
> Fix <ChannelHeader /> component

- src/components/Message/MessageCommerce.js
- src/components/Message/MessageLivestream.js
- src/components/Message/MessageSimple.js
- src/components/Message/MessageTeam.js
- src/components/Message/MessageText.js
- src/components/Message/hooks/__tests__/useReactionHandler.test.js
- src/components/Message/hooks/useReactionHandler.js
- src/components/Reactions/ReactionSelector.js
- src/components/Reactions/__tests__/ReactionSelector.test.js
- types/index.d.ts
Converts ReactionSelector to hooks.
Note: technically a (small, probably irrelevant) breaking change because there no longer is a ref inside a ref in ReactionsList. Instead, the ref of the container div is directly forwarded by the component.
> CRS-224 ReactionSelector

- src/components/Reactions/ReactionSelector.js
#166 Submit a pull request
Added `@ts-ignore` because emoji-mart typescript definitions don't seem to support a usecase that is in fact supported by their actual implementation.
See: https://github.com/missive/emoji-mart/blob/master/src/components/emoji/nimble-emoji.js#L139
`spriteUrl` can be supplied instead of `imageUrl`, but the typescript definitions for their emoji components (e.g. `NimbleEmoji`) only allow `imageUrl` to be passed.
> Fix ReactionSelector typescript error

- src/components/Message/MessageLivestream.js
- src/components/Message/MessageTeam.js
- src/components/Message/MessageText.js
- src/components/Message/hooks/__tests__/useMentionsHandler.test.js
- src/components/Message/hooks/useMentionsHandler.js
- types/index.d.ts
Currently, there are two ways we allow our message components mention handlers
to be overwritten. A user might want to overwrite the click event itself
or the user might want to overwrite how we process this event.
Also in the current implementation, our message UI components deal with the latter,
while the <Message /> HOC deals with the first case. This commit makes
sure we keep it this way, by extending the useMentionsHandler custom
hook to handle both use cases while applying them correctly where
they're used - it will be later applied to the Message HOC as well.
> Fix useMentionsHandler hook

- src/components/Message/hooks/__tests__/useEditHandler.test.js
- src/components/Message/hooks/useEditHandler.js
- src/components/MessageActions/MessageActions.js
Adding the whole editing state handling to the edit handler hook, as
this now belongs to the message components. While doing it, I noticed
that there are 2 edit handlers passed to the MessageActions component,
both intended to deal with setting the edit state to true. Because of
that, and because for now this component is only used internally, I
removed one of them in favor of the other, simplifying the logic there.
This is needed to complete https://github.com/GetStream/stream-chat-react/pull/415.
> Improve edit handler

- src/docs/MessageInputHooks.md
- styleguide.config.js
Adding some initial documentation for the message input custom hook.
Preview:
> Add initial message input custom hook documentation

- src/components/Channel/Channel.js
> fix: channel title when read_events are disabled

- src/components/Message/Message.js
- src/components/Message/MessageCommerce.js
- src/components/Message/MessageLivestream.js
- src/components/Message/MessageSimple.js
- src/components/Message/MessageTeam.js
- src/components/Message/MessageTimestamp.js
- src/components/Message/__tests__/MessageTimestamp.test.js
- types/index.d.ts
This provides a way for overriding the Datetime information rendered by the message UI components.
Closes #128.
To-do:
> Allow message timestamp override

- src/components/Reactions/SimpleReactionsList.js
- src/components/Reactions/__tests__/SimpleReactionsList.test.js
This check was present on the class version of the component, so we probably dropped it accidentally when migrating it to a functional component.
> Only render <SimpleReactionList /> if there are reactions

- examples/commerce/package.json
- examples/commerce/yarn.lock
- examples/livestream/package.json
- examples/livestream/yarn.lock
- examples/messaging/package.json
- examples/messaging/yarn.lock
- examples/team/package.json
- examples/team/yarn.lock
- examples/typescript-app/package.json
- examples/typescript-app/yarn.lock
> Bump example app dependencies

- src/components/Gallery/Image.js
- src/components/Gallery/__tests__/Image.test.js
- src/components/Gallery/__tests__/__snapshots__/Image.test.js.snap
Some outdated browsers could still allow javascript execution from img
elements, which could lead to XSS. Although such browsers would fall
outside the scope of our supported browsers, fixing the vulnerability is
a simple, so we're opting for doing it here.
It is important to note that the javascript check will be obsolete in
the next major react version, where it will no longer render uris with
javascript as a protocol.
> [CRS-276] Sanitize URL image sources in Image component

- src/components/Message/Message.js
- src/components/Message/MessageOptions.js
- src/components/Message/__tests__/MessageCommerce.test.js
- src/components/Message/__tests__/MessageOptions.test.js
- src/components/Message/__tests__/utils.test.js
- src/components/Message/utils.js
> CRS-289: make reply/reactions available in messageActions

- src/components/Thread/Thread.js
- src/components/Thread/__tests__/Thread.test.js
pending on #579 for tests to pass
> feat: Thread renders null if replies is disabled

- package.json
- src/components/Channel/Channel.js
- src/components/MessageInput/MessageInputFlat.js
- src/components/MessageInput/MessageInputLarge.js
- src/components/MessageInput/MessageInputSmall.js
- src/components/MessageInput/__tests__/MessageInput.test.js
- src/components/MessageInput/hooks/messageInput.js
- src/i18n/en.json
- src/i18n/fr.json
- src/i18n/hi.json
- src/i18n/it.json
- src/i18n/nl.json
- src/i18n/ru.json
- src/i18n/tr.json
- yarn.lock
Draft: relies on https://github.com/GetStream/react-file-utils/pull/22. Relates to https://github.com/GetStream/stream-chat-react/issues/565
This PR uses `channelContext.maxNumberOfFiles` to prevent the user from uploading too many files. It does so by doing two things:
- setting the `maxNumberOfFiles` prop in `ImageDropzone` (part of `react-file-utils`)
- disabling the file upload button if needed
Other fixes:
- Removing while uploading no longer throws
- if `channelContext.multipleUploads` is set to false, you can now only upload a single file (and its default value is now `true`)
To do:
- Get translations for tooltip ("You've reached the maximum number of files")
- UI indication in ImageDropzone, when attempting to drop more than the allowed number of files (in `react-file-utils`)
> CRS-293 Max attachments

- src/components/Message/MessageOptions.js
> fix #586: displayActions respected in MessageOptions

- package.json
- src/components/Channel/hooks/useEditMessageHandler.js
- src/components/Channel/hooks/useMentionsHandlers.js
- src/components/Message/hooks/useActionHandler.js
- src/components/Message/hooks/useDeleteHandler.js
- src/components/Message/hooks/useFlagHandler.js
- src/components/Message/hooks/useMentionsHandler.js
- src/components/Message/hooks/useMuteHandler.js
- src/components/Message/hooks/useOpenThreadHandler.js
- src/components/Message/hooks/useReactionHandler.js
- src/components/Message/hooks/useRetryHandler.js
- src/components/Message/hooks/useUserHandler.js
- src/components/Message/hooks/useUserRole.js
- src/components/MessageInput/hooks/messageInput.js
- types/index.d.ts
- yarn.lock
Moving some custom hook type definitions to `.d.ts`. Due to https://github.com/microsoft/TypeScript/issues/38691 it wasn't possible to do so on the version of TS we were using, so I upgraded TS and locked it to their current release candidate.
closes #481
> Add custom hook types

- src/components/Message/MessageCommerce.js
- src/components/Message/MessageLivestream.js
- src/components/Message/MessageSimple.js
- src/components/Message/MessageTeam.js
- src/components/Message/MessageText.js
- types/index.d.ts
Pass `message.own_reactions` into reactions components so custom implementations can use it to show the current user's reaction.
> CRS-320 Add own reactions

- src/components/Channel/Channel.js
- src/components/ChannelPreview/ChannelPreview.js
- src/components/ChannelPreview/__tests__/ChannelPreview.test.js
> add channel preview mute support

- src/components/Channel/Channel.js
not the most brilliant approach, but our WS is a little bit behind detecting network is down or not
well supported: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine
> fix: prevent firing load more when user is offline

- examples/commerce/src/App.js
- examples/livestream/src/App.js
- examples/messaging/src/App.js
- examples/team/src/App.js
- examples/typescript-app/src/App.tsx
Uncomment `setBaseURL` with the `REACT_APP_CHAT_SERVER_ENDPOINT` env var in all example apps.
> uncomment setBaseURL

- src/styles/ChannelHeader.scss
Height and Width cut off svg on mobile. Adds padding instead to fix issue.
> stops box from covering svg

- src/styles/Message.scss
Removes extra margin on messages that are only emojis.
https://stream-io.atlassian.net/browse/CRS-247
> removes extra margin on emoji only messages

- CHANGELOG.md
> 3.6.0-changelog

- src/components/Message/hooks/useReactionHandler.js
- types/index.d.ts
Fixes #715
Based on my inspection, a race condition of catching the click event happens. For the bug to be reproduced, the list should be scrolled up and down - my guess is that this changes the event handler execution order, but I am not 100%. 
The proposed solution delays the attachment of the hide event handler. It works when testing manually.
> Fix erratic reaction list display

- src/components/Message/MessageText.js
- src/components/Message/__tests__/MessageText.test.js
- src/components/Message/hooks/index.js
- src/components/Message/hooks/useBreakpoint.js
- src/components/Message/hooks/useMobilePress.js
- src/components/Message/utils.js
- src/styles/Message.scss
The MessageText component triggers the display of the MessageOptions (react, reply, actions) onHover. This created some issues on mobile where hover events do not exist. We now disable hover on mobile and trigger an onClick event to show the MessageOptions when a user presses the MessageText component.
> Mobile Options onClick

- CHANGELOG.md
> v4.1.2 changelog

- src/components/MessageList/VirtualizedMessageList.js
- src/styles/VirtualMessage.scss
Explanation:
https://stackoverflow.com/a/38523642/1009797
The above is necessary if we would like to have disappearing messages (due to soft deletion for example). In addition to that, this PR moves the inline styling of the virtual list message wrappers to a class, so that inline-block can be overwritten if necessary.
> Fix handling of 1px tall messages

- src/components/AutoCompleteTextarea/List.js
- src/components/AutoCompleteTextarea/Textarea.js
- src/styles/MessageList.scss
- src/styles/index.scss
- Fixes regression around keyboard navigation in suggestions list (scroll position was no longer being updated on lists that don't fit the container)
- Fixes regression that caused the selected item to be reset to the first item (due to `SuggestionListContainer` being redefined in the render method of the `Textarea` component)
- Fixes CSS issue where ReactionList would sometimes cover the suggestions from TextAreaAutocomplete
> CRS-442 emoji keyboard navigation

- src/components/ChatAutoComplete/ChatAutoComplete.js
This patch fixes a bug when the user types "-" followed by `<space>`.
> Fix unexpected undefined in autocomplete

- src/components/MessageList/MessageListInner.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/utils.ts
Adds disableDateSeparator property for the virtual message list. To avoid breaking changes, the default value of the property is `true`.
> Support date separators in virtual message list

- src/styles/Message.scss
- src/styles/MessageCommerce.scss
- src/styles/MessageLivestream.scss
- src/utils.tsx
Renders mentions as span with `str-chat__message-mention` class instead of just wrapping it in a `<strong>`. Also allows users to override the wrapping component for mentions by supplying a custom mentions component to the `renderText` function.
> CRS-441 customizable message mentions

- src/components/Gallery/Gallery.tsx
- src/components/Gallery/ModalImage.tsx
Found two bugs with image attachments:
- single-attachment images didn't show up in the lightbox
- (found out that we were setting both `source` and `src` for multiple-image galleries, but only `source` for single-attachment galleries, the latter seems to correspond to `react-images` types)
- after clicking a thumbnail in a gallery with multiple images, it was impossible to close the lightbox
> Fix image attachment bugs

- package.json
- yarn.lock
> CRS-458 upgrade react-file-utils to prevent jsx-runtime from being required

- src/components/AutoCompleteTextarea/Textarea.js
This fixes a bug where the list of suggestions would sometimes open after a message had already been submitting because the promise needed to populate that list would only resolve after the user had submitted the message. `_closeAutocomplete` takes care of all the cleanup that is needed in this case.
> CRS-479 force close autocomplete suggestions on submit

- src/components/AutoCompleteTextarea/List.js
- src/components/AutoCompleteTextarea/Textarea.js
See the second comment in https://github.com/GetStream/stream-chat-react/issues/838
Triggers currently only correctly support highlighting of suggestions if the trigger is right at the start of the input value, which this PR fixes.
While working on this I realised that some of it could also be used to simplify the work I did on https://github.com/GetStream/stream-chat-react/pull/827, so I added that to this PR as well.
> CRS-494 Fix autocomplete trigger hightlight

- src/components/ChatAutoComplete/ChatAutoComplete.tsx
We use a custom dataset for emoji-mart to reduce the bundle size. For this reason, we left out the skin color variations and only ship the bright yellow emojis. It turns out that there is one code path inside emoji-mart's `NimbleEmojiIndex` that expects these skin color variations to be present: https://github.com/missive/emoji-mart/blob/ccd591dd5af5ea21455e65b16c233f4876447b80/src/utils/emoji-index/nimble-emoji-index.js#L99. This causes it to return `undefined` only when a user searches for `-` or `-1` inside our Autocomplete Textarea.
This PR contains a small workaround, which just filters out these falsy values. That does mean that users cannot search for the "thumbs down" emoji by typing `-` or `-1`, but it still works if you search e.g. `thumbs down`. We can talk to the folks who …
> Filter out any falsy values of emojiIndex.search result

- src/styles/MessageActions.scss
See https://github.com/GetStream/stream-chat-react/issues/845
This PR removes some old css that was not used anywhere in the actual components. It includes an inline svg icon that caused Gatsby to throw an error.
> Remove unused css that caused Gatsby to error

- src/components/AutoCompleteTextarea/Textarea.js
fix trigger regex: no match if any of the subsequent parts are the contain a new trigger token, needed to support subsequent triggers
Previously, if a user tried to use multiple triggers in the same message (e.g. mentioning multiple users), the second trigger didn't work. This was due to the regex, which matched everything starting from the first trigger's token until the position of the cursor. This updated regex prevents that from happening.
> Fix trigger regex

- src/utils.tsx
filter out non-unique links, and replace all instances in the message text at the same time to prevent buggy behaviour with duplicate links
> CRS-268 Fix messed up url parsing when you add the same URL twice

- package.json
The peerDependency was declaring `stream-chat@3.1.x` which block us installing `stream-chat@3.7.0` when we use npm@7 in strict mode
Using `^3.1.0` should fix the issue as it would allow all `v3` major version that are above `3.1.0`
> fix: Wrong "stream-chat" peer dependency

- src/styles/_base.scss
This hard-coded relative path was causing issues for me when trying to import the SASS into my project to extend the base styles. I believe this should reference the `assetsPath` variable.
> use assetPath variable instead of hard-coded relative path

- package.json
- yarn.lock
Discovered an edge case that needs:
- a tall virtualized message list 
- a very tall last message (attachments help)
- a set of one-liners above it
When all of the above combine, the list does not start from the bottom. 
Resolved in the virtualized list upstream dependency.
> fix(): resolve edge case with tall last message

- docusaurus/docs/React/core-components/virtualized-list.mdx
- package.json
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/hooks/useNewMessageNotification.ts
- yarn.lock
- Expose `defaultItemHeight` prop to smooth out long uneven lists
- Fix quick "new messages" blink when loaded or switching channels
> Virtualized list improvements

- src/components/Message/MessageOptions.tsx
- src/components/Message/icons.tsx
- src/components/MessageActions/MessageActions.tsx
- src/version.ts
Added `ActionsIcon`, `ReactionIcon`, `ThreadIcon` props to the `MessageOptions` component to override the SVGs within.
> Message options updates

- src/components/MessageInput/hooks/useUserTrigger.ts
Fix a bug that actually incorrectly only included muted users as mention options instead of the reverse.
Updated the conditional in the `filterMutes` method.
None
> fix mentions list to not include muted users

- src/components/MessageInput/hooks/useUserTrigger.ts
Fix the `filterMutes` method to correctly filter muted users, but in case of the '/unmute' trigger in the text, include only muted users in the results to effectively unmute.
Update conditionals in the `filterMutes` method in `useUserTrigger`.
None.
> more filter mentions updates

- src/components/AutoCompleteTextarea/Textarea.js
- src/version.ts
Prevent the text `@:` from crashing the app
Added conditional check to not throw error if current trigger is `:`
none
> prevent mentions crash with emoji colon

- CHANGELOG.md
- docusaurus/docs/React/core-components/channel-list.mdx
- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/hooks/useNotificationAddedToChannelListener.ts
- src/components/ChannelList/hooks/useNotificationMessageNewListener.ts
Ensure the creation of new channels and messages on unwatched channels won't increment the list if not desired.
Add `allowNewMessagesFromUnfilteredChannels` argument to `useNotificationMessageNewListener` and `useNotificationAddedToChannelListener` ChannelList hooks and corresponding conditionals to prevent channel from incrementing list.
None
> add allowNewMessagesFromUnfilteredChannels argument to channellist hooks

- docusaurus/docs/React/contexts/message-input-context.mdx
- src/components/MessageInput/hooks/useMessageInputState.ts
Provide a function that easily overrides and sets the MessageInput text value
Add `setText` function that dispatches an action on our MessageInput reducer
None
> add setText to message input context

- CHANGELOG.md
- docusaurus/docs/React/core-components/channel.mdx
- src/components/Channel/Channel.tsx
All people to customize the setting of the document title when the active channel has unread messages
Add new prop to Channel that overrides our default behavior
None
> add active unread handler function to Channel

- docusaurus/docs/React/contexts/message-input-context.mdx
- docusaurus/docs/React/message-components/attachment.mdx
- docusaurus/docs/React/message-input-components/message-input.mdx
- src/components/MessageInput/MessageInput.tsx
Provide clarification to Attachment documentation.
Add Attachment file types to documentation, as well as more info for `noFiles` `MessageInput` prop.
None.
> attachment type documentation

- src/components/Avatar/Avatar.tsx
- src/version.ts
Allow the Avatar fallback logic to display an emoji if one is the first character in a user's name
Add a regex check that tests to see if the first two characters comprise a unicode emoji
None
> support emoji as first character in avatar name

- docusaurus/docs/React/core-components/virtualized-list.mdx
- src/components/MessageList/VirtualizedMessageList.tsx
Allow people to customize the props passed to `react-virtuoso`
Add an optional prop to `VirtualizedMessageList` the spreads props into the `Virtuoso` component
None
> option to pass props to virtuoso component

- examples/typescript/yarn.lock
- src/components/Channel/Channel.tsx
- src/version.ts
Prevent the message list from re-rendering when users join/leave a channel
Do not initiate an action to update the state returned from the channel reducer when user watch events are received
None
> prevent user watch events from updating channel state

- src/components/MessageInput/hooks/useCreateMessageInputContext.ts
Add `CooldownInterval` to the `MessageInput` memoization hook.
Add `CooldownInterval` to the `MessageInput` memoization hook.
None.
> add cooldowninterval to input memoization

- src/components/Channel/hooks/useCreateChannelStateContext.ts
- src/components/Message/utils.tsx
Update user info in real time when clients are subscribed to presence events
Ensure memoization cases don't prevent messages from re-rendering when user name or image changes
> update user info in messages when subscribe to presence events

- src/utils.tsx
To prevent already encoded uri from being double encoded 
decode the URI before encoding
> fix: check for already encoded url

- docusaurus/docs/React/contexts/chat-context.mdx
- docusaurus/docs/React/core-components/chat.mdx
- docusaurus/docs/React/custom-code-examples/channel-search.mdx
- docusaurus/docs/React/custom-code-examples/override-submit-handler.mdx
- docusaurus/docs/React/troubleshooting/troubleshooting.mdx
- docusaurus/docs/React/utility-components/channel-preview-ui.mdx
- examples/website-demos/social-messaging/src/components/ChannelPreview/SocialPreviewActions.tsx
Docusaurus complained about some broken links, this should fix it.
For the relevant ones, link to the mdx file as is done (seemingly) everywhere else to not confuse the resolver in docusaurus. Linking to files also ensures that the CLI will give information about the link if it can't be resolved in the future.
A couple links seemed to have missed an update, or something.
Tested the changes out locally to make sure they worked fine after the changes.
No UI changes (except less 404 :D)
*NOTE*: I had to skip the hooks when making the commit as the python script checking for large files broke cause of "bogus GIT_CONFIG_PARAMETERS", but that should not matter in this case.
> docs: Fix broken links in the docusaurus docs

- docusaurus/docs/React/contexts/chat-context.mdx
- docusaurus/docs/React/message-input-components/message-input.mdx
- src/components/MessageInput/MessageInput.tsx
- src/components/MessageInput/hooks/useAttachments.ts
- src/components/MessageInput/hooks/useEmojiPicker.ts
- src/components/MessageInput/hooks/useFileUploads.ts
- src/components/MessageInput/hooks/useMessageInputState.ts
Focus input after emoji and attachment selection. Close emoji selector upon selection if closeEmojiPickerOnClick prop is true.
Update useEmojiPicker's onSelectEmoji method and useAttachment's uploadNewFiles method to focus. Add `closeEmojiPickerOnClick` prop to `MessageInput` to optionally close the picker on select.
> focus input after emoji and attachment selection

- src/components/ChatAutoComplete/ChatAutoComplete.tsx
Make it possible to override the default wordReplace functionality. Our product includes a number of custom emotes that don't have `.native` values that we'd like to handle in a different way using `ChatAutoComplete`, but currently we don't have access to change the behavior of the autocomplete selection.
Adds an optional prop that takes a function to apply custom autocomplete behavior.
No UI changes, change is backwards compatible and passes the existing tests.
> Add wordReplace prop to ChatAutoComplete to override default behavior

- src/components/ChannelList/hooks/useChannelUpdatedListener.ts
After a channel.updated event is fired the own_capabilities array and hidden value are lost. 
This change adds those two values back to the channel.data object.
> fix: keep channel capabilities array

- src/components/MessageInput/UploadsPreview.tsx
The `ThumbnailPlaceholder` component should not be visible if multiple upload is disabled
We have to set the `disabled` prop of `ImagePreviewer` component to false if multiple upload is disabled
> Set ImagePreviewer to disabled if multiple upload is not allowed

- src/utils.tsx
Use decodeURIComponent, now correctly decoding URLs like
http://example.com/?orderBy%3D%5Ba%2Cb%2Cc%5D
> Support URLs with encoded components

- src/components/Message/hooks/useUserRole.ts
Fix code so quotes (aka replies) are not still available in message options when quotes are disabled in configuration.
Account for channelCapabilities permissions when assigning `canQuote` value.
> fix: acount for channel capabilities when assigning canQuote value

- src/components/Window/Window.tsx
- src/components/Window/__tests__/Window.test.js
Update the Window component so it doesn't remount the list components when using `hideOnThread` prop. Scenario: when scrolled up in the list and clicking on a thread, when closing the thread the list should be at the same spot instead of scrolled to the bottom.
A true value for the `hideOnThread` prop is now handled via CSS rather than by returning null in the Window component.
> Hide onthread update

- package.json
- yarn.lock
The latest version of stream-chat-css includes the removal of a font import and the changes necessary for the upcoming features in stream-chat-react.
> chore: upgrade css

- src/components/MessageList/VirtualizedMessageList.tsx
This PR sets some sensible defaults for react-virtuoso.
- Renders new messages instantly through `increaseViewportBy`, reducing jumps when new messages are received;
- Measures fractional heights, reducing the chance of rendering glitches in a zoomed-out state.
- Silences benign ResizeObserver errors.
> Improve default performance of VirtualizedMessageList

- docusaurus/docs/React/message-input-components/ui-components.mdx
- src/components/ChatAutoComplete/ChatAutoComplete.tsx
Adds the transitive `onBlur` prop to `ChatAutoComplete`, mirroring `onFocus`.
Fixes #1345.
> onBlur prop for ChatAutoComplete

- docusaurus/docs/React/core-components/channel.mdx
- src/components/Channel/Channel.tsx
* Fix an inconsistency introduced in https://github.com/GetStream/stream-chat-react/pull/1374, where the default value in the doc was not the same as what was used in the code.
* Change the default giphyVersion to `fixed_height` to maintain parity across the component SDKs.
* Fix the incorrect removal of the documentation of giphyVersion prop in 5b88fff01d436d767876cc515b3b61c6fe542bee and fcad45d76a1aad841ec36309f22e855381fe284d
The giphy attachment payload includes several versions. By default, we use `fixed_height`. The Channel prop can be used to change the version name.
NA
> Fix giphy usage inconsistencies

- src/components/MessageList/VirtualizedMessageList.tsx
This change prevents the unnecessary reset of scroll position if no new messages have been received.
Fixes #1415
> fix: make scrollToLatestMessageOnFocus smarter

- docusaurus/docs/React/message-components/ui-components.mdx
- src/components/Message/MessageSimple.tsx
- src/components/MessageActions/MessageActions.tsx
- src/components/MessageActions/__tests__/MessageActions.test.js
The original behavior of actions box to disappear on hover away keeps being opt in by passing the `messageWrapperRef`. However the `MessageSimple` component does not pass neither create this ref anymore to `MessageOption` (and thus down to `MessagActions`). Moreover event listener for `keyup` event is now registered and hides message actions box on pressing `Escape` key only.
These changes then lead to the message actions box being hidden when user:
- clicks outside
- presses Escape key
- presses on an item in the menu
fixes #1401
> Dont hide message actions dialog on hover away

- src/components/MessageInput/MessageInputFlat.tsx
Allign the send button with the `textarea` when there's an upload preview available.
Before (don't mind the input icons):
After:
> Move `UploadsPreview` outside textarea wrapper

- src/i18n/Streami18n.ts
Fixes #1467 - Bei is the wrong word to use in a time context. Same as zu
Signed the CLA
To improve/fix German calendar translations
Just updating the translation strings
> Fix german calendar translation strings

- docusaurus/docs/React/core-components/channel.mdx
The "DateSeparator" link is broken in the [channel#DateSeparator](https://getstream.io/chat/docs/sdk/react/core-components/channel/#dateseparator) docs
> Fix broken link in doc

- src/i18n/Streami18n.ts
Fix Portuguese timestamp translations.
The previous translation didn't make much sense to Portuguese speakers, so this patch corrects it.
Note: Portuguese is a gendered language, so while this fixes the translation for the feminine week days (Monday to Friday), Saturday and Sunday will be slightly wrong. They're masculine and should be written "Sábado passado" and "Domingo passado", but I don't know how to fix this right away.
> Fix Portuguese timestamp translation

- docusaurus/docs/React/customization/typescript.mdx
The [typescript and generics guide ](https://getstream.io/chat/docs/sdk/react/customization/typescript_and_generics/) contains outdated links (the links point stream chat v5 code, when they should point to v6)
> docs: Fix outdated links in generics guide

- package.json
- src/components/MessageInput/MessageInputSmall.tsx
- yarn.lock
1. Avoid file upload preview overflow in thread. 
2. Bump the @stream-io/stream-chat-css dependency to the latest version that fixes message overflows in thread.
Change the parent container by moving the preview one level higher.
Before:
After:
> fix: Upload preview overflow in thread

- .github/auto-merge.yml
- .github/dependabot.yml
Streamline installation of `stream-chat*` dependencies by adding dependabot configuration. For automatic merging of PRs raised by dependabot I propose to use [probot-auto-merge bot](https://github.com/bobvanderlinden/probot-auto-merge) only for `@stream-io/stream-chat-css`. I believe that updates in the `@stream-io/stream-chat-css` package can be tested only with `stream-chat-react` and so there should not be any incompatibility. As the time goes, we may decide for auto-merge of `stream-chat` bump PRs too.
> ci: add dependabot & PR auto-merge

- docusaurus/docs/React/customization/typescript.mdx
- src/components/Message/MessageCommerce.tsx
- src/components/Message/MessageLivestream.tsx
- src/components/Message/MessageSimple.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/__tests__/utils.test.js
- src/components/MessageList/hooks/useMessageListElements.tsx
- src/components/MessageList/utils.ts
- src/constants/messageTypes.ts
- src/types/types.ts
Fix the bug that generated custom messages of type `'message.date'` with duplicate id as the message they preceded.
fixes #1510 
This PR adds a refactor to the use of custom message type values `'message.date'` and `'channel.intro'`. These values were scattered all around the code base. If they were to be changed, the maintainer would have to make sure those values are changed correctly in all the places. Now the values are referenced by a `CUSTOM_MESSAGE` constant dictionary in a new folder `src/constants`.
> fix: prevent duplicate message id generation in message list

- e2e/jump-to-message.test.ts
- src/stories/connected-user.stories.tsx
- src/stories/hello.stories.tsx
- src/stories/jump-to-message.stories.tsx
- src/stories/mark-read.stories.tsx
- src/stories/utils.tsx
Connection issues due to previous setup caused problems to some of the tests which then failed.
- use of `new StreamChat()` instead of `StreamChat.getInstance` ensures new instance for each story, disconnection happens behind the scenes and is not intrusive
- fix double `beforeEach` call in `jump-to-message` test
> test: fix client connect/disconnect issue

- src/components/Gallery/Gallery.tsx
- src/components/Gallery/__tests__/Gallery.test.js
- src/components/Gallery/__tests__/__snapshots__/Gallery.test.js.snap
Display overlay "X more" on Gallery only if more images uploaded than displayed.
Fixes #1418 
If user clicks on:
1. image without the overlay -> the Gallery modal displays the clicked message
2. image with the overlay -> the Gallery modal displays the clicked message
<details><summary>1 image</summary>
</details>
<details><summary>2 images</summary>
</details>
<details><summary>3 images</summary>
</details>
<details><summary>4 images</summary>
</details>
<details><summary>5 images</summary>
</details>
<details><summary>6 images</summary>
</details>
<details><summary>thread</summary>
</details>
> fix: display overlay "X more" on Gallery only if more images uploaded than displayed

- package.json
- yarn.lock
Bump mml-react to remove sanitize-url v5 from sub-dependencies.
> chore(deps): bump mml-react from 0.4.2 to 0.4.5

- docusaurus/docs/React/basics/getting-started.mdx
- docusaurus/docs/React/customization/typescript.mdx
Update documentation to use basic instantiation rather than using `StreamChat.getInstance` which causes connection issues for the users who tend to switch between user profiles within one application.
> docs: `connect/disconnect(User)`/instantiation code snippets update

- .github/workflows/size.yml
Fix error in action Compressed Size:
```Unable to resolve action `preactjs/compressed-size-action@v2.5`, unable to find version `v2.5```
> ci: change preactjs/compressed-size-action version to @latest

- .releaserc.json
Add `releaseRules` key to the `.releaserc.json` configuration file to trigger release on commit of type `chore` with scope `deps`.
> ci(release): add releaseRules to commit-analyzer plugin

- src/components/Channel/__tests__/Channel.test.js
- src/components/Channel/hooks/useCreateChannelStateContext.ts
- src/components/ChannelPreview/ChannelPreview.tsx
- src/components/ChannelPreview/__tests__/ChannelPreview.test.js
- src/components/Message/utils.tsx
- src/mock-builders/event/index.js
- src/mock-builders/event/userUpdated.js
Reflect updates to user's data in:
* 2-members channel preview
* Avatar (in MessageList, Thread, ChannelPreview)
fixes #1565
The change's are performed upon reception of WS event `user.updated`. The implementation takes into account that a user can have custom fields and therefore the memoization in `MessageList` takes this into account. Until now, the changes were propagated to the most bottom components only if user's `image` or `name` changed. Those are default attributes. Therefore if a custom `Avatar` component displays custom user data, their update would not be reflected until page is refreshed.
The `ChannelList` component neither its children were listening to `user.updated` event and therefore the event listener has been added to the `ChannelPreview`'s effect. 
`ChannelHeader` …
> fix: propagate user update data to UI

- .github/ISSUE_TEMPLATE/bug_report.md
Add a new default label on the bug issue template. It should provide a feedback to a requester about the actual status of the issue. The status then can be changed by labeling the issue "status: confirmed" once confirmed by a maintainer dev.
> chore: add "status: unconfirmed" label to a newly created issue

- package.json
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/InfiniteScrollPaginator/InfiniteScroll.tsx
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/hooks/__tests__/useMessageListScrollManager.test.js
- src/components/MessageList/hooks/useMessageListScrollManager.ts
- src/components/MessageList/hooks/useScrollLocationLogic.tsx
- yarn.lock
The logic, that assures the channel to be scrolled to the bottom on page load uses `scrollToBottom` function call in multiple places and multiple hook effects. The current logic does not handle the scroll behavior on message list `scrollHeight` change robustly. It just sets timeout 200ms to scroll to the bottom after the last invocation of `scrollToBottom` function. On slower network the may images load slower than that leaving the channel not scrolled to the bottom.
Use `ResizeObserver` to keep the channel scrolled to the bottom until the user initiates own scroll behavior. Once user starts scrolling, the resize observer is cancelled.
The heuristic used to infer that the scroll has been user-initiated compares the total number of calls to `scrollToBottom` function and the number of …
> feat: use ResizeObserver to keep Channel scrolled to bottom on page load

- src/components/InfiniteScrollPaginator/InfiniteScroll.tsx
- src/components/MessageList/MessageList.tsx
The jump-to-message logic in `MessageList` was broken because the browser could not calculate the correct target message position. This was due to the fact, that at the moment of the calculation, the `MessageList` was higher because of conditionally rendering the loading indicator. Once the indicator is positioned absolutely and is kept among the `MessageList` children, the calculation and scroll to the position are performed correctly.
Depends on https://github.com/GetStream/stream-chat-css/pull/116
> fix: calculate jumped-to-message position correctly by keeping the loading indicator mounted

- src/components/MessageList/hooks/useScrollLocationLogic.tsx
Solves open Issue #1623. Build will fail with Gatsby and Next.js if window is undefined.
Add check if window is defined
> fix: add check if window is defined before using ResizeObserver

- examples/typescript/yarn.lock
- package.json
- yarn.lock
Updates `react-player` to `v2.10.1`, a version which fixes the problem with excessive logging when using React v18 in `StrictMode`. Closes: #1626.
`react-player@2.10.1` currently has one known issue which prevents certain events (`onProgress`) from firing in `development` mode when using React v18 `StrictMode`. We don't use these events in our SDK codebase but a customer of ours can be using them if they opted into overriding the default `AttachmentProps.Media` component. In that case, our customers would have to explicitly pin their dependency towards `react-player` or temporary disable `StrictMode`.
This problem only occurs in development mode.
> feat: upgrade react-player to its latest version

- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/hooks/usePrependMessagesCount.ts
- src/stories/hello.stories.tsx
A customer discovered that scrolling back through a virtualized message list does not work as expected. 
Upon closer investigation, it turned out that our logic for prepend item count does not work with date separators.
The fix ignores the date message. 
We need to add E2E tests for that, but we need to populate a channel with messages in multiple days. This is semi-possible now.
> fix: correct calculation of scrollback with date separators

- docusaurus/docs/React/core-components/thread.mdx
- src/components/Message/Message.tsx
- src/components/Message/__tests__/utils.test.js
- src/components/Message/utils.tsx
- src/components/Thread/Thread.tsx
- src/components/Thread/__tests__/Thread.test.js
- src/stories/toggle-message-actions.stories.tsx
This PR fixes the issue described in #1627. While working on it, we discovered that `Thread` messages always have all messageActions enabled and afterwards filtered out based on user's permissions.
- `messageActionHandler` now respects the `messageActions` prop
- `Thread` component now accepts additional `messageActions` property which will later be passed down to the selected `MessageList` implementation
> fix: respect updates to messageActions prop, support messageActions overrides in Thread

- package.json
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/__tests__/__snapshots__/VirtualizedMessageList.test.js.snap
- src/stories/hello.stories.tsx
- yarn.lock
At some point, the virtualized message list regressed its default setup for loading earlier messages. 
The first load more did not persist its scroll location properly due to page size being larger than the initial message count.
Upgrading to the latest version should also reduce messages unmounting/remounting, so less blinking of the avatars.
Upgrade to the latest react-virtuoso version, which fixes the problem and adds tests for that scenario. 
Related test cases:
https://github.com/petyosi/react-virtuoso/blob/master/examples/prepend-items.tsx
https://github.com/petyosi/react-virtuoso/blob/master/e2e/prepend-items.test.ts#L27-L34
> fix: initial load earlier in vml persists the position

- .github/workflows/docusaurus.yml
Add ability to push documentation changes to `stream-chat-docusaurus` staging branch when new changes are pushed to the `develop` branch within this repository. 
Implementation [tested here](https://github.com/GetStream/stream-chat-react/runs/7200293672?check_suite_focus=true#step:2:1).
> ci(docusaurus): add staging enviroment

- src/components/Channel/Channel.tsx
Allow usage of custom message ID within `sendMessage` function of `ChannelActionStateContext`.
Fixes: #1656
> fix(Channel): allow usage of custom message ID in `sendMessage`

- src/components/MessageActions/MessageActionsBox.tsx
Allow quoting quoted messages by removing part of the condition within the `MessageActionsBox` component.
> fix: allow quoting quoted messages

- src/components/Message/hooks/__tests__/useUserRole.test.js
- src/components/Message/hooks/useUserRole.ts
I'm not entirely sure how this was/is supposed to work. But in my case the api/library does not provide a `role` inside the channel state membership. Instead, it receives an `is_moderator: bool` and a `channel_role: string`.
This pull requests extends the `isModerator` check with these two props to correctly ensure a user is a moderator of the given channel. I didn't want to break previous behavior, so I left the `role` check in there.
> fix: align user role checks with channel membership, deprecate isModerator, isAdmin, isOwner

- src/components/MessageList/CustomNotification.tsx
- src/components/MessageList/__tests__/CustomNotification.test.js
Closes #1587 
This PR brings only a single change related to v2 theme for message notitications - addition of v2 class to `CustomNotification` component. The message notification logic remains the same.
Compared to https://github.com/GetStream/stream-chat-angular/pull/314, this PR does not introduce message notification into the `EmptyStateIndicator` as shown below:
It may be beneficial to introduce a notification service and not a`MessageNotification` component that is tightly coupled to `MessageList` logic. A proposal of such system is described in the issue #1671
The only change is the styling of the notification stripe:
> Theming v2 message notifications react

- docusaurus/docs/React/message-components/reactions.mdx
- src/components/Gallery/Image.tsx
- src/components/Gallery/__tests__/__snapshots__/Image.test.js.snap
- src/components/Message/MessageSimple.tsx
- src/components/Message/__tests__/MessageText.test.js
- src/components/Message/hooks/useReactionHandler.ts
- src/components/MessageInput/EditMessageForm.tsx
- src/components/MessageList/CustomNotification.tsx
- src/components/MessageList/__tests__/CustomNotification.test.js
- src/components/Reactions/ReactionSelector.tsx
- src/components/Reactions/ReactionsList.tsx
- src/components/Reactions/SimpleReactionsList.tsx
- src/components/Reactions/hooks/useProcessReactions.tsx
Add classes and markup to adapt to theme v2. Besides that the duplicate processing code from `ReactionList` and `SimpleReactionList` has been extracted to a single hook now shared by the both components.
Depends on https://github.com/GetStream/stream-chat-css/pull/150
Closes #1585
- with reaction selector
There is no distinction btw. own and other users' reactions.
- with reaction selector (same as for the `ReactionList`)
> Theming v2 message reactions react

- docusaurus/docs/React/message-components/ui-components.mdx
- src/components/Message/MessageStatus.tsx
- src/components/Message/__tests__/utils.test.js
- src/components/Message/utils.tsx
- src/mock-builders/__test__/translator.test.js
- src/mock-builders/index.js
- src/mock-builders/translator.js
- src/stories/message-status-readby-tooltip.stories.tsx
Allow the user to customize read-by tooltips based on user information.
I needed this in my project so that I could add information about users from another database to the readby tooltip.  Due to our architecture, user.name was email, and we wanted it to be first/last name from our own users table.
Adds an optional callback to MessageStatus that takes in a UserResponse and and returns a string of the custom tooltip text.  This is passed into getReadByTooltipText.  If it's null, it uses the original format.
I also added some testing around getReadByTooltipText, including a minimal test helper function to enable testing with i18n.
> feat(message-status): extendable user information in read-by tooltip

- package.json
- src/__tests__/__snapshots__/utils.test.js.snap
- src/__tests__/utils.test.js
- src/utils.tsx
- yarn.lock
With this PR, we want to fix one edge case with user mentions feaure in which a user could have their name set to their e-mail address. Before, the SDK would wrongly recognize the mention as an e-mail address and would wrap it into `<a href="mailto:..." />` tag.
The link detection process kicks in before user mentions are detected.
With this change, while detecting links we also consider whether the detected link matches an email identical to the mentioned user's name.
As part of this change, `mdast-util-find-and-replace` is updated to its latest version as the one we were previously using had a bug, and sometimes it could skip matching nodes.
> fix: detect mentions of users who have email as their name

- docusaurus/docs/React/custom-code-examples/override-submit-handler.mdx
- src/components/MessageInput/__tests__/MessageInput.test.js
- src/components/MessageInput/hooks/useSubmitHandler.ts
Allow users to pass custom message data when updating a message.
> feat: allow to send custom message data when editing a message

- .github/workflows/ci.yml
- .github/workflows/release.yml
- package.json
- rollup.config.js
- scripts/validate-cjs-bundle.cjs
Our recent upgrade of `mdast-util-find-and-replace` in #1698 broke our CommonJS bundle. This PR fixes that problem.
The `mdast-util-find-and-replace` package is now bundled within our CJS bundle. This will eliminate the conflict between ESM and CJS modules in NodeJS.
As part of this change, a very naive smoke test is introduced aiming for earlier detection of such incompatibilities.
> fix: include mdast-util-find-and-replace into our CJS bundle

- src/components/Channel/__tests__/Channel.test.js
- src/components/ChannelSearch/__tests__/SearchResults.test.js
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/MessageListNotifications.tsx
- src/components/MessageList/MessageNotification.tsx
- src/components/MessageList/ScrollToBottomButton.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/__tests__/ScrollToBottomButton.test.js
- src/components/MessageList/hooks/useNewMessageNotification.ts
- src/components/MessageList/hooks/useScrollLocationLogic.tsx
- src/mock-builders/event/messageNew.js
- src/mock-builders/event/messageUpdated.js
- src/mock-builders/index.js
- src/mock-builders/utils.js
Add missing logic to the `ScrollToBottomButton` component:
- show the component on scroll above a threshold, where the message list is not considered to be scrolled to the bottom. Show it even no new messages have arrived.
- show the counter of unread messages that is independent between the main message list and the thread message list
The calculation of unread messages differs depending on the button's location context. 
The unread counter is increased by 1 upon arrival of each `message.new` event.
The unread count is calculated as a difference between the `event.message.reply_count` and the last stored reply count value.
In the both contexts the counter is reset upon scrolling bellow the threshold that signals the container is scrolled to the bottom.
The component does not increase the …
> Theming v2 user testing  scroll to bottom buttom

- src/components/Attachment/Card.tsx
- src/components/Attachment/__tests__/Card.test.js
- src/components/Attachment/__tests__/__snapshots__/Card.test.js.snap
- src/components/Gallery/Image.tsx
- src/types/types.ts
Allow to view the whole attachment image if rendered in the `Card` attachment. This aligns the image display behavior. Also, this solves the problem of not being able to see the whole og image if the images does not match the ration 1:1.91.
The `Image` component was reused for rendering images in `Card`. This component conditionally renders modal with the displayed image.
> Theming v2 user testing - card image enlargement

- src/components/MessageInput/hooks/useAttachments.ts
- src/components/MessageInput/hooks/useImageUploads.ts
Fix image upload behaviour where preview URI does not get generated while the image is being uploaded.
Replace `FileReader` API with `URL.createObjectURL`.
> fix: replace FileReader with URL.createObjectURL

- e2e/jump-to-message.test.ts
- package.json
- src/components/Channel/Channel.tsx
- src/context/ChannelActionContext.tsx
- yarn.lock
The default limit of 25 can be too small for tall screens (or short items), causing additional queryChannel request and potential scroll glitches.
Introduce an additional parameter for jumpToMessage, defaulting it to 100 (default value for pagination).
> feat: increase and support overriding jump to message limit

- src/components/AutoCompleteTextarea/Textarea.jsx
Hitting enter in Korean text mode entry submits twice. This PR fixes it.
I've patched this by ignoring compositing events (left links in the comments for reference). 
Long term, we should not handle keydown but keypress (considered a better practice). But I am not sure about the implications of such change.
> fix: prevent double submissions in korean

- src/components/MessageInput/__tests__/MessageInput.test.js
- src/context/DefaultEmoji.ts
- src/context/DefaultEmojiPicker.ts
- src/context/EmojiContext.tsx
Vite development mode is broken for the latest version of the SDK (when installed from the NPM) when using "custom" object (with `default` property) dynamic imports. I've re-exported the `emoji-mart` modules based on this comment of one [somewhat unrelated issue on GH](https://github.com/fuse-box/fuse-box/issues/1646#issuecomment-666468319) and that seems to fix the issue. ~Used [`/dist-es` instead of `/dist`](https://github.com/missive/emoji-mart/tree/v3.0.1#optimizing-for-production) which comes with the benefit of sligtly smaller bundle size.~
```ts
// this approach (as suggested by the aforementioned comment) increases bundle size
// so I chose different approach 
export { NimblePicker as default } from 'emoji-mart';
```
> fix(Vite): add emoji-mart (emoji, picker) re-export

- src/components/Message/MessageStatus.tsx
- src/components/Reactions/ReactionsList.tsx
- src/components/Reactions/hooks/useProcessReactions.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/hooks/index.ts
- src/components/Tooltip/hooks/useEnterLeaveHandlers.ts
Replace current tooltip components with `PopperTooltip` component which utilises package [`PopperJS`](https://popper.js.org/react-popper/v2/). This PR relies on [CSS updates](https://github.com/GetStream/stream-chat-css/pull/165).
(viewport-aware, adjusts position by itself for better visibility)
> feat(ThemingV2): PopperTooltip component

- src/components/Channel/Channel.tsx
This change fixes a production-only issue where rapid jumping between messages created a race condition + exception. 
@szuperaz - more of an FYI if you copied this mistake from me :(.
> fix: avoid race condition crash in jumping

- src/components/MessageInput/icons.tsx
Remove React's `useId` which breaks compatibility for older versions of React and replace it with memoized `nanoid` "equivalent".
> fix: remove `useId` from `LoadingIndicatorIcon`

- src/components/MessageInput/__tests__/AttachmentPreviewList.test.js
- src/components/MessageInput/__tests__/__snapshots__/AttachmentPreviewList.test.js.snap
Add mock of `nanoid` to prevent snapshots from changing every time.
> test: add nanoid mock to AttachmentPreviewList

- src/components/AutoCompleteTextarea/Textarea.jsx
Prevents caret movement of the textarea component when the suggestion list is rendered (actively selecting from the list). 
Fixes: #1731
> fix(Textarea): prevent caret movement on suggestion list item select

- src/components/Channel/Channel.tsx
- src/components/Channel/__tests__/__snapshots__/Channel.test.js.snap
- src/components/Channel/hooks/useChannelContainerClasses.ts
- src/components/ChannelList/ChannelList.tsx
- src/components/Chat/Chat.tsx
- src/components/MessageInput/MessageInputSmall.tsx
- src/components/MessageInput/UploadsPreview.tsx
- src/components/MessageList/__tests__/__snapshots__/VirtualizedMessageList.test.js.snap
- src/context/ChatContext.tsx
Remove deprecation notice for Chat's `theme` property and fix order of class names in `ChannelList` which sets the theming variables.
> fix(ChannelList): update class names order for theming variables

- src/components/Attachment/Card.tsx
- src/components/Attachment/__tests__/Card.test.js
- src/components/Attachment/__tests__/__snapshots__/Card.test.js.snap
Allow to play the video directly in the `Card` with video asset link with css theme version 1. After the release v10.0.0 the video widget was replaced with an image. Click on the image lead to opening of a new tab with the video link.
It was necessary to check the attachment type in `Card` component using theme v1.
> fix: play video in attachment card theme v1

- docusaurus/docs/React/custom-code-examples/channel-search.mdx
- docusaurus/docs/React/utility-components/channel-search.mdx
- src/components/ChannelSearch/SearchBar.tsx
- src/components/ChannelSearch/__tests__/SearchBar.test.js
- src/components/ChannelSearch/index.ts
Allow users to pass a callback invoked once the app menu item is selected. The default `onSelect` callback closes the `AppMenu` dropdown.
> feat: provide close callback to app menu

- src/components/ChannelList/hooks/usePaginatedChannels.ts
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/hooks/useEnrichedMessages.ts
- src/components/Reactions/hooks/useProcessReactions.tsx
Avoid unnecessary re-renders caused by regenerating a new array of message group style keys (`Object.keys()` was called directly in the hook dependency array).
> fix(VirtualizedMessageList): use memoized values as hook dependencies directly

- src/components/Attachment/Attachment.tsx
- src/components/Attachment/utils.tsx
Backports attachment [fix](https://github.com/GetStream/stream-chat-react/pull/1697/commits/34082a4600281a77c8792a1aad8a3c75b7bcd3c5) from #1697.
> fix(Attachment): reduce the number of re-renders

- src/components/ChannelPreview/hooks/index.ts
- src/components/ChannelPreview/index.ts
- src/components/MessageInput/index.ts
- src/components/MessageList/Center.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/index.ts
Export recently added components that were not exported from the SDK (`AttachmentPreviewList`, `useChannelPreviewHook`).
> fix: export all necessary components

- src/components/Message/__tests__/Message.test.js
- src/components/Message/__tests__/MessageOptions.test.js
- src/components/Message/hooks/__tests__/useUserRole.test.js
- src/components/Message/hooks/useUserRole.ts
Enable permission configuration for message flagging, stop inferring `mute, react, reply` permissions from `channel.config`.
fixes #1806
> fix: replace use of channel config with channel.own_capabilities to derive permission flags

- src/components/Attachment/AttachmentContainer.tsx
- src/components/Attachment/attachment-sizing.tsx
Add `linkify.test` check before any `URL` instantiation to prevent errors due to malformed links.
> fix: add linkify.test check before any URL instantiation

- src/components/MessageInput/hooks/useUserTrigger.ts
Sort configuration can be an array of objects or an object. This should be checked when merging the custom `mentionQueryParams.sort` value into the resulting `client.queryUsers` call params.
fixes #1862
> fix: merge mentionQueryParams.sort configuration correctly

- docusaurus/docs/React/guides/customization/channel-search.mdx
Improve the customSearchFunction example in [docs](https://getstream.io/chat/docs/sdk/react/guides/customization/channel_search/#the-searchfunction-prop) is not correct.
- Use of hook (`useChatContext`) within regular async function (no hook or component).
- `chatClient` is not defined.
- setResultsOpen doesn't exist.
Errors fixed:
- React Hook "useChatContext" is called in function "customSearchFunction" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use"
- `chatClient` doesn’t exist ➜ should be client.
- Provided `client` as prop instead of the use of a hook within a regular function. 
- Re-used `e.target.value` assigned to var ➜ improves re-usability.
> customSearchFunction example in docs is not correct

- docusaurus/docs/React/components/utility-components/channel-search.mdx
- src/components/ChannelSearch/hooks/useChannelSearch.ts
- src/components/MessageInput/hooks/useUserTrigger.ts
I want to be able to control `mentionQueryParams` by myself and have access to input query value
Just update `mentionQueryParams`, now it accepts function
> feat(MessageInput): extend mentionQueryParams to accept `filters` function 

- package.json
- src/utils.tsx
- yarn.lock
Package `linkifyjs` uses plugins which are registered globally ([like this one - mentions](https://linkify.js.org/docs/plugin-mention.html)), so when integrators use compatible `linkifyjs` with custom compatible plugins for other purposes, it tampers with our implementation - in this case it broke mentions implementation which is handled by `ReactMarkdown` instead.
Fixes: #1851
> fix(renderText): specify linkifyjs types to look for (`email` and `url`)

- src/components/Window/Window.tsx
- src/components/Window/__tests__/Window.test.js
Enable the `Window` component's `thread` prop, that was previously ignored. 
fixes #1917
> fix: reflect thread prop in Window component

- src/components/Thread/Thread.tsx
Do not required key `message` in `ThreadProps.additionalParentMessageProps`
> fix: make all ThreadProps.additionalParentMessageProps keys optional

- docusaurus/docs/React/components/contexts/channel-action-context.mdx
- docusaurus/docs/React/guides/customization/thread-header.mdx
- src/components/Channel/Channel.tsx
- src/components/Thread/ThreadHeader.tsx
- src/context/ChannelActionContext.tsx
Allow users to invoke `openThread` and `closeThread` in effects or outside Event listener context.
fixes #1917
> refactor: make openThread and closeThread usable outside event listener context

- package.json
- yarn.lock
It seems that react-player@2.11.1 has introduced a bug as reported in #1925. Therefore we are pinning to a working version of react-player@2.10.1.
> chore: pin the react-player version to 2.10.1

- src/context/ChannelActionContext.tsx
Adjust openThread definition in order the #1923 can work.
fix #1917
> fix: make event optional for openThread in ChannelActionContext

- .github/workflows/release.yml
Authenticate the release on behalf of the user, who pushed the changes to master.
See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
> chore: use GITHUB_TOKEN to release

- src/components/Attachment/Attachment.tsx
- src/components/Attachment/AttachmentContainer.tsx
- src/components/Attachment/UnsupportedAttachment.tsx
- src/components/Attachment/index.ts
Introduces `UnsupportedAttachment` component to handle unsupported attachment types.
This component is disabled by default, enable by passing `UnsupportedAttachment` component to `Attachment`'s `UnsupportedAttachment` property:
```tsx
import { Attachment, UnsupportedAttachment } from 'stream-chat-react';
const CustomAttachment = (props) => <Attachment {...props} UnsupportedAttachment={UnsupportedAttachment} />
/* ... */
<Channel Attachment={CustomAttachment} >
/* ... */
</Channel>
```
> feat(Attachments): introduce `UnsupportedAttachment` component

- src/components/Attachment/Attachment.tsx
- src/components/Gallery/Gallery.tsx
- src/components/Gallery/__tests__/__snapshots__/Gallery.test.js.snap
Premature sanitization of attachment URL's (of image types) caused `image_url` to be set to `about:blank` which when defined is prefered source for the image causing images to not render at all:
```js
// "about:blank" ↴
image.previewUrl || image.image_url || image.thumb_url
```
- leave sanitization to `Image` and `Gallery` components
> fix(Attachment): sanitization of image sources

- .github/workflows/ci.yml
On 30 April 2023, extended support for Node 14 LTS will end.
> build(ci): remove Node v14, add v18

- src/components/Channel/Channel.tsx
Discussion: https://getstream.slack.com/archives/C04L46T90HK/p1678217984091969?thread_ts=1677866241.515559&cid=C04L46T90HK
Fixes following bug:
- Use `Channel` component without `ChannelList` and Pass the `channel` as prop to Channel component without instantiating it. Now send a message to that channel from some other user and check that `markRead` call never happens
```tsx
const App = () => {
const [ isReady, setIsReady ] = React.useState(false);
const [ channel, setChannel ] = React.useState<StreamChatChannel>();
React.useEffect(() => {
const init = async () => {
await chatClient.connectUser({ id: userId }, userToken);
const _channel = chatClient.channel('messaging', 'sample-app-channel-999');
setChannel(_channel);
setIsReady(true);
};
init();
}, []);
if (!isReady) return …
```
> fix: update event handler upon channel config update

- src/components/MessageList/__tests__/VirtualizedMessageList.test.js
- src/components/MessageList/hooks/usePrependMessagesCount.ts
This fix solves an edge case situation, when a user starts to send messages very quickly into an empty channel displaying messages with VirtualizedMessageList. VirtualizedMessageList calculates number of messages prepended in order it loads more messages from the history. Number of prepended messages was calculated incorrectly, when 2+ messages were sent in a range of few milliseconds (crazy typing and pressing Enter key). The reason for this situation to occur is that we use optimistic UI updates - we render message in the message list even before it was sent to & response received from the API. That leads to following:
1. sending message A that is committed to the channel state flagged with `status: "sending"` before the actual response is received from the API
2. sending message B …
> fix: do not increase count of prepended VirtualizedMessageList messages of status "sending" or "failed"

- src/components/Channel/Channel.tsx
Fix #1983 
Upon `user.deleted` event the entire channel state is re-fetched to reflect the state on the back-end.
> fix: update channel state on user.deleted event

- src/components/ChannelList/utils.ts
Prevent duplicate simultaneous requests querying channel data, if multiple events that trigger querying data for a channel are delivered to the client. Example of such events are `message.new` and `notification.added_to_channel`. They are received when user sends a message to a newly created channel (for example a direct message). The queries are triggered by the hooks inside the `ChannelList` component.
Keep a map of promises representing the query channel HTTP requests being in flight and prevent retriggering that request for a given channel and only await till the query finishes..
> fix: prevent duplicate simultaneous query channel quests

- src/components/AutoCompleteTextarea/Textarea.jsx
Prevent overriding internal event handler of Textarea component by event handlers provided via `additionalTextareaProps` prop.
> fix: prevent overriding event handlers in MessageInput's Textarea component

- docusaurus/docs/React/components/message-input-components/message-input.mdx
- docusaurus/docs/React/guides/customization/adding-notification.mdx
- docusaurus/docs/React/guides/customization/persist-input-text-in-local-storage.mdx
- src/components/MessageInput/MessageInput.tsx
- src/components/MessageInput/__tests__/MessageInput.test.js
- src/components/MessageInput/hooks/useMessageInputState.ts
Allow users to generate the default value for `MessageInput` components instead of providing static `defaultValue` through `additionalTextareaProps`. This circumvents the limitation posed by passing `defaultValue` to `MessageInput` in `Thread` component. If the default value has to be generated / retrieved, it cannot be set  with the first render of the `Thread` component as the thread is not yet opened / known and the original `defaultValue` passed to `Thread` would not get overwritten once the `thread` value is set in `ChatContext`.
> feat: allow to retrieve the default message input value dynamically

- src/components/AutoCompleteTextarea/Textarea.jsx
- src/utils/browsers.ts
Fix bug, when clicking item in message input's autocomplete just closes the dropdown without selecting the item.
The blur event's relatedTarget value in Safari is incorrect when clicking on autocomplete item. We cannot therefore decide, whether to close or not the autocomplete dropdown. This fix introduces change that will lead to ignoring the textarea blur event in Safari. That means that user will be able to close the autocomplete dropdown only by selecting the item.
> fix: do not try close message input's autocomplete dropdown on textarea blur

- docusaurus/docs/React/guides/theming/translations.mdx
- src/i18n/Streami18n.ts
1. Fix the type declaration of `dayjsLocaleConfigForLanguage` object passed to `Streami18n` constructor options.
2. Add missing documentation on how to customize the datetime locale translations
> fix: extend i18n datetime locale config type

- docusaurus/docs/React/components/contexts/chat-context.mdx
- docusaurus/docs/React/components/contexts/component-context.mdx
- docusaurus/docs/React/components/core-components/channel.mdx
- docusaurus/docs/React/components/core-components/thread.mdx
- docusaurus/docs/React/components/message-components/attachment.mdx
- docusaurus/docs/React/components/utility-components/channel-search.mdx
- docusaurus/docs/React/guides/theming/css-and-theming.mdx
- docusaurus/docs/React/release-guides/upgrade-to-v10.mdx
[The docs reshuffling PR](https://github.com/GetStream/stream-chat-react/pull/1842) lead to introduction of incorrect linking to css theming docs. This PR is introduction corrections to those changes.
> docs: fix links to the theming documentation

- src/components/ChannelSearch/hooks/useChannelSearch.ts
Fix bug of click listener not being updated with the latest channel search state data.
> fix: add missing effect and callback dependencies in useChannelSearch hooks

- src/components/Message/QuotedMessage.tsx
- src/components/Message/__tests__/QuotedMessage.test.js
Keep the consistency between the original and quoting message contents when the original message is deleted. That means that when a message that is quoted somewhere else, is deleted, then the quoting message as well as original message should display string "This message was deleted...". Before this fix, only the original message displayed the deletion string upon receiving `message.deleted` event, whereas the quoting message kept the original text until new channels query is performed.
Was upon `message.deleted`:
Should be upon `message.deleted`:
> fix: prevent showing original text of deleted quoted message

- src/components/MessageInput/hooks/__tests__/useCooldownTimer.test.js
- src/components/MessageInput/hooks/useCooldownTimer.tsx
Adapt the cooldown timer enablement to the latest bug fix on the backend:
The `'slow-mode'` own capability was replaced by `'skip-slow-mode'`. This capability should only be used to determine if the user can skip cooldown mode and not to determine if the channel has cooldown enabled. The `channel.own_capabilities` array will contain capability `'skip-slow-mode'` if a user is assigned a role that has `skip-channel-cooldown` permission.
Cooldown mode enablement is signaled by the presence of `channel.cooldown` value (num of seconds).
When cooldown mode is enabled a user can send a message only if:
1.  in the cooldown period if `channel.own_capabilities` includes `'skip-slow-mode'`
2. the time elapsed since the last message sent is > `channel.cooldown`
3. no previous message was sent by the …
> fix: cooldown timer

- src/components/ChannelSearch/hooks/useChannelSearch.ts
Fixes an issue where `clearSearchOnClickOutside` would be ignored when the navigation in mobile view is open.
> fix: prevent ignoring the clearSearchOnClickOutside search param on mobile

- package.json
- yarn.lock
Upgrade and pin the version of the `react-image-gallery` package due to breaking change released as minor version update. 
Goes hand in hand with: https://github.com/GetStream/stream-chat-css/pull/231
> chore(deps): upgrade and pin version of the `react-image-gallery`

- src/components/ChannelSearch/ChannelSearch.tsx
- src/components/ChannelSearch/__tests__/ChannelSearch.test.js
Fix the bug in channel search results list to make it scrollable. If the channel search result list overflew the parent, it was not possible to scroll the list.
This fix depends on https://github.com/GetStream/stream-chat-css/pull/232
> fix: enable search results scrolling

- src/components/ChannelSearch/ChannelSearch.tsx
- src/components/ChannelSearch/__tests__/ChannelSearch.test.js
Avoid conflicts with integrators' custom rules attached to `inline` class.
depends on https://github.com/GetStream/stream-chat-css/pull/234
fixes: https://github.com/GetStream/stream-chat-react/pull/2041#issuecomment-1635304125
> fix: namespace the ChannelSearch's root element "inline" and "popup" classes

- docusaurus/docs/React/components/core-components/virtualized-list.mdx
- src/components/MessageList/VirtualizedMessageList.tsx
Enable rendering of read receipts inside `VirtualizedMessageList`. This feature mirrors the read receipt behavior in `MessageList` component.
Integrators can now use a new `VirtualizedMessageList` prop `returnAllReadData`. This again mirrors the `MessageList` prop. 
close #2074 
The VML now starts to memoize the mapping of what other users have read which messages send by the local user. The logic is mirrored from `MessageList`.
> feat: show read receipts in VirtualizedMessageList

- src/components/Message/__tests__/MessageSimple.test.js
- src/components/MessageList/utils.ts
The message read receipt will be rendered even though the last message update has not been read.
fix: #2078
> fix: keep showing message read receipt once read

- package.json
- rollup.config.js
- tsconfig.json
- yarn.lock
- remove CSS mappings from the build as they point to non-existing files within the `dist` folder
- refresh `tsconfig.json` (feel free to commit your changes)
- move `tslib` and actually use it
(I feel like we should also do something about all the Webpack packages and do some ESLint cleaning - it's way too strict)
Closes: #1540
Closes: #1827
> chore(deps): general build audit & tslib

- docusaurus/docs/React/components/contexts/message-context.mdx
- docusaurus/docs/React/components/message-components/message-ui.mdx
- docusaurus/docs/React/guides/theming/message-ui.mdx
- docusaurus/docs/React/guides/theming/reactions.mdx
- src/components/Message/MessageSimple.tsx
- src/components/Message/__tests__/Message.test.js
- src/components/Message/__tests__/MessageOptions.test.js
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/__tests__/MessageText.test.js
- src/components/Message/__tests__/QuotedMessage.test.js
- src/components/Message/hooks/__tests__/useReactionHandler.test.js
- src/components/Message/hooks/useReactionHandler.ts
- src/context/MessageContext.tsx
The PR introduces two changes:
1. allow to send reactions to frozen channel for users who have `UseFrozenChannel` permission
2. the prop / value of `isReactionEnabled` should be used to determine permission to send reactions only. Not to view them. This is to achieve parity with other SDKs that use only channel's own capability `send-reaction` to determine, whether reactions can be send. Angular neither RN SDK have notion of enabling reactions (meaning read + write). This seems like a legacy code from times, when `channelConfig.reactions` was used to control reactions. This change means that existing reactions will be always visible in the default implementation of `MessageSimple`. The integrators however can still override the prop on the `MessageSimple` level.
> fix: enable sending reactions to frozen channel with UseFrozenChannel permission

- docusaurus/docs/React/guides/theming/translations.mdx
- package.json
- src/context/TranslationContext.tsx
- src/i18n/Streami18n.ts
- src/i18n/__tests__/Streami18n.test.js
- yarn.lock
Allow integrators to display datetimes in timezone different than the machine's timezone.
> feat: add timezone support to datetime parsing

- src/components/MessageInput/CooldownTimer.tsx
- src/components/MessageInput/hooks/__tests__/useCooldownTimer.test.js
- src/components/MessageInput/hooks/useCooldownTimer.tsx
Account for the possibility that the current local time generated by machine can be in the past compared to the time of the last of own message creation. This lead to showing `Slow Mode ON` placeholder in `MessageInput` even though cooldown was disabled on back-end. Negative value was considered truthy and so the placeholder was shown.
> fix: adjust cooldown interval calculation for messages coming from future

- docusaurus/docs/React/components/utility-components/channel-preview-ui.mdx
- docusaurus/docs/React/guides/customization/channel-list-preview.mdx
- src/components/ChannelPreview/ChannelPreview.tsx
- src/components/ChannelPreview/ChannelPreviewMessenger.tsx
- src/components/ChannelPreview/hooks/__tests__/useMessageDeliveryStatus.test.js
- src/components/ChannelPreview/hooks/index.ts
- src/components/ChannelPreview/hooks/useMessageDeliveryStatus.ts
- src/mock-builders/api/getOrCreateChannel.js
- src/mock-builders/event/index.js
Provide delivery status calculated value to for custom `ChannelPreview` UI component. The default UI component `ChannelPreviewMessenger` does not support the message delivery status visuals.
The `ChannelPreview` component does not have access to the information about a message being sent and not delivered yet and so can infer only the following two delivery states :
1. `DELIVERED`
2. `READ`
The states are exposed to the SDK users in an enum:
```tsx
export enum MessageDeliveryStatus {
DELIVERED = 'delivered',
READ = 'read',
}
```
The hook that performs that calculations *`useMessageDeliveryStatus`* is not exported for the SDK users to protect the SDK internals.
- The delivery status is calculated only for the last message in the message set
- The delivery status is calculated only for own …
> feat: add messageDeliveryStatus prop to ChannelListPreview

- docusaurus/docs/React/components/utility-components/channel-search.mdx
- docusaurus/docs/React/guides/customization/channel-search.mdx
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/ChannelSearch/__tests__/ChannelSearch.test.js
- src/components/ChannelSearch/__tests__/__snapshots__/ChannelSearch.test.js.snap
- src/components/ChannelSearch/hooks/useChannelSearch.ts
- allow users to configure the debounce interval that would delay triggering of search requests to the backend
- change the search query delay method from throttle to debounce
- discard search responses when those are not relevant anymore (the input has been cleared)
> feat: add search debounce interval configuration param

- docusaurus/docs/React/components/core-components/channel-list.mdx
- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/ChannelList/hooks/usePaginatedChannels.ts
Allow to load the most recent updates to the ChannelList after the internet connection loss. The `StreamChat` client's recovery mechanism has the following shortcomings:
- re-queries only the channels that have already been loaded into the UI
-  does not throttle the channel list queries.
On the other side, the SDK's recovery mechanism just reloads the channel list based on the filters, sort and options parameters originally provided to `ChannelList` through props.
This is an opt-in feature that has to be enabled as described in the documentation.
Currently it is not possible to load both the latest updates that would include new channels at the top and the originally loaded channels due to the fact that after re-querying the originally loaded channels we loose track of the next page for …
> feat: allow complete channel list throttled reload on internet connection recovery

- .github/workflows/release.yml
- adjust job `if` conditions
- change `release` user to [Stream CI Bot](https://github.com/stream-ci-bot)
> chore: adjust release workflow conditions

- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/Chat/hooks/useChannelsQueryState.ts
The `EmptyStateIndicator` was flashing before the first channels query used to be triggered. This is a strange UX. 
This was happening because before the first query there were 0 channels loaded and `channelsQueryState.queryInProgress` was initialized with `null` what translates to valid state of channels query returning 0 channels.
This PR introduces a new state / value for `ChatContext.channelsQueryState.queryInProgress` and that is `'uninitialized'`. We cannot use `'reload'` as the first value for `queryInProgress` state , because the `Channel` component also relies on this status. If the `Channel` was not rendered with `ChannelList` the state would never transition to `null` (done inside  `ChannelList`) thus never rendering the `Channel` contents.
With this PR, the `'uninitialized'` …
> fix: prevent flashing EmptyStateIndicator in ChannelList before the first channels page is loaded

- .releaserc.json
- package.json
- yarn.lock
Add `conventional-changelog-conventionalcommits` package and adjust `.releaserc.json` so that `chore(deps)` & `refactor` type releases generate notes to the `CHANGELOG.md`.
This helped: https://github.com/semantic-release/commit-analyzer/issues/233
> chore: generate release notes for chore and refactor types

- docusaurus/docs/React/components/core-components/chat.mdx
- docusaurus/docs/React/release-guides/emoji-picker-v11.mdx
- package.json
- src/components/Chat/Chat.tsx
- yarn.lock
This PR bumps our CSS package to the latest RC version which separates `emoji-mart` related styling rules and `emoji-replacement` (styling rules for the `Chat.useImageFlagEmojisOnWindows` property) from the main `index.css` to reduce final bundle size for integrators who do not wish to use these stylesheets.
Fixes: #2116
NOTE: This PR is part of the `v11` release, it should should be merged only after `v4` of `stream-chat-css` lands.
> chore(deps): bump @stream-io/stream-chat-css to v4-rc

- docusaurus/docs/React/components/contexts/message-list-context.mdx
- docusaurus/docs/React/components/contexts/translation-context.mdx
- docusaurus/docs/React/components/contexts/typing-context.mdx
- src/components/MessageList/MessageList.tsx
- src/context/MessageListContext.tsx
- src/context/index.ts
Expose API relevant to `MessageList` children. At the moment it exposes function `scrollToBottom` and reference to the message list's root element needed to control the scroll-to-bottom logic.
> feat: introduce MessageListContext

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- README.md
Isolate flaky e2e tests in a separate workflow.
> chore: separate e2e workflow file

- package.json
- src/components/MessageList/CustomNotification.tsx
- src/components/MessageList/__tests__/CustomNotification.test.js
- yarn.lock
Depends on https://github.com/GetStream/stream-chat-css/pull/249
> fix: lift notifications above modal overlay

- src/components/Channel/Channel.tsx
- src/components/Channel/__tests__/Channel.test.js
- src/components/Channel/channelState.ts
- src/components/InfiniteScrollPaginator/InfiniteScroll.tsx
- src/components/MessageList/utils.ts
- src/components/Thread/Thread.tsx
The logic to determine whether there are more messages to be loaded from the API was flawed because it relied on the expectation that the first page size will be always constant determined by the SDK. But once the integrators perform the initial channel query outside the `Channel` component with custom query options different from the SDK constant default 
or they specify this through `Channel` prop `channelQueryOptions`, then the custom value has to be taken into the consideration. Otherwise if the custom first page size was smaller then the default, the next page would not be loaded.
This PR brings a small optimization when the `hasMore` flag is set on the `Channel` component state immediately after the first query resp. also for already initialized channel in the layout effect.
> fix: calculate pagination stop from custom channel query message limit

- src/components/MessageInput/index.ts
- src/components/MessageList/index.ts
Primary goal is to export component props types as they are needed to override the default components.
> feat: export MessageListNotifications and LinkPreviewList components and component props

- docusaurus/docs/React/_docusaurus-components/GHComponentLink.jsx
- docusaurus/docs/React/components/message-components/reactions.mdx
- docusaurus/docs/React/guides/theming/reactions.mdx
- docusaurus/docs/React/release-guides/new-reactions.mdx
- docusaurus/docs/React/release-guides/reactions-v11.mdx
- src/components/Channel/Channel.tsx
- src/components/Channel/__tests__/Channel.test.js
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/__tests__/MessageText.test.js
- src/components/Reactions/ReactionSelector.tsx
- src/components/Reactions/ReactionsList.tsx
- src/components/Reactions/SimpleReactionsList.tsx
- src/components/Reactions/SpriteImage.tsx
- src/components/Reactions/StreamEmoji.tsx
- src/components/Reactions/__tests__/ReactionSelector.test.js
- src/components/Reactions/__tests__/ReactionsList.test.js
- src/components/Reactions/__tests__/SimpleReactionsList.test.js
- src/components/Reactions/__tests__/__snapshots__/SimpleReactionsList.test.js.snap
- src/components/Reactions/hooks/useProcessReactions.tsx
- src/components/Reactions/index.ts
- src/components/Reactions/reactionOptions.tsx
- src/components/Reactions/utils/utils.tsx
- src/context/ComponentContext.tsx
- src/context/EmojiContext.tsx
- src/types/types.ts
BREAKING CHANGE: `reactionOptions` signature has changed, see release guide for more information
Refactor and fix the way reactions work, introduce new way of customizing with better DX.
Fixes: #1935
Closes: #1637
Closes: #1437
Closes: #2159
Closes: https://github.com/GetStream/stream-chat-react-native/issues/2023
- ditch EmojiMart implementation, use native/sprite-sheet solution
> fix(emoji-mart): new reactions 

- .github/workflows/release.yml
1. Remove docs release job
2. Allow to run release job for branches which name starts with `'release-v'`.
> chore(ci): remove docs release

- docusaurus/docs/React/components/contexts/component-context.mdx
- docusaurus/docs/React/components/utility-components/base-image.mdx
- src/components/Gallery/BaseImage.tsx
- src/components/Gallery/ModalGallery.tsx
- src/components/Gallery/__tests__/BaseImage.test.js
- src/components/MessageInput/AttachmentPreviewList.tsx
- src/components/MessageInput/__tests__/AttachmentPreviewList.test.js
- src/components/MessageInput/__tests__/__snapshots__/AttachmentPreviewList.test.js.snap
- src/components/MessageInput/index.ts
- src/i18n/de.json
- src/i18n/en.json
- src/i18n/es.json
- src/i18n/fr.json
- src/i18n/hi.json
- src/i18n/it.json
- src/i18n/ja.json
- src/i18n/ko.json
- src/i18n/nl.json
- src/i18n/pt.json
- src/i18n/ru.json
- src/i18n/tr.json
A follow up to #2183. Just in case prevent any message height changes due to switching between the `<img/>` element and a fallback component in case of image load error.
> feat: render BaseImage image fallback within the same img element

- docusaurus/docs/React/components/contexts/chat-context.mdx
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/ChannelList/hooks/usePaginatedChannels.ts
- src/components/Chat/Chat.tsx
- src/components/Chat/hooks/useChannelsQueryState.ts
- src/components/Chat/hooks/useChat.ts
- src/components/Chat/hooks/useCreateChatContext.ts
- src/context/ChatContext.tsx
Moving the state away from the `ChannelList` prevents integrators from having multiple `ChannelList` components rendered inside `Chat`. The `setChannels` function and `channels` state will be exposed in the following PR.
> fix: revert "feat: expose channels state on chat level (#2161)"

- docusaurus/docs/React/components/contexts/channel-list-context.mdx
- docusaurus/docs/React/components/contexts/chat-context.mdx
- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/ChannelList/hooks/usePaginatedChannels.ts
- src/components/Chat/Chat.tsx
- src/components/Chat/hooks/useChannelsQueryState.ts
- src/components/Chat/hooks/useChat.ts
- src/components/Chat/hooks/useCreateChatContext.ts
- src/context/ChannelListContext.tsx
- src/context/ChatContext.tsx
- src/context/index.ts
Allow to control and access the `ChannelList` state  with `channels` and `setChannels`.
> feat: add channel list context

- src/components/MessageList/hooks/VirtualizedMessageList/usePrependMessagesCount.ts
- src/components/MessageList/hooks/__tests__/usePrependMessagesCount.test.js
This PR handles edge case situation when message order is swapped due to message `status` change. This happens when:
1. users submit new messages `in high cadence` 
2. into an `empty channel` 
3. having VirtualizedMessageList` prop set `disableDateSeparator={false}`  
When submitting messages in high cadence, the message list displays multiple messages in status `'sending'`, then gradually the messages are updated over WS events, where the messages have `created_at` timestamp set by the API (which comes later then the original timestamp). This leads to message order swap. In this case we fall back to the prepend count calculated in the previous re-render as the current re-render is not caused due to change of prepended items count but due to the swap.
This edge case situation does not …
> fix(VML): prevent recalculation of prepended items when messages are swapped due to status change

- src/components/MessageInput/CooldownTimer.tsx
- src/components/MessageInput/__tests__/CooldownTimer.test.js
- src/components/MessageInput/__tests__/MessageInput.test.js
- src/components/MessageInput/hooks/__tests__/useCooldownTimer.test.js
- src/components/MessageInput/hooks/useCooldownTimer.tsx
Schedule the cooldown removal in `useCooldownTimer` hook so that all the descendants can update their UI.
Properly update CooldownTimer state with setTimeout to avoid freezing of the countdown during higher message rate influx.
> fix: schedule cooldown removal from useCooldownTimer hook instead of CooldownTimer

- src/components/AutoCompleteTextarea/Textarea.jsx
- src/components/ChatAutoComplete/__tests__/ChatAutocomplete.test.js
Disables `SuggestionList` component when text composition (with Korean and Japanese keyboard inputs) is active to prevent text duplication on submission.　
During text composition:
After text composition:
> fix: disable SuggestionList during text composition

- src/components/MessageInput/icons.tsx
Add viewBox to svg to enable changing svg size with css styles
Add viewBox to svg components to enable changing svg size with css.
Added viewBox prop.
> fix: update MessageInput icons to include viewBox property

- docusaurus/docs/React/components/core-components/channel-list.mdx
- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/ChannelList/hooks/useMessageNewListener.ts
Having custom handler allows integrators to ignore `message.new` events if system message is received when removing a user from a channel. That way the channel is not re-queried again. 
The behavior with receiving a new message into a channel from which a user is removed is to be adjusted by the BE team.
> feat: handle message.new events in ChannelList with custom handler onMessageNewHandler

- package.json
- yarn.lock
Pin version of `react-markdown` package to ensure our SDK is still somewhat compatible with older versions of React (`<v18`) as the newest version of the said package requires minimal version of React to be at least `v18` but does not necessarily use any new APIs that aren't available in the older versions.
> chore(deps): pin react-markdown to v9.0.1

- src/components/MessageActions/MessageActions.tsx
- src/components/MessageActions/MessageActionsBox.tsx
- src/components/MessageActions/__tests__/MessageActions.test.js
- src/components/MessageActions/hooks/index.ts
- src/components/MessageActions/hooks/useMessageActionsBoxPopper.ts
Message actions box is currently relatively positioned inside MessageList, which means it sometimes gets clipped by MessageList's boundaries.
This PR implements proper positioning for the actions box, preventing it from being clipped in (almost) every case.
`stream-chat-react` already uses `react-popper` for tooltips, so it made sense to reuse it for the actions box as well.
My initial plan was to render the actions box into a portal and position it using popper, but using a portal turned out to be unnecessary: with the positioning strategies that popper implements, the action box is never clipped by it's parent container.
See also: https://github.com/GetStream/stream-chat-css/pull/260
Previously:
After the fixes:
The actions box automatically flips if it's close to the clipping boundary:
> fix: use popper to properly position message actions box

- src/components/MessageActions/MessageActions.tsx
- src/components/MessageActions/MessageActionsBox.tsx
- src/components/MessageActions/__tests__/MessageActions.test.js
In #2241 we've added a new positioning wrapper for `MessageActionsBox`. That was not the greatest idea, since adding new wrappers can break custom CSS for the users.
Having a wrapper is not necessary in this case anyway. This PR implements the same positioning as #2241, but without additional wrappers.
> fix: get rid of positioning wrapper for message actions box

- src/components/Channel/Channel.tsx
- src/components/Channel/__tests__/Channel.test.js
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/utils.ts
A bug that would prevent users from loading older messages within message lists if they paginated on channel B, switched to channel A and then back to channel B and tried paginating again.
Moved from `startReached` to `atTopStateChange` and from `endReached` to `atBottomStateChange` callbacks for pagination as `startReached` [is distinct](https://github.com/petyosi/react-virtuoso/blob/efdf50b8c4ee18e1c9d2fa4866e47ae9fd64cae1/src/listStateSystem.ts#L386) and called only once per set of data (I assume, not sure why as scrolling back down should ideally reset it) - but if you were to hit the top - and the data load would fail for some reason - scrolling a bit down and back up would not trigger the data load again.
This was one of my ways to try to resolve the original problem before I was …
> fix: hasMore limitations

- docusaurus/docs/React/components/core-components/channel-list.mdx
- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/ChannelList/hooks/usePaginatedChannels.ts
- src/components/Chat/hooks/useChannelsQueryState.ts
Create a new `ChannelList` prop `customQueryChannels` that allows integrators to control the channels pagination queries. The integrators have to generate own `filters`, `sort` and `options` parameters.
> feat: allow to pass custom function customQueryChannels to ChannelList to query channels

- src/components/MessageList/MessageList.tsx
- src/components/MessageList/hooks/MessageList/useScrollLocationLogic.tsx
- src/components/MessageList/hooks/MessageList/useUnreadMessagesNotification.ts
Handle situation when `scrollToBottom` is called from another component when the msg list is scrolled above the observed target (unread separator).The intersection observer is not triggered when Element.scrollTo() is called and so we are left with old position information - being above the `UnreadMessagesSeparator`. So we end up in a situation when we are scrolled to the bottom and at the same time scrolled above the observed target.
> fix: show UnreadMessagesNotification when MessageList is scrolled to bottom via Element.scrollTo

- examples/typescript/package.json
- examples/typescript/yarn.lock
Typescript app is our go-to example for React SDK, however it's currently incompatible with Node 18+ (which is a requirement for `stream-chat-react`).
Fixed by bumping react-scripts to latest.
> chore: bump react-scripts in typescript example

- src/index.ts
- src/types/index.ts
- src/types/types.ts
All the default components extend from `DefaultStreamChatGenerics` type defined in `stream-chat-react`. This type defines different fields on ChannelType than the generics exported from `stream-chat`. This leads to the situation where custom components extend different default type than the default components.
> fix: export DefaultStreamChatGenerics

- .eslintrc.json
- src/components/MessageActions/MessageActionsBox.tsx
Prevents excessive spread of props onto the MessageActionsBox div, and fixes https://github.com/GetStream/stream-chat-react/issues/2269.
> fix: prevent mine attr from spreading on message actions box div

- src/components/MessageList/hooks/VirtualizedMessageList/usePrependMessagesCount.ts
- src/components/MessageList/hooks/__tests__/usePrependMessagesCount.test.js
Prevent including date separator messages in the prepended item count in VML. Prepended item count represents the number of messages loaded during the pagination. These are prepended. A special case of scenario is in empty channel when the messages change the order after being sent and then updated on WS event - their timestamps change and so does their order. That could create artificial prepend count that is incorrect.
This PR fixes a problem, when date separator that is present in the list from the beginning starts to be counted as a prepended message, which is not correct.
fixes #2228
> fix: adjust the first message rendering for DateSeparator in empty VirtualizedMessageList

- axe-helper.js
We had `nested-interactive` rule disabled in axe, but that doesn't seems necessary anymore.
> chore: enable nested-interactive axe rule

- src/components/Emojis/EmojiPicker.tsx
- src/components/Message/MessageOptions.tsx
This fixes an accessibility issue with the `EmojiPicker` and reactions selector: their respective tigger buttons should have `aria-expanded` attribute, as per the [Menu Button ARIA pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/).
No visible changes.
> fix: add aria-expanded attribute to emoji picker and reactions selector

- docusaurus/docs/React/components/contexts/message-context.mdx
- docusaurus/docs/React/components/core-components/message-list.mdx
- docusaurus/docs/React/components/core-components/virtualized-list.mdx
- docusaurus/docs/React/components/message-components/message.mdx
- docusaurus/docs/React/components/message-components/reactions.mdx
- examples/typescript/src/App.tsx
- src/components/Message/Message.tsx
- src/components/Message/types.ts
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/VirtualizedMessageListComponents.tsx
- src/components/Reactions/ReactionsList.tsx
- src/components/Reactions/__tests__/ReactionsList.test.js
- src/components/Reactions/__tests__/ReactionsListModal.test.js
- src/components/Reactions/hooks/useProcessReactions.tsx
- src/components/Reactions/types.ts
- src/context/MessageContext.tsx
Currently the order of reactions in the `ReactionsList` depends of the order of keys in the `reaction_counts` object returned by the backend. This leads to unstable reaction order, which can change on page reloads, or when the list of reactions changes.
We want to provide a way to customize this behavior, and to have a stable order of reactions by default.
Added a new `MessageContext` property: `sortReactions`. It accepts two reaction objects, and should return a positive/negative/zero numeric value, similar to the `Array.prototype.sort` method.
The `sortReactions` prop can be passed both to `MessageList` and `VirtualizedMessageList`, as well as to the `Message` component directly. It will then be available via the `MessageContext`.
> feat: add customizable reactions sorting

- docusaurus/docs/React/components/contexts/message-context.mdx
- docusaurus/docs/React/components/core-components/message-list.mdx
- docusaurus/docs/React/components/core-components/virtualized-list.mdx
- docusaurus/docs/React/components/message-components/message.mdx
- docusaurus/docs/React/components/message-components/reactions.mdx
- src/components/Message/Message.tsx
- src/components/Message/types.ts
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/VirtualizedMessageListComponents.tsx
- src/components/Reactions/ReactionsList.tsx
- src/components/Reactions/ReactionsListModal.tsx
- src/components/Reactions/__tests__/ReactionsListModal.test.js
- src/components/Reactions/types.ts
- src/context/MessageContext.tsx
This is a follow-up to 🚂 #2289. Same thing, but for the list of reacted users inside the reactions list modal.
> feat: add customizable reaction details sorting

- src/components/Chat/hooks/useCreateChatClient.ts
- src/components/Chat/index.ts
Introduce `useCreateChatClient` hook which takes care of creation and initiation of `StreamChat` client. 
closes: GetStream/stream-chat-react-issues#19
> feat: introduce useCreateChatClient hook

- src/components/Message/renderText/index.ts
- src/components/index.ts
- src/types/index.ts
- tsconfig.json
If we want the codebase to be compilable by tools like Vite, that use esbuild under the hood to process files one-by-one, we should follow the rules for isolated typescript modules.
Previously we were breaking the isolated modules rule by doing re-exports like this one:
```ts
export { DefaultStreamChatGenerics, ChannelUnreadUiState } from './types';
```
Where both `DefaultStreamChatGenerics` and `ChannelUnreadUiState` are types. When processing a single file, the compiler doesn't know if these are types or not, and leaves the export statement as is, when really it should be removed.
Fixing this by using verbatim module syntax:
```ts
export type { DefaultStreamChatGenerics, ChannelUnreadUiState } from './types';
```
After fixing all issues, `isolatedModules` was enabled in tsconfig.
A good …
> chore: add verbatim type specifier to export from statements

- src/components/AutoCompleteTextarea/Textarea.jsx
- src/components/MessageInput/__tests__/MessageInput.test.js
Fixes a race condition with emoji auto-replacement when submitting a message.
`_replaceWord` is an async method, we should await it before submitting.
Before:
https://github.com/GetStream/stream-chat-react/assets/975978/d989b491-d301-43c0-9386-ffc41f00f4ee
After:
https://github.com/GetStream/stream-chat-react/assets/975978/3fcf49bf-84e2-46cc-92f4-9eafd2f1c2b0
> fix: await word replace before submitting message

- src/components/Channel/Channel.tsx
- src/components/Channel/__tests__/Channel.test.js
In some circumstances, the response about the delivery of a message may be aborted (timeout) or the web socket information about `message.new` might not arrive because of network conditions (offline, etc...).
In this case, the SDK will prompt the user to re-send the message. Once the user retries, the backend will error with `SendMessage failed: Message with id XYZ already exists`.
This error wasn't handled properly by the SDK and it led the user to re-attempt sending the same message over and over again in a loop.
This loop could have been broken only by reloading the app. This PR aims to fix that.
The SDK now recognizes this error, and once it happens, it immediately marks the message as `received`. This breaks the re-send loop for the user. Any UI inconsistencies (ordering of messages) …
> fix: mark retryable duplicated messages as received

- src/components/Emojis/EmojiPicker.tsx
- Some chat applications that uses the EmojiPicker needs the emoji picker to be closed once an emoji is selected
- The component EmojiPicker allows multiple props available but it doesn't allow to configure this behaviour
- New boolean property `closeOnEmojiSelect` on `EmojiPicker.tsx`
- When the event `onEmojiSelect` is received from `@emoji-mart/react`, the property is checked, unmounting the picker container
> feat: allow EmojiPicker to be closed on emoji click

- src/components/Message/MessageSimple.tsx
This PR adds missing `PinIndicator` placeholder and `str-chat__message--pinned` class name to a `MessageSimple` component.
> fix: add missing PinIndicator placeholder

- src/components/Attachment/__tests__/VoiceRecording.test.js
- src/components/Attachment/__tests__/__snapshots__/File.test.js.snap
- src/components/MessageInput/hooks/utils.ts
Quick fix for some stuff that got broken after removing `pretty-bytes` in #2301:
1. Sizes are now 1024-based (as opposed for 1000-based) to align with backend.
2. Add support for zero-precision,
> fix: file size formatting

- src/components/ChannelSearch/SearchResults.tsx
Small fixups for search results list props:
1. `SearchResultItem` is not an optional prop is practice (it's defaulted in the parent component). Having it optional makes it hard to override `SearchResultsList`. (Technically a breaking change, but let's consider it a fix instead.)
2. `| []` is not required 😅 
The only place realistically that may require updates is the custom `SearchResultsList` component.
Before:
```tsx
const CustomSearchResultsList = (props: SearchResultsListProps) => {
const { results, SearchResultItem = DefaultSearchResultItem } = props;
return /* ... */
};
<ChannelSearch SearchResultsList={CustomSearchResultsList} />
```
After:
```tsx
const CustomSearchResultsList = (props: SearchResultsListProps) => {
// 👇 
const { results, SearchResultItem } = props;
return /* ... */ …
```
> fix: search results list props

- src/components/ChannelSearch/hooks/useChannelSearch.ts
`setChannels` is used by the `ChannelSearch` component to update the channel list state to include the selected search result. When rendered by the `ChannelList`, it actually passes its own `setChannels` setter there.
But this behavior should be optional, because it's totally valid to use search outside of the `ChannelList`.
> fix: make setChannels prop optional for ChannelSearch

- src/components/Emojis/EmojiPicker.tsx
[@tanstack/react-query-devtools]() introduces a side effect which causes pointer event handlers to return children of shadow root nodes as targets. As these targets are not children of hosting elements the `element.contains` method returns `false` and in turn closes the `EmojiPicker`.
Adds `isShadowRoot` check and reaches for `host` node if it is.
> fix(EmojiPicker): check whether clicked target is child of shadow root node

- src/components/Attachment/hooks/useAudioController.ts
- src/components/MediaRecorder/AudioRecorder/AudioRecorder.tsx
- src/components/MediaRecorder/AudioRecorder/AudioRecordingInProgress.tsx
- src/components/MediaRecorder/AudioRecorder/AudioRecordingPreview.tsx
- src/components/MediaRecorder/AudioRecorder/__tests__/AudioRecorder.test.js
- src/components/MediaRecorder/AudioRecorder/__tests__/AudioRecordingPreview.test.js
- src/components/MediaRecorder/AudioRecorder/__tests__/__snapshots__/AudioRecorder.test.js.snap
- src/components/MessageInput/icons.tsx
> test: add AudioRecorder tests

- docusaurus/docs/React/components/message-components/reactions.mdx
- examples/typescript/yarn.lock
- package.json
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/__tests__/MessageText.test.js
- src/components/Message/__tests__/utils.test.js
- src/components/Message/hooks/useReactionHandler.ts
- src/components/Message/hooks/useReactionsFetcher.ts
- src/components/Message/utils.tsx
- src/components/MessageList/utils.ts
- src/components/Reactions/ReactionSelector.tsx
- src/components/Reactions/ReactionsList.tsx
- src/components/Reactions/SimpleReactionsList.tsx
- src/components/Reactions/__tests__/ReactionSelector.test.js
- src/components/Reactions/__tests__/ReactionsList.test.js
- src/components/Reactions/__tests__/ReactionsListModal.test.js
- src/components/Reactions/__tests__/SimpleReactionsList.test.js
- src/components/Reactions/hooks/useProcessReactions.tsx
- src/components/Reactions/types.ts
- src/context/MessageContext.tsx
- src/mock-builders/generator/reaction.js
- yarn.lock
Adds support for a new `reaction_groups` property on message, that contains more in-depth summary of message reactions than the soon-to-be-deprecated `reaction_counts`.
The new property allows to implement a Slack-like sorting order for reactions (sorted by first reaction timestamp) which is now the default.
> feat: support reaction groups

- src/components/AutoCompleteTextarea/Textarea.jsx
React 16 had a wacky thing called [event pooling](https://legacy.reactjs.org/docs/legacy-event-pooling.html). Basically you couldn't use event objects outside of the microtask in which the event handler was triggered, unless you explicitly called `event.persist()`.
When we made key down handler on message input async in https://github.com/GetStream/stream-chat-react/pull/2332, we broke this rule. So `preventDefault()` in [submit handler](https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageInput/hooks/useSubmitHandler.ts#L119) became a no-op.
React still provides the `perist()` method on synthetic events, even in newer versions, so we just use it to fix the issue.
> fix: message input not preventing default on enter on React 16

- docusaurus/docs/React/components/core-components/message-list.mdx
- docusaurus/docs/React/components/core-components/virtualized-list.mdx
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/__tests__/MessageList.test.js
- src/components/MessageList/__tests__/utils.test.js
- src/components/MessageList/hooks/MessageList/useEnrichedMessages.ts
- src/components/MessageList/utils.ts
Allow integrators to influence the "processing" of messages before they are rendered. The adjustment is possible for each message retrieved from the back-end by passing `reviewProcessedMessage` prop to `MessageList` resp. `VirtualizedMessageList`
> feat: allow to review message processing before rendering in message lists

- src/components/Message/MessageSimple.tsx
> fix: attach class str-chat__message-with-thread-link only if the message has replies

- src/components/MessageInput/AttachmentPreviewList/AttachmentPreviewList.tsx
- src/components/MessageInput/MessageInputFlat.tsx
- src/components/MessageInput/__tests__/MessageInput.test.js
Prevent showing link previews in AttachmentPreviewList:
Link previews are not filtered out of `attachments` array in `MessageInput` state. Therefore:
- if there are only link previews in `attachments` and no uploads, do not show `AttachmentPreviewList`
- if there is a mix of link previews and other attachments in `attachments`, show `AttachmentPreviewList` without attachments representing link previews. The link previews are rendered with another component.
Tests to cover these requirements are just drafted in todo as the whole `MessageInput.test.js` tests only v1 components. These tests will be added to #2394 (added with commit https://github.com/GetStream/stream-chat-react/pull/2394/commits/ef5e46bbb0f7075bb236171ccd5f27bb05c1fd35)
> fix: prevent showing link previews in AttachmentPreviewList

- src/components/MessageList/hooks/VirtualizedMessageList/useGiphyPreview.ts
- src/components/MessageList/hooks/__tests__/useGiphyPreview.test.js
> fix: reflect separateGiphyPreview prop value in VirtualizedMessageList

- src/components/Gallery/Gallery.tsx
- src/components/Gallery/Image.tsx
- src/components/Message/MessageSimple.tsx
- src/components/MessageBounce/MessageBounceModal.tsx
- src/components/Modal/Modal.tsx
- src/components/Reactions/ReactionsListModal.tsx
Allow to apply specific styles to different modal scenarios.
> feat: allow custom class on Modal root div

- docusaurus/docs/React/components/message-components/ui-components.mdx
- src/components/Message/MessageStatus.tsx
- src/components/Message/__tests__/MessageStatus.test.js
- src/components/Message/__tests__/__snapshots__/MessageStatus.test.js.snap
> feat: allow to customize MessageStatus UI by message delivery status

- src/components/Channel/Channel.tsx
> fix: memoize addNotification function provided by Channel component

- src/components/Message/renderText/__tests__/__snapshots__/renderText.test.js.snap
- src/components/Message/renderText/__tests__/renderText.test.js
- src/components/Message/renderText/remarkPlugins/keepLineBreaksPlugin.ts
`keepLineBreaksPlugin`'s visitor function terminated tree traversal when encountered multiple markdown elements on one line.
fix: #2409
> fix: keep line breaks in message text that contains multiple markdown elements

- src/components/Channel/Channel.tsx
- src/context/ChannelActionContext.tsx
Adjust `ChannelActionContextValue` type to include new `highlightDuration` parameter, pair the types to the functions so that we don't forget in the future (in case we need to adjust).
> fix: adjust ChannelActionContextValue type

- package.json
- src/components/MediaRecorder/transcode/mp3.ts
Bundle @breezystack/lamejs separately and thus load it only if audio recording is enabled.
> feat: load lazily mp3 encoding library for audio recorder

- src/components/InfiniteScrollPaginator/InfiniteScroll.tsx
Eager channel pagination lead to problems in Safari. More messages were queried on channel opening which increased the scroll size of the container. Safari does not adjust container scrollTop on prepending new items. The SDK logic however relies on scroll events to maintain the list scrolled to the bottom. As a result the container was not scrolled to the bottom in Safari.
> fix: avoid eager channel pagination on channel open

- src/components/Channel/channelState.ts
When switching between threads, the threadHasMore flag has to be always re-enabled.
fix #2433
> fix: always load thread replies on Thread opening

- src/components/Attachment/__tests__/VoiceRecording.test.js
- src/components/Attachment/__tests__/WaveProgressBar.test.js
- src/components/Attachment/__tests__/__snapshots__/WaveProgressBar.test.js.snap
- src/components/Attachment/components/WaveProgressBar.tsx
- src/components/MediaRecorder/AudioRecorder/__tests__/AudioRecorder.test.js
- src/components/MediaRecorder/AudioRecorder/__tests__/__snapshots__/AudioRecorder.test.js.snap
- src/mock-builders/browser/ResizeObserver.js
- src/mock-builders/browser/index.js
Adjust the number of bars and the gap width based on the available space.
The solution uses ResizeObserver as the only way to react to size change of the root div. The `window` `resize` would be useful only to mobile device screen rotation, but not possible message list resizing if implemented by integrators.
[6Y0O.webm](https://github.com/GetStream/stream-chat-react/assets/32706194/95c7b9d1-ed52-41e2-a15c-a86e500a9241)
> fix: adapt audio recording wave form to the available space

- src/components/MessageList/VirtualizedMessageListComponents.tsx
- src/components/MessageList/__tests__/VirtualizedMessageListComponents.test.js
The default message UI component does not make use of `groupStyles`
Closes #2214 
Co-authored-by: @TaylorBeeston
> fix: forward groupStyles to Message in VirtualizedMessageList

- docusaurus/docs/React/components/core-components/message-list.mdx
- docusaurus/docs/React/components/core-components/virtualized-list.mdx
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/VirtualizedMessageListComponents.tsx
- src/components/MessageList/__tests__/utils.test.js
- src/components/MessageList/hooks/MessageList/useEnrichedMessages.ts
- src/components/MessageList/utils.ts
The goal is the parity with RN Chat SDK.
If the value of `maxTimeBetweenGroupedMessages` is greater then the difference btw the current and next message creation date, the groupd is considered to end with the current message. Effectively, what happens is that the message is applied  a class `str-chat__li--bottom`. The visual result is reflected in `MessageList` (each message has timestamp and author (metadata) shown) but not in `VirtualizedMessageList` which has additional logic that decides whether a group ends at a given message. This should be synced with the `MessageList` but potentially introducing breaking changes to the integrators using `VirtualizedMessageList` :it_is_what_it_is_emoji.
> feat: configure message group size by max time between messages

- docusaurus/docs/React/release-guides/upgrade-to-v12.mdx
1. Adds a section about the new build pipeline to the v12 migration guide
2. Fixes a couple of typos
> docs: add notes about new build pipeline to migration guide

- docusaurus/docs/React/guides/date-time-formatting.mdx
- docusaurus/docs/React/release-guides/upgrade-to-v12.mdx
- src/components/DateSeparator/DateSeparator.tsx
- src/components/DateSeparator/__tests__/DateSeparator.test.js
- src/components/EventComponent/EventComponent.tsx
- src/components/EventComponent/__tests__/EventComponent.test.js
- src/components/Message/MessageSimple.tsx
- src/components/Message/MessageTimestamp.tsx
- src/components/Message/Timestamp.tsx
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/__tests__/MessageTimestamp.test.js
- src/i18n/de.json
- src/i18n/en.json
- src/i18n/es.json
- src/i18n/fr.json
- src/i18n/hi.json
- src/i18n/it.json
- src/i18n/ja.json
- src/i18n/ko.json
- src/i18n/nl.json
- src/i18n/pt.json
- src/i18n/ru.json
- src/i18n/tr.json
- src/i18n/utils.ts
Provide a betted DX for those that want to override the defaults via i18n. This way there is no need to nullify the default component prop values. Based on direct customer feedback.
BREAKING CHANGE: Removed default values for timestamp formatting props like calendar or format for DateSeparator, EventComponent, MessageTimestamp. The formatting configuration now entirely relies on i18n translations.
> feat: remove default timestamp formatting props from DateSeparator, EventComponent, MessageTimestamp

- src/components/Message/utils.tsx
Consider `groupStyles` prop in Message UI component memoization, aka memoization strikes again.
> fix: reflect Message groupStyles prop in the component memoization

- src/components/MediaRecorder/AudioRecorder/AudioRecordingInProgress.tsx
- src/components/MessageInput/hooks/useTimeElapsed.ts
`MediaRecorder` is already in `"recording"` state when `AudioRecordingInProgress` component is rendered on iOS.
fix #2452
> fix: start audio recorder timer if already recording

- package.json
- scripts/bundle.mjs
- scripts/validate-cjs-bundle.cjs
- yarn.lock
That should fix the problem with node-specific versions of packages included in the CJS bundle.
> fix: change platform for CJS bundle from node to browser

- src/components/Message/MessageStatus.tsx
- src/components/Message/__tests__/MessageStatus.test.js
- src/components/MessageList/__tests__/utils.test.js
Correctly account for the presence of own user in the message readers' array and don't just assume it is always present.
Once we know a message has been read by someone else, let's take an array of other users who read the message and base the reader count rendering on that.
> fix: prevent including own user in read count displayed in MessageStatus

- package.json
- src/components/Message/renderText/__tests__/__snapshots__/renderText.test.js.snap
- src/components/Message/renderText/rehypePlugins/mentionsMarkdownPlugin.ts
- src/components/Message/renderText/remarkPlugins/htmlToTextPlugin.ts
- src/components/Message/renderText/remarkPlugins/keepLineBreaksPlugin.ts
- src/components/Message/renderText/renderText.tsx
- yarn.lock
fix #2455
fix #2234
Only react-markdown was downgraded while the libraries used to create remark and rehype plugins have not. Custom rehype or remark plugins using `visit` function from the library `unist-util-visit` will have to check the `index` and `parent` arguments of the `Visitor` function for `null` and `undefined`.
> fix: downgrade react-markdown to v8 that supports React version < v18

- docusaurus/docs/React/basics/getting-started.mdx
- src/components/Chat/hooks/useCreateChatClient.ts
Allow to initiate `StreamChat` instance with options.
> fix: forward StreamChat constructor options via useCreateChatClient

- docusaurus/docs/React/basics/getting-started.mdx
- src/components/Chat/hooks/useCreateChatClient.ts
🚂 https://github.com/GetStream/stream-chat-react/pull/2463
It might be better not to recreate the client every time options update, since `useCreateChatClient({ options: { /* some inline options */ } })` will probably be a popular way to use this hook.
> fix: do not rerender on client options update

- docusaurus/docs/React/components/contexts/message-input-context.mdx
- docusaurus/docs/React/components/message-input-components/message-input.mdx
- docusaurus/react_versioned_docs/version-11.x.x/components/contexts/message-input-context.mdx
- docusaurus/react_versioned_docs/version-11.x.x/components/message-input-components/message-input.mdx
Remove forgotten and no longer functional EmojiPicker mentions from docs.
> docs: remove EmojiPicker remnants

- package.json
- src/components/Channel/Channel.tsx
- src/components/Channel/__tests__/Channel.test.js
- yarn.lock
Use the pagination flags from the the client, which actually performs the queries and thus share the information btw React components that are siblings (`ChannelList` queries channels and `Channel` will know, what channels have less than the 1st page size message count).
depends on https://github.com/GetStream/stream-chat-js/pull/1332
> fix: use the client pagination indicators for ChannelStateContext's hasMore and hasMoreNewer flags

- package.json
- src/components/Channel/hooks/useCreateChannelStateContext.ts
- src/components/Chat/Chat.tsx
- src/components/Chat/hooks/useChat.ts
- src/components/DateSeparator/DateSeparator.tsx
- src/components/EventComponent/EventComponent.tsx
- src/components/Message/MessageTimestamp.tsx
- src/components/Message/Timestamp.tsx
- src/components/Message/__tests__/MessageTimestamp.test.js
- src/components/MessageList/utils.ts
- src/context/TranslationContext.tsx
- src/i18n/Streami18n.ts
- src/i18n/index.ts
- src/i18n/types.ts
- src/i18n/utils.ts
- yarn.lock
Circular dependencies btw. the translation files caused problems to users who installed the version built with esbuild into an app based on react-scripts and React v17/v16.
As a side effect, this refactor lead to correct execution of extending Dayjs with plugins in Streami18n. Thus the fixed tests.
> fix: address the circular dependencies among TranslationContext and Streami18n

- src/components/MessageInput/MessageInputFlat.tsx
It's perfectly normal to quote a message that is part of a thread, as long as it's quoted in the same thread. Looks like this logic has been broken for some time. This PR fixes it.
Take a look at how quoted message is handled in `Channel`:
```
const messageData = {
// ...
quoted_message_id: parent_id === quotedMessage?.parent_id ? quotedMessage?.id : undefined
};
```
Quoting is allowed as long as the quoted message is part of the same thread, or both are regular non-thread messages.
However, there was a mismatch in how `MessageInputFlat` displays a quoted message: it was always hidden for thread messages, which lead to confusing behavior.
Now the logic is the same in both places.
> fix: quote replies in threads

- src/components/Message/MessageOptions.tsx
- src/components/Message/__tests__/MessageOptions.test.js
- src/components/Message/utils.tsx
- src/components/MessageActions/MessageActions.tsx
- src/components/MessageActions/__tests__/MessageActions.test.js
This change allows rendering `CustomMessageActionsList` component without having to provide empty `customMessageActions` object.
> fix: MessageActions adjustments

- src/components/ChannelSearch/__tests__/ChannelSearch.test.js
- src/components/ChannelSearch/hooks/useChannelSearch.ts
- src/components/MessageInput/hooks/useUserTrigger.ts
The `$nin` and the `$ne` operators cause bad performance on the backend, and they will be deprecated (and eventually removed). The SDK used only `$ne` operator which is now removed. It also means that the own user will not be anymore filtered out of the selection list of users to mention if `mentionAllAppUsers` is enabled on `MessageInput`. Own user will be  always included on the list if matched.
> fix: remove the use of deprecated query operator $ne

- src/components/Channel/hooks/useCreateChannelStateContext.ts
- src/components/ChannelHeader/ChannelHeader.tsx
- src/components/ChannelPreview/hooks/useChannelPreviewInfo.ts
- src/components/ChannelPreview/utils.tsx
In case of `ChannelPreview` the effect that set the display image and title was missing dependencies.
In case of `ChannelHeader` the problem with `ChannelStateContext` value memoization was the cause.
> fix: update ChannelHeader and ChannelPreview titles and images on channel.updated

- docusaurus/react-docusaurus-dontent-docs.plugin.js
- docusaurus/react_versioned_docs/version-11.x.x/theming/introduction.mdx
We cannot test redirect in development mode. Followed [docusaurus redirects example](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects#ex-config)
> docs: make v12 the last version and redirect /v12 routes to /

- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/hooks/useChannelDeletedListener.ts
- src/components/ChannelList/hooks/useChannelHiddenListener.ts
- src/components/ChannelList/hooks/useChannelTruncatedListener.ts
- src/components/ChannelList/hooks/useChannelUpdatedListener.ts
- src/components/ChannelList/hooks/useChannelVisibleListener.ts
- src/components/ChannelList/hooks/useConnectionRecoveredListener.ts
- src/components/ChannelList/hooks/useMessageNewListener.ts
- src/components/ChannelList/hooks/useNotificationAddedToChannelListener.ts
- src/components/ChannelList/hooks/useNotificationMessageNewListener.ts
- src/components/ChannelList/hooks/useNotificationRemovedFromChannelListener.ts
- src/components/ChannelList/hooks/useUserPresenceChangedListener.ts
fix #2524 and fix all the ChannelList hook effect deps.
> fix: add missing dependencies to ChannelList hooks effects

- docusaurus/docs/React/components/core-components/message-list.mdx
- docusaurus/docs/React/components/core-components/virtualized-list.mdx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/VirtualizedMessageListComponents.tsx
Add parity btw. `MessageList` and `VirtualizedMessageList` in aspect of customizing thread opening callback in `VirtualizedMessageList`.
> feat: add openThread prop to VirtualizedMessageList

- docusaurus/docs/React/components/core-components/channel-list.mdx
- docusaurus/docs/React/components/utility-components/channel-preview-ui.mdx
- docusaurus/docs/React/components/utility-components/channel-preview.mdx
- docusaurus/docs/React/guides/customization/channel-list-preview.mdx
- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/ChannelPreview/ChannelPreview.tsx
- src/components/ChannelPreview/ChannelPreviewMessenger.tsx
- src/components/ChannelPreview/__tests__/ChannelPreview.test.js
- src/components/ChannelPreview/__tests__/ChannelPreviewMessenger.test.js
- src/components/ChannelPreview/utils.tsx
- src/mock-builders/event/messageUndeleted.js
Fix bug of not syncing `lastMessage` and `latestMessage`. Meanwhile the `latestMessage` was correctly taken from the channel state, the `lastMessage` was set as any message coming with `message.new`, `message.updated` and `message.deleted`. Moreover, `message.undeleted` and `channel.truncate` were not taken into consideration when setting `lastMessage`. Now both are set from the `channel.state`.
Another fix is that `latestMessage` was derived from `channel.state.messages` what is a getter that returns the currently viewed message set in the message list, but not the latest message set. This had to be changed to `channel.state.latestMessages`.
I have deprecated `latestMessage` in favor of `latestMessagePreview` because for integrators (and for me) it was unclear how does it differ from …
> fix: get correct lastMessage and latestMessagePreview from channel state

- .github/workflows/release.yml
Sometimes we do not want to override the staging documentation when releasing from maintenance branches (v11, v10...)
> chore(release): add option to skip publishing documentation

- docusaurus/docs/React/guides/sdk-state-management.mdx
- src/components/ChatView/ChatView.tsx
- src/components/Dialog/hooks/useDialog.ts
- src/components/Thread/Thread.tsx
- src/components/Threads/ThreadList/ThreadList.tsx
- src/components/Threads/ThreadList/ThreadListItemUI.tsx
- src/components/Threads/ThreadList/ThreadListLoadingIndicator.tsx
- src/components/Threads/ThreadList/ThreadListUnseenThreadsBanner.tsx
- src/store/hooks/useStateStore.ts
Adjust selector outputs to be named objects to match the new `StateStore` API.
> feat: return objects from selectors instead of arrays

- src/utils/getChannel.ts
Remove stale promise references from the channel query lock. If not removed, even if the whole chat is remounted, the rejected promise from the past leads to display of error in the chat UI. This is because the lock is located in the global scope.
> fix: remove rejected channel query promises from channel query lock

- src/components/MessageInput/__tests__/MessageInput.test.js
- src/components/MessageInput/hooks/usePasteHandler.ts
When a website content is copied or MS Word content is copied, the clipboards DataTransferItemList contains two items:
```
{kind: "string", type: "text/plain"}
{kind: "string", type: "text/html"}
```
The type `text/html` carries information about images, that can be uploaded to the back-end. Until now, if both item types were present, the `text/plain` type was ignored and images were extracted and uploaded from the `text/html` type. This lead to surprising behavior of user instead of observing the copied text to be pasted into the message composer, the images to be added as attachments.
This PR changes this behavior by giving preference to pasting text over images as chat applications usually do. The `text/html` content us thus ignored.
> fix: give preference to pasting text over files

- src/components/ChatAutoComplete/ChatAutoComplete.tsx
[the type `SuggestionItem`](https://github.com/GetStream/stream-chat-react/blob/949446b6b5e5193da590e92487a9997fdd6da20d/src/components/ChatAutoComplete/ChatAutoComplete.tsx#L30) uses [type `SuggestionEmoji`](https://github.com/GetStream/stream-chat-react/blob/949446b6b5e5193da590e92487a9997fdd6da20d/src/components/ChatAutoComplete/ChatAutoComplete.tsx#L26) which is declared as an array (result of emoji search). But this cannot be right as every suggestion item component receives a single data point from an array. This iteration and passing of single objects is done in [`SuggestionList`]( https://github.com/GetStream/stream-chat-react/blob/949446b6b5e5193da590e92487a9997fdd6da20d/src/components/AutoCompleteTextarea/List.jsx#L121).
Without doing this change, it is impossible to implement …
> fix: change SuggestionEmoji to extended EmojiSearchIndexResult

- package.json
- src/components/Message/__tests__/MessageSimple.test.js
- src/components/Message/utils.tsx
- yarn.lock
Support moderation v2 workflow
Depends on https://github.com/GetStream/stream-chat-js/pull/1392
The moderation v2 workflow is the same as v1. The only difference is that the moderation data is received with `message.moderation` object instead of `message.moderation_details`. The new moderation object contains more attributes that can be later acted on.
The SDK will now also mark message as bounced if it carries `moderation` object with `action` attribute value equal to `bounce`.
No changes, the workflow is kept the same.
> feat: support moderation v2 workflow

- .releaserc.json
- package.json
- scripts/bundle.mjs
- scripts/copy-version.sh
- src/components/Chat/__tests__/Chat.test.js
- src/components/Chat/hooks/useChat.ts
- src/version.ts
- yarn.lock
Report the correct package version in `useChat.ts` hook.
During the release process the correct latest package version can be determined only while `semantic-release` is run. This is because `semantic-release` infers the next version. The bundle script now takes into consideration the `NEXT_VERSION` env variable value set during the `semantic-release` process run. If this value is not set, then the version is calculated from the current latest git tag - that is useful for local builds. Otherwise the fallback is package.json `version` that is not maintained, but such fallback should actually be never executed.
We are removing the `version.ts` file and `copy-version.sh` script as this script was run before the version could be calculated.
> fix: report correct package version in the source code

- package.json
- scripts/bundle-cjs.mjs
- scripts/bundle-esm.mjs
- scripts/getPackageVersion.mjs
- src/components/Chat/hooks/useChat.ts
Report package version not only in cjs bundles.
> fix: report correct package version in esm build

- scripts/getPackageVersion.mjs
`execSync` was not imported, so getting the latest tag always failed.
> fix: import execSync

- examples/vite/src/App.tsx
- examples/vite/src/index.scss
- package.json
- src/components/ChannelList/hooks/useChannelListShape.ts
- src/components/ChannelList/hooks/useChannelMembershipState.ts
- src/components/ChannelList/hooks/useSelectedChannelState.ts
- src/components/ChannelList/utils.ts
- yarn.lock
Adjust certain conditions to match behavior of the RN implementation, add missing handler for the `notification.added_to_channel`.
- `notification.added_to_channel` is being handled properly (considers pinned channels)
- if `sort` is an object and `pinned_at` is first in chronological order of property creation `{ pinned_at: 1 | -1 }` then pinned channels are considered (https://github.com/GetStream/stream-chat-react/issues/2595#issuecomment-2569118691)
Related PR: https://github.com/GetStream/stream-chat-js/pull/1430
> fix: channel-pinning related improvements

- src/components/ChannelSearch/__tests__/ChannelSearch.test.js
- src/components/ChannelSearch/hooks/useChannelSearch.ts
> feat: allow to search for channels only

- src/store/hooks/useStateStore.ts
Changing stores on the fly would keep previously calculated state for a bit before the effect would run to recalculate it - using `useSyncExternalStore` (thank you, @myandrienko) should alleviate this issue. Both `subscribe` and `getSnapshot` functions required by the React hook are wrapped to allow for selector functionality, [`geSnapshot` requires the output to be cached](https://react.dev/reference/react/useSyncExternalStore#parameters) so the wrapper reuses similar cache check mechanism as `subscribeWithSelector` does internally.
> fix: change useStateStore to use useSyncExternalStore

- src/components/ChannelList/hooks/useChannelListShape.ts
References: https://github.com/GetStream/stream-chat-react-native/pull/2925
> fix: make `channel.visible` respect archived and pinned channels

- src/components/ChannelList/hooks/useChannelListShape.ts
This PR solves an issue where if `pinned_at` is missing from the `sort`, the archived channels are not being handled properly during application runtime.
> fix(handleMemberUpdated): consider both pinned and archived channels

- src/components/MediaRecorder/classes/MediaRecorderController.ts
- src/components/MediaRecorder/classes/__tests__/MediaRecorderController.test.js
- src/components/MediaRecorder/hooks/__tests__/useMediaRecorder.test.js
- src/mock-builders/browser/MediaRecorder.js
Introduce a more reliable way to determine, what audio recording format should be used as navigator.userAgent is not reliable.
> fix: determine audio recording format with MediaRecorder.isTypeSupported not userAgent

- src/components/MessageList/__tests__/MessageList.test.js
- src/components/MessageList/utils.ts
UnreadMessagesIndicator was shown in thread's message list even though threads do not support unread state.
Fixes [REACT-293](https://linear.app/stream/issue/REACT-293/prevent-showing-unreadmessagesseparator-in-threads)
> fix: hide UnreadMessagesSeparator in threads

- package.json
- src/components/Message/QuotedMessage.tsx
- src/components/Message/__tests__/QuotedMessage.test.js
- src/components/MessageInput/MessageInputFlat.tsx
- src/components/MessageInput/QuotedMessagePreview.tsx
- src/components/MessageInput/__tests__/MessageInput.test.js
- yarn.lock
Currently, Markdown text is not being rendered properly within quoted messages (`renderText` omitted). This PR aims at adding `renderText` to both `QuotedMessage` and `QuotedMessagePreview` components.
> feat: render Markdown within quoted message components

- package.json
- src/components/Channel/Channel.tsx
- src/components/Message/MessageBlocked.tsx
- src/components/Message/MessageSimple.tsx
- src/components/Message/utils.tsx
- src/context/ComponentContext.tsx
- src/i18n/de.json
- src/i18n/en.json
- src/i18n/es.json
- src/i18n/fr.json
- src/i18n/hi.json
- src/i18n/it.json
- src/i18n/ja.json
- src/i18n/ko.json
- src/i18n/nl.json
- src/i18n/pt.json
- src/i18n/ru.json
- src/i18n/tr.json
- yarn.lock
This PR adds a `MessageBlocked` component to render instead of a normal message UI whenever sync/async moderation blocks an inappropriate message.
Ref: https://github.com/GetStream/stream-chat-js/pull/1510
Ref: https://github.com/GetStream/stream-chat-css/pull/327
Also awaits BE changes to the `message.updated` message object's payload.
> feat: [REACT-218] add MessageBlocked component

- src/@types/stream-chat-common-custom-data.d.ts
- src/@types/stream-chat-custom-data.d.ts
- src/types/defaultDataInterfaces.ts
- src/types/index.ts
- src/types/types.ts
Introduce default data interfaces which are used to extend `stream-chat` interfaces with custom data used across the SDK. These defaults can be used by our integrators who use our default components which expect this custom data to be present.
> feat: default data interfaces

- src/components/Channel/Channel.tsx
- src/components/MessageInput/MessageInput.tsx
- src/components/MessageInput/MessageInputFlat.tsx
- src/components/MessageInput/WithDragAndDropUpload.tsx
- src/components/MessageInput/index.ts
- src/context/MessageInputContext.tsx
Current `Channel.dragAndDropWindow` and `Channel.optionalMessageInputProps` architecture which used to allow drag&drop file upload by dropping files onto the message list (channel) component suffers from a few pain points: 
- duplicate `MessageInputContextProvider` initialization, see [here](https://github.com/GetStream/stream-chat-react/blob/5fa6b0fc239a7d48032ae4c3d34e29969c52bd0c/src/components/Channel/Channel.tsx#L1479-L1484), [here](https://github.com/GetStream/stream-chat-react/blob/5fa6b0fc239a7d48032ae4c3d34e29969c52bd0c/src/components/MessageInput/MessageInput.tsx#L137-L159) and [here](https://github.com/GetStream/stream-chat-react/blob/5fa6b0fc239a7d48032ae4c3d34e29969c52bd0c/src/components/MessageInput/DropzoneProvider.tsx#L47-L67) ([related …
> feat: introduce WithDragAndDropUpload component

- src/components/MessageInput/MessageInput.tsx
- src/components/MessageInput/WithDragAndDropUpload.tsx
Yesterday evening I reconsidered how the wrapper should work - this way it's much more simpler and allows multiple `MessageInput` components to work under one wrapper without any clashing.
Since the previous feature has not been released yet, we can change the context API without any worry and thus `refactor`.
> refactor: simplify WithDragAndDropUpload API

- package.json
- src/components/MessageInput/__tests__/EditMessageForm.test.js
- src/components/MessageInput/__tests__/MessageInput.test.js
- src/components/TextareaComposer/SuggestionList/CommandItem.tsx
- src/components/TextareaComposer/SuggestionList/SuggestionList.tsx
- src/components/TextareaComposer/SuggestionList/SuggestionListItem.tsx
- yarn.lock
Allow to customize the UI components for different suggestion item types separately.
> feat: replace SuggestionItem prop with suggestionItemComponents prop for SuggestionList

- src/components/MessageInput/hooks/useSubmitHandler.ts
Make the clearing of the MessageInput UI immediate without any delay when sending a message.
> fix: clear composer state optimistically with snapshot restoration upon sending a message

- src/components/MessageInput/hooks/useSubmitHandler.ts
When sending a poll message (contains only poll id) the composer id has to be created anew (for the next msg) and the poll composer state has to be reset. The rest of the states should be kept as they can be used for the next message.
This should be moved to the LLC in the future, once `MessageComposer.sendMessage()` exists.
> fix: reset message composer state partially when poll message is sent

- src/components/Dialog/DialogManager.ts
- src/components/Dialog/DialogPortal.tsx
- src/components/Dialog/__tests__/DialogsManager.test.js
- src/components/MessageInput/AttachmentSelector.tsx
- src/components/MessageInput/MessageInput.tsx
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/VirtualizedMessageList.tsx
- src/components/MessageList/__tests__/VirtualizedMessageList.test.js
- src/components/MessageList/__tests__/__snapshots__/VirtualizedMessageList.test.js.snap
- src/components/UtilityComponents/useStableId.ts
Rendering two Channel components side by side would result in inability to open any type of a dialog (rendered by default SDK components) in the other window.
This PR adds unique strings to existing dialog manager ID's to prevent UI clashes.
Fixes: #2685
Fixes: #2682
> fix: extend dialogManagerId's with dictinct strings

- src/components/Poll/PollHeader.tsx
- src/components/Poll/__tests__/PollHeader.test.js
Do not show any string in PollHeader if there are no options.
Fixes REACT-389
> fix: account for polls with no options in PollHeader text

- src/components/Channel/Channel.tsx
- src/components/MessageList/VirtualizedMessageListComponents.tsx
Closes REACT-411 
Prevent showing empty message list indicator when we already have message loaded in state.
> fix: prevent rendering placeholder for empty message list if messages are actually loaded 

- src/context/ComponentContext.tsx
- src/i18n/TranslationBuilder/TranslationBuilder.ts
- src/i18n/TranslationBuilder/notifications/index.ts
- src/i18n/__tests__/TranslationBuilder.test.js
- src/i18n/index.ts
Allow integrators to register translators before i18next initiation
Specifically, we want this translator to be executed if registered as follows (before passing `i18nInstance` to `Chat` component) :
```js
const i18nInstance = new Streami18n();
const customNotificationTranslators: Record<
string,
Translator<NotificationTranslatorOptions>
> = {
'api:message:send:failed': ({ key, value, options: { notification }, t }) => {
return 'translated';
},
};
// this registration call was internally ignored due to i18next not being initiated yet
i18nInstance.translationBuilder.registerTranslators(
'notification',
customNotificationTranslators,
);
```
> fix: allow to pre-register TranslationTopic translator functions

- src/components/TextareaComposer/TextareaComposer.tsx
Fixes a problem when a text change is committed to the state before the selection state is updated (e.g. Ctrl + A & Ctrl + V -> Ctrl + V takes precendence and just leads to appending of inserted string instead of overwriting int)
> fix: prevent debouncing the selection state update in TextareaComposer

- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/hooks/usePaginatedChannels.ts
- src/context/ChannelListContext.tsx
Allow integrators to recover from failed pagination requests. For example by showing retry button in custom `LoadingErrorIndicator` passed to `ChannelList`. Unfortunately the indicator is not shown along the channel list items. It is items or error. That part is not changed as it would be breaking change.
Example:
```tsx
const ChannelListLoadingIndicator = () => {
const { hasNextPage, loadNextPage } = useChannelListContext();
return (
<div>
<div>Failed to load channels</div>
{hasNextPage && <button onClick={loadNextPage}>Retry</button>}
</div>
);
};
<ChannelList
filters={filters}
LoadingErrorIndicator={ChannelListLoadingIndicator}
options={options}
sort={sort}
/>
```
Update docs
> feat: add pagination tools to ChannelList context

- src/components/Channel/Channel.tsx
> fix: prevent setting unread UI state for channel non-members

- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/ChannelListMessenger.tsx
- src/components/ChannelList/__tests__/ChannelList.test.js
- src/components/Loading/LoadingErrorIndicator.tsx
Fixes REACT-458
Make the implementation consistent with the [documentation](https://getstream.io/chat/docs/sdk/react/components/utility-components/indicators/#loadingerrorindicatorprops) that claims we are forwarding the object.
> fix: forward error object to LoadingErrorIndicator in ChannelList

- src/components/MessageInput/__tests__/EditMessageForm.test.js
- src/components/TextareaComposer/TextareaComposer.tsx
Fix #2760 
Controlling the textarea value via external state lead to cancellation of composition events - specifically `compositionend`. But at the same time, we need to override the textarea value with the middleware processing result (e.g. to replace original string with emoji). 
So the value is set inside the effect.
> fix: make character composition possible in textarea

- src/components/Dialog/FormDialog.tsx
- src/components/MessageInput/EditMessageForm.tsx
- src/components/MessageInput/__tests__/ThreadMessageInput.test.js
- src/components/Poll/PollCreationDialog/OptionFieldSet.tsx
- src/components/Poll/PollCreationDialog/PollCreationDialogControls.tsx
Fixes REACT-471
All the non-submit buttons should be marked as `type='button'`:
https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/submit#using_submit_buttons
This change fixes the behavior where the submit handler is not invoked if the input types are not clearly distinguished.
> fix: distinguish non-submit form buttons

- package.json
- src/i18n/TranslationBuilder/notifications/NotificationTranslationTopic.ts
- src/i18n/TranslationBuilder/notifications/pollVoteCountTrespass.ts
- src/i18n/de.json
- src/i18n/en.json
- src/i18n/es.json
- src/i18n/fr.json
- src/i18n/hi.json
- src/i18n/it.json
- src/i18n/ja.json
- src/i18n/ko.json
- src/i18n/nl.json
- src/i18n/pt.json
- src/i18n/ru.json
- src/i18n/tr.json
- yarn.lock
Depends on https://github.com/GetStream/stream-chat-js/pull/1598
> fix: publish notification on poll vote casting limit trespass

- src/components/Modal/Modal.tsx
- src/components/Modal/__tests__/Modal.test.js
Closes REACT-386
Customer request to control whether on modal overlay click a modal is closed. This PR makes it more general so that it can be determined what happens on overlay click, close button click, Escape key press. Array of events can be extended in the future.
> feat: allow restrictions on modal close behavior

- package.json
- src/components/Attachment/__tests__/Geolocation.test.js
- src/components/Channel/Channel.tsx
- src/components/Chat/Chat.tsx
- src/components/Dialog/DialogManager.ts
- src/components/Dialog/DialogPortal.tsx
- src/components/Dialog/__tests__/DialogManagerContext.test.js
- src/components/Dialog/hooks/useDialog.ts
- src/components/Gallery/Gallery.tsx
- src/components/Gallery/Image.tsx
- src/components/MessageActions/__tests__/MessageActions.test.js
- src/components/MessageBounce/MessageBounceModal.tsx
- src/components/MessageInput/AttachmentSelector.tsx
- src/components/MessageInput/EditMessageForm.tsx
- src/components/MessageList/__tests__/VirtualizedMessageListComponents.test.js
- src/components/MessageList/__tests__/__snapshots__/VirtualizedMessageList.test.js.snap
- src/components/MessageList/__tests__/__snapshots__/VirtualizedMessageListComponents.test.js.snap
- src/components/Modal/GlobalModal.tsx
- src/components/Modal/__tests__/GlobalModal.test.js
- src/components/Modal/index.ts
- src/components/Poll/PollActions/PollAction.tsx
- src/components/Poll/PollActions/PollActions.tsx
- src/components/Reactions/ReactionsListModal.tsx
- src/context/ComponentContext.tsx
- src/context/DialogManagerContext.tsx
- yarn.lock
Allow to render the modal at the top of chat app.
Fixes REACT-22
Fixes REACT-340
Fixes the issue of modal overlay being cut-off in Safari because the parent was the message thus limiting the overlay position fixed to the message list.
Depends on CSS adjustments: https://github.com/GetStream/stream-chat-css/pull/341
This is an opt-in feature. The top-level modal rendering is activated by passing `GlobalModal` to `Channel` and thus the `ComponentContext`:
```jsx
import { GlobalModal } from 'stream-chat-react';
const Component = () => <Channel Modal={GlobalModal}></Channel>
```
The PR introduces possibility of nested `DialogManagerProviders` (Modal > MessageList) and thus allowing to retrieve a dialog manager other than the one from the nearest dialog manager context.
None …
> feat: add support for global modal rendering at the top of the chat component tree

- src/components/Modal/GlobalModal.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/__tests__/GlobalModal.test.js
`GlobalModal` was added in parallel to the PR which introduced `onCloseAttempt` to `ModalProps`. This PR introduces `onCloseAttempt` prompt to `GlobalModal.
> feat: respect onCloseAttempt prop in GlobalModal

- src/components/Message/__tests__/utils.test.js
- src/components/Message/utils.tsx
The presence of actions using `Array.prototype.indexOf` should be checked against -1 not agains value truthiness.
> fix: check the presence of remindMe and saveForLater message actions correctly

- src/components/ChannelPreview/__tests__/utils.test.js
- src/components/ChannelPreview/utils.tsx
The ChannelPreview did not render any text preview if the latest message represented HTML string. Other SDKs do render the preview as well as the message in message list
> fix: render html as text in ChannelPreview

- src/components/ChannelPreview/utils.tsx
- src/components/Message/renderText/__tests__/renderText.test.js
- src/components/Message/renderText/remarkPlugins/index.ts
- src/components/Message/renderText/remarkPlugins/plusPlusToEmphasis.ts
- src/components/Message/renderText/renderText.tsx
- src/components/MessageInput/__tests__/EditMessageForm.test.js
Convert markdown `++Some text++` to <ins>Some text</ins>.
> feat: support inserted text element in message markdown rendering

- src/components/ChannelPreview/utils.tsx
- src/components/Message/renderText/__tests__/renderText.test.js
- src/components/Message/renderText/remarkPlugins/imageToLink.ts
- src/components/Message/renderText/remarkPlugins/index.ts
- src/components/Message/renderText/renderText.tsx
Recognize Markdown image links.
Message text
`![Minion](https://octodex.github.com/images/minion.png)`
Would result in empty message bubble:
With this PR the links are recognized and transformed into `<a href={url}>{url | title | alt}</a>`
This PR also fixes an issue when such embedded image links would lead to `<img/>` rendering in `ChannelPreview` text:
Now:
> feat: add imageToLink Remark plugin for converting image MD links to anchor tags

- src/components/Poll/PollActions/PollActions.tsx
- src/components/Poll/__tests__/PollActions.test.js
The permission has to be checked, because part of the suggest-an-option action is casting vote for a given newly created option.
> fix: check cast-poll-vote permission to show "Suggest an option" poll action

- src/components/Message/QuotedMessage.tsx
- src/components/Message/hooks/useActionHandler.ts
- src/utils/useStableCallback.ts
This PR fixes an issue which made it impossible to use `/giphy` command in quoted messages.
Ref: https://getstream.slack.com/archives/C02R5UCGN6N/p1759317325637579
> fix(giphy): allow using actions in quoted messages

- src/components/MessageInput/hooks/useMessageComposer.ts
fixes #2845 
The cached message composer instance was not given the latest message reference when retrieved.
> fix(useMessageComposer): keep editing message composer with up-to-date edited message reference

- src/components/Channel/Channel.tsx
- src/components/Message/MessageSimple.tsx
- src/components/MessageInput/EditMessageForm.tsx
- src/context/ComponentContext.tsx
Closes REACT-600
Allowing to override additionalMessageInputProps, the integrators can control textarea configuration that was not previously available without overriding the whole `MessageSimple`, e.g. number of rows in the textarea:
```
const CustomEditMessageModal = (props: EditMessageModalProps) => (
<EditMessageModal
additionalMessageInputProps={{
...props.additionalMessageInputProps,
maxRows: 10,
}}
/>
);
<Channel
emojiSearchIndex={SearchIndex}
EmojiPicker={EmojiPicker}
EditMessageModal={CustomEditMessageModal}
>
```
Before:
Now:
> feat: allow to override EditMessageModal and thus its additionalMessageInputProps

- src/types/defaultDataInterfaces.ts
Ref: https://getstream.slack.com/archives/C02R5UCGN6N/p1759426108993259
> fix: add "team" property to the `DefaultChannelData` interface
